import type { ReactNode } from 'react';
import Link from '../Link';
import type { Chapter } from '../chapters';
import SolutionVault from '../components/SolutionVault';
import FieldMapLab from './FieldMapLab';
import { CoulombLab, PlateLab } from './ForceLabs';
import PotentialLab from './PotentialLab';
import { CapacitorLab, MatterLab, ParticleLab, SuperpositionLab } from './ExtraLabs';
import RCSelfStudy from './RCSelfStudy';
import { Check, Formula } from './LabUI';
import './electric.css';
import { MathFormula, MathText } from './Math';
import PlottingTasks from './PlottingTasks';
import Glossary from './Glossary';
import BasicsLab from './BasicsLab';
import InfluenceMachine, { ElectroscopeLab } from './InfluenceLab';
import cartoon from './assets/physik-macht-spass.png';
const BP = 'https://www.bildungsplaene-bw.de/,Lde/BP2016BW_ALLG_GYM_PH.V2_IK_11-12-LF_02_01';
const contents = [{ id: 'grundlagen', n: '00', title: 'Grundlagen' }, { id: 'influenz', n: '01', title: 'Influenz & Polarisation' }, { id: 'feldbegriff', n: '02', title: 'Feldbegriff' }, { id: 'feldkraft', n: '03', title: 'Kraft & Feldstärke' }, { id: 'coulomb', n: '04', title: 'Coulomb-Kraft' }, { id: 'potential', n: '05', title: 'Potential & Spannung' }, { id: 'superposition', n: '06', title: 'Superposition' }, { id: 'kondensator', n: '07', title: 'Kondensator & RC' }, { id: 'teilchen', n: '08', title: 'Teilchen & Gravitation' }, { id: 'uebungen', n: '09', title: 'Lexikon & Übungen' }];
function Section({ id, n, title, intro, children }: { id: string; n: string; title: string; intro: string; children: ReactNode }) { return <section id={id} className="ef-section"><header><span className="ef-eyebrow">TEIL {n}</span><h2>{title}</h2><p><MathText>{intro}</MathText></p></header>{children}</section>; }

export default function ElectricFieldChapter({ chapter }: { chapter: Chapter }) {
  return <main className="ef-page"><header className="site-header compact"><Link href="/" className="brand"><span className="mini-atom">✦</span><span>Physik-Lernlabor</span></Link><Link href="/" className="back-link">← Alle Kapitel</Link></header>
  <article className="chapter-page shell ef-chapter"><header className="ef-hero"><div><span className="kicker">KAPITEL 01 · BILDUNGSPLAN 3.6.2.1 · LEISTUNGSFACH</span><h1>Elektrisches Feld.<br /><em>Von Grund auf.</em></h1><p>Warum ziehen sich manche Körper an? Wie misst man ein unsichtbares Feld? Vom einfachen Stromkreis bis zur Bewegung geladener Teilchen: ausprobieren, beobachten und verstehen.</p><div className="ef-hero-actions"><a className="button button-primary" href="#grundlagen">Mit Teil 00 starten →</a><a href="#glossar">Zum Physik-Lexikon</a></div></div><figure className="ef-cartoon"><img src={cartoon} width="1254" height="1254" alt="Eine neugierige Glühlampe mit Brille entdeckt zwei geladene Kugeln im Labor." /><figcaption>Physik macht Spaß. Vor allem, wenn's klickt.</figcaption></figure></header>
  <nav className="ef-nav" aria-label="Teile des ersten Kapitels">{contents.map(c => <a key={c.id} href={`#${c.id}`}><span>Teil {c.n}</span>{c.title}</a>)}</nav>
  <details className="ef-coverage"><summary>Bildungsplan-Kompass · alle 11 Kompetenzen im Überblick</summary><p>Zuordnung zum <a href={BP} target="_blank" rel="noreferrer">Bildungsplan Physik, Leistungsfach 11/12, Fassung 2022, Abschnitt 3.6.2.1 ↗</a>. Teil 00 wiederholt die Mittelstufe. Anschließend führen die Teile 01–08 durch das elektrische Feld; Teil 09 sammelt Fachbegriffe und Übungen.</p><div className="ef-table-wrap"><table><thead><tr><th>Kompetenz</th><th>Inhalt</th><th>Hier bearbeiten</th></tr></thead><tbody>{[
    ['(1)', 'Anziehung, Abstoßung, Coulomb-Gesetz', 'coulomb', 'Teil 04'], ['(2)', 'Feldmodelle und Superposition', 'feldbegriff', 'Teile 02 und 06'], ['(3)', 'Influenz und Polarisation', 'materie', 'Teil 01'], ['(4)', 'Feldstärke aus einer Kraftmessung', 'feldkraft', 'Teil 03'], ['(5)', 'Feldstärke zwischen Platten', 'feldkraft', 'Teil 03'], ['(6)', 'Kapazität', 'kondensator', 'Teil 07'], ['(7)', 'Geometrie, Dielektrikum, Feldenergie', 'kondensator', 'Teil 07'], ['(8)', 'Exponentielles Auf- und Entladen', 'rc', 'Teil 07'], ['(9)', 'Potential, Spannung, Äquipotentiallinien', 'potential', 'Teil 05'], ['(10)', 'Vergleich mit Gravitation', 'gravitation', 'Teil 08'], ['(11)', 'Bewegung parallel und senkrecht zum Feld', 'teilchen', 'Teil 08'],
  ].map(r => <tr key={r[0]}><td>{r[0]}</td><td>{r[1]}</td><td><a href={`#${r[2]}`}>{r[3]} →</a></td></tr>)}</tbody></table></div></details>

  <Section id="grundlagen" n="00" title="Elektrizität: Das kennst du schon." intro="Frische die Grundbegriffe der Mittelstufe auf: Ladung, Stromstärke, Spannung, Widerstand, Leistung und Energie. Danach misst du selbst im virtuellen Stromkreis."><BasicsLab /></Section>
  <Section id="influenz" n="01" title="Ladungen verschieben und trennen" intro="Ein geladener Körper kann die Ladungsverteilung eines anderen Körpers verändern – auch ohne Berührung. Entscheidend ist, ob Ladungen frei beweglich oder gebunden sind."><h3 id="materie">Influenz oder Polarisation?</h3><MatterLab /><aside className="ef-memory"><b>Übertrage es auf einen Versuch:</b><p>Ein geriebener Kunststoffstab zieht einen neutralen dünnen Wasserstrahl an. Die polaren Wassermoleküle richten sich aus; im inhomogenen Feld überwiegt die Anziehung auf der näheren Seite. Bei einem neutralen Metallkörper ist dagegen die Verschiebung freier Elektronen entscheidend.</p></aside><h3>Das Elektroskop · Ladung nachweisen</h3><ElectroscopeLab /><h3 id="influenzmaschine">Die Influenzmaschine · Ladungstrennung verstehen</h3><InfluenceMachine /><details className="ef-real"><summary>Begriffscheck: Influenz oder Polarisation?</summary><div><p>In einem Metall können sich freie Elektronen über größere Strecken umverteilen: <b>Influenz</b>. In einem Isolator verschieben sich gebundene Ladungen gegeneinander oder vorhandene Dipole richten sich aus: <b>Polarisation</b>. Bei einem zunächst neutralen, isolierten Körper bleibt die Gesamtladung in beiden Fällen null.</p></div></details></Section>

  <Section id="feldbegriff" n="02" title="Was ist ein elektrisches Feld?" intro="Eine geladene Kugel kann eine andere Kugel anziehen oder abstoßen, ohne sie zu berühren. Mit dem Feldmodell beschreiben wir diese Wirkung an jedem Ort im Raum.">
    <div className="ef-concept-grid"><div><span>QUELLE</span><h3>Ladung erzeugt ein Feld.</h3><p>Eine Quellladung Q bzw. eine Anordnung geladener Körper bestimmt das elektrische Feld – auch wenn niemand es gerade misst.</p></div><div><span>PROBE</span><h3>Eine kleine positive Ladung zeigt es an.</h3><p>Die Kraft auf q &gt; 0 legt die Feldrichtung fest. Die Probeladung muss klein genug sein, damit sie die Quellenanordnung kaum verändert.</p></div><div><span>MODELL</span><h3>Ein Pfeil an jedem Ort.</h3><p>Der Feldvektor <MathFormula tex="\vec E" /> gibt Richtung und Stärke an. Für eine negative Ladung ist die Kraft entgegengesetzt gerichtet.</p></div></div>
    <h3>Experiment · Die virtuelle Grießwanne</h3><FieldMapLab />
    <aside className="ef-memory"><b>Feldlinien lesen</b><ul><li>Die Tangente zeigt die Richtung von <MathFormula tex="\vec E" /> und damit von <MathFormula tex="\vec F" /> auf q &gt; 0.</li><li>Feldlinien verlaufen von + nach − bzw. ins Unendliche. Im elektrostatischen Feld sind sie keine geschlossenen Schleifen.</li><li>Sie kreuzen sich nicht. Bei gleicher Zeichenkonvention bedeutet größere Dichte ein stärkeres Feld.</li><li>Homogen: parallel und gleich dicht. Radial: zur Punktladung hin oder von ihr weg. Dipol: gekrümmte Linien zwischen + und −.</li></ul></aside>
    <Check question="Ein Körper besitzt einen Überschuss von 2,0 · 10¹⁰ Elektronen. Wie groß ist der Betrag seiner Ladung in nC? Verwende $e=1{,}602\cdot10^{-19}\,\mathrm C$." answer={3.204} unit="nC" hint="Berechne $|Q|=n\cdot e$ und rechne C in nC um." solution="$|Q|=n\cdot e=2{,}0\cdot10^{10}\cdot1{,}602\cdot10^{-19}\,\mathrm C=3{,}204\,\mathrm{nC}$. Das Vorzeichen der Ladung ist negativ." />
  </Section>

  <Section id="feldkraft" n="03" title="Wie stark wirkt das Feld?" intro="Eine Kraftmessung liefert zunächst F. Erst der Vergleich verschiedener Probeladungen zeigt die Eigenschaft des Feldes: den Quotienten $E=\frac{F}{q}$.">
    <p>Bei derselben Quellenanordnung und am selben Ort gilt <MathFormula tex="F\propto q" />. Ein F-q-Diagramm ergibt eine Ursprungsgerade; ihre Steigung ist die Feldstärke. Die Einheit <MathFormula tex="\frac{\mathrm N}{\mathrm C}" /> bedeutet: Kraft in Newton pro Coulomb Ladung.</p><h3>Experiment · Probeladung im Plattenkondensator</h3><PlateLab />
    <div className="ef-derivation"><h3>Von der Kraft zur Spannung – und zurück</h3><ol><li>Mechanisch: Bei konstanter Kraft in Wegrichtung beträgt die übertragene Energie <MathFormula tex="\Delta E_{\mathrm{el}}=F\cdot d" />.</li><li>Elektrisch: Für den übertragenen Energiebetrag gilt <MathFormula tex="\Delta E_{\mathrm{el}}=q\cdot U" />, wenn die positive Ladung vom höheren zum niedrigeren Potential läuft.</li><li>Gleichsetzen: <MathFormula tex="F\cdot d=q\cdot U" />. Mit <MathFormula tex="E=\frac{F}{q}" /> folgt <MathFormula tex="E=\frac{U}{d}" />.</li></ol><p><b>Voraussetzung:</b> homogenes Feld, Weg von einer Platte zur anderen in Feldrichtung; Randfelder vernachlässigt. Der Abstand d ist in Metern einzusetzen.</p></div>
    <Check question="Auf q = 2,0 nC wirkt F = 8,0 µN. Wie groß ist E?" answer={4000} unit="N/C" hint="$E=\frac{F}{q}$. µN = 10⁻⁶ N, nC = 10⁻⁹ C." solution="$E=\frac{F}{q}=\frac{8{,}0\cdot10^{-6}\,\mathrm N}{2{,}0\cdot10^{-9}\,\mathrm C}=4{,}0\cdot10^3\,\frac{\mathrm{N}}{\mathrm{C}}$." />
    <Check question="Zwischen Platten mit d = 5,0 cm liegt U = 100 V. Berechne E." answer={2000} unit="V/m" hint="Zuerst d = 0,050 m, dann $E=\frac{U}{d}$." solution="$E=\frac{U}{d}=\frac{100\,\mathrm V}{0{,}050\,\mathrm m}=2000\,\frac{\mathrm{V}}{\mathrm{m}}=2000\,\frac{\mathrm{N}}{\mathrm{C}}$." />
    <Check question="Eine positive Probeladung q = 3,0 nC liegt in E = 2000 N/C. Berechne F in µN." answer={6} unit="µN" hint="$F=q\cdot E$. Rechne das Ergebnis von N in µN um." solution="$F=q\cdot E=3{,}0\cdot10^{-9}\,\mathrm C\cdot2000\,\frac{\mathrm{N}}{\mathrm{C}}=6{,}0\,\mathrm{\mu N}$, in Feldrichtung." />
  </Section>

  <Section id="coulomb" n="04" title="Wie beeinflussen Ladung und Abstand die Kraft?" intro="Jetzt verändern wir die Quelle selbst: Eine zweite geladene Kugel übt eine Kraft auf die positive Probekugel am Sensor aus."><CoulombLab /><h3>Vom Kraftgesetz zur Feldstärke</h3><p>Für das Radialfeld einer einzelnen Punktladung folgt aus <MathFormula tex="\frac{F}{q}" /> die Beziehung <MathFormula tex="E=k\cdot\frac{|Q|}{r^2}" />. Der Abstand r wird von der Quellladung aus gemessen.</p><Formula tex={["E_{\\mathrm{Punktladung}}=\\frac{|Q|}{4\\cdot\\pi\\cdot\\varepsilon_0\\cdot r^2}"]} note="Betrag im Vakuum, näherungsweise in Luft. Richtung radial nach außen für Q > 0, nach innen für Q < 0." />
    <Check question="Q = +10 nC und q = +20 nC liegen 10 cm auseinander. Berechne F mit $k=8{,}99\cdot10^9\,\frac{\mathrm N\cdot\mathrm{m^2}}{\mathrm{C^2}}$ in mN." answer={.1798} unit="mN" hint="r = 0,10 m und beide Ladungen in C einsetzen." solution="$F=k\cdot\frac{|Q\cdot q|}{r^2}=0{,}1798\,\mathrm{mN}$. Einsetzen: $Q=10\cdot10^{-9}\,\mathrm C$, $q=20\cdot10^{-9}\,\mathrm C$ und $r=0{,}10\,\mathrm m$. Die Kraft ist abstoßend." />
    <Check question="Bei einem Abstand r beträgt die Kraft 12 mN. Wie groß ist sie bei 2r, wenn beide Ladungen gleich bleiben?" answer={3} unit="mN" hint="$F\propto\frac{1}{r^2}$." solution="$F_{\mathrm{neu}}=\frac{F_{\mathrm{alt}}}{2^2}=\frac{12\,\mathrm{mN}}{4}=3\,\mathrm{mN}$." />
  </Section>

  <Section id="potential" n="05" title="Eine Landkarte der elektrischen Energie" intro="Das Potential φ beschreibt die potentielle Energie pro Ladung. Eine einzelne Potentialangabe braucht einen Bezugspunkt; eine Spannung ist der Unterschied zweier Potentiale.">
    <div className="ef-concept-grid ef-two"><div><h3>Feldlinien fragen nach der Kraft.</h3><p>In welche Richtung würde eine positive Ladung beschleunigen? Das Feld zeigt in Richtung abnehmenden Potentials.</p></div><div><h3>Äquipotentiallinien fragen nach der Energie.</h3><p>Wo hat dieselbe Ladung dieselbe potentielle Energie? Entlang einer solchen Linie ändert sich die potentielle Energie der Ladung nicht. Das heißt nicht, dass auch das Feld null ist.</p></div></div>
    <h3>Experiment · Spannungen in der Wasserwanne messen</h3><PotentialLab />
    <details className="ef-real"><summary>Vom Wasserbecken zum elektrostatischen Dipol</summary><div><p>Auch um zwei entgegengesetzte Punktladungen gibt es gekrümmte Äquipotentiallinien. In der Symmetrieebene zwischen gleich großen Ladungen ist φ = 0 (Bezug im Unendlichen), aber E ≠ 0: Die Felder beider Ladungen zeigen dort in dieselbe Richtung. Die Wasserwanne veranschaulicht die Beziehung zwischen Feldrichtung und Potentiallinien; ihre endlichen Elektroden und Wände verändern die genaue Form.</p></div></details>
    <Check question="$\varphi_A=8\,\mathrm V$, $\varphi_B=3\,\mathrm V$. Wie groß ist $U_{AB}$ nach unserer Konvention?" answer={5} unit="V" hint="$U_{AB}=\varphi_A-\varphi_B$." solution="$U_{AB}=\varphi_A-\varphi_B=8\,\mathrm V-3\,\mathrm V=5\,\mathrm V$. Beim Vertauschen der Messspitzen würde das Voltmeter −5 V anzeigen." />
    <Check question="q = +2,0 nC bewegt sich von A nach B mit $U_{AB}=100\,\mathrm V$. Um welchen Betrag nimmt die kinetische Energie in µJ zu, wenn nur die elektrische Kraft wirkt?" answer={.2} unit="µJ" hint="$\Delta E_{\mathrm{kin}}=q\cdot U_{AB}$, 1 µJ = 10⁻⁶ J." solution="$\Delta E_{\mathrm{kin}}=q\cdot U_{AB}=2{,}0\cdot10^{-9}\,\mathrm C\cdot100\,\mathrm V=0{,}20\,\mathrm{\mu J}$. Die potentielle Energie nimmt um 0,20 µJ ab; bei freier Bewegung nimmt die kinetische entsprechend zu." />
  </Section>

  <Section id="superposition" n="06" title="Mehrere Felder überlagern" intro="An einem Ort können mehrere Quellen zum Feld beitragen. Mit der vektoriellen Addition findest du die gemeinsame Wirkung."><h3>Experiment · Feldvektoren überlagern</h3><SuperpositionLab /><Check question="E₁ = 3 kN/C nach rechts und E₂ = 4 kN/C nach oben stehen senkrecht. Wie groß ist das Gesamtfeld?" answer={5} unit="kN/C" hint="Bei senkrechten Beiträgen gilt Pythagoras." solution="$E_{\mathrm{ges}}=\sqrt{E_1^2+E_2^2}=\sqrt{3^2+4^2}\,\frac{\mathrm{kN}}{\mathrm{C}}=5\,\frac{\mathrm{kN}}{\mathrm{C}}$. Der Winkel zur rechten Richtung beträgt $\alpha=\arctan\frac43\approx53{,}1^\circ$. Einfach 3 + 4 zu rechnen wäre hier falsch." /></Section>

  <Section id="kondensator" n="07" title="Ladung und Energie speichern" intro="Ein Kondensator trennt Ladungen auf zwei isolierten Leitern. Die Kapazität beschreibt, wie viel Ladung bei einer gegebenen Spannung gespeichert werden kann."><p>Hier ist Q der Betrag der Ladung auf <em>einer</em> Platte; die andere trägt −Q. C steht für die Kapazität (Einheit Farad), während C als Einheit hinter einem Ladungswert Coulomb bedeutet. A bezeichnet die überlappende Plattenfläche, d den Plattenabstand, ε₀ die elektrische Feldkonstante und εᵣ die relative Permittivität.</p><h3>Experiment · Den Kondensator verändern</h3><CapacitorLab /><div className="ef-derivation"><h3>Warum steht bei der Feldenergie ein Faktor <MathFormula tex="\frac{1}{2}" />?</h3><p>Beim Laden wächst die Spannung von 0 bis U. Im U-Q-Diagramm gilt <MathFormula tex="U=\frac{Q}{C}" />. Die im Feld gespeicherte Energie entspricht der Dreiecksfläche: <MathFormula tex="E_{\mathrm{Kond}}=\frac{1}{2}\cdot Q\cdot U=\frac{1}{2}\cdot C\cdot U^2" />. Das ist ein anderer Vorgang als eine kleine Ladung q durch ein bereits bestehendes, konstantes Feld zu bewegen; dabei beträgt die übertragene Energie <MathFormula tex="\Delta E_{\mathrm{el}}=q\cdot U" /> für q &gt; 0 und einen Weg in Feldrichtung.</p></div>
    <Check question="Ein Kondensator speichert bei 10 V die Ladung 20 µC. Berechne C in µF." answer={2} unit="µF" hint="$C=\frac{Q}{U}$." solution="$C=\frac{Q}{U}=\frac{20\,\mathrm{\mu C}}{10\,\mathrm V}=2\,\mathrm{\mu F}$." /><Check question="A = 200 cm², d = 2,0 mm, εᵣ = 1. Berechne die Kapazität mit ε₀ = 8,854 · 10⁻¹² F/m in pF." answer={88.54} unit="pF" hint="200 cm² = 0,0200 m², 2,0 mm = 0,0020 m." solution="$C=\varepsilon_0\cdot\varepsilon_r\cdot\frac{A}{d}=88{,}54\,\mathrm{pF}$. Einsetzen: $A=0{,}0200\,\mathrm{m^2}$ und $d=0{,}0020\,\mathrm m$." /><Check question="C = 100 µF ist auf U = 10 V geladen. Berechne die gespeicherte Energie in mJ." answer={5} unit="mJ" hint="$E_{\mathrm{Kond}}=\frac{1}{2}\cdot C\cdot U^2$. 100 µF = 10⁻⁴ F." solution="$E_{\mathrm{Kond}}=\frac{1}{2}\cdot C\cdot U^2=\frac{1}{2}\cdot10^{-4}\,\mathrm F\cdot(10\,\mathrm V)^2=5\,\mathrm{mJ}$." />
    <RCSelfStudy /></Section>

  <Section id="teilchen" n="08" title="Vom Feld zur Bewegung" intro="Wir lassen die Probeladung los: Nun verbindet $F=q\cdot E$ das elektrische Feld mit der Mechanik. Für eine konstante Masse gilt $a=\frac{q\cdot E}{m}$."><ParticleLab /><Formula tex={["\\Delta E_{\\mathrm{kin}}=q\\cdot U_{AB}", "\\Delta E_{\\mathrm{kin}}=\\frac{1}{2}\\cdot m\\cdot\\left(v_B^2-v_A^2\\right)"]} note="Energieerhaltung bei alleiniger Wirkung der elektrischen Kraft; $U_{AB}=\varphi_A-\varphi_B$." /><p>Parallel zum Feld ist die Bewegung geradlinig und gleichmäßig beschleunigt. Bei Anfangsgeschwindigkeit entgegen der Kraft wird das Teilchen zunächst langsamer. Beim senkrechten Eintritt überlagern sich gleichförmige Bewegung und gleichmäßig beschleunigte Querbewegung: eine Parabel entsteht. Für ein positives Teilchen aus der Ruhe und <MathFormula tex="U_{AB}&gt;0" /> folgt <MathFormula tex="v_B=\sqrt{\frac{2\cdot q\cdot U_{AB}}{m}}" />.</p>
    <Check question="Auf ein positiv geladenes Teilchen wirkt F = 6,0 · 10⁻¹⁶ N. Seine Masse ist m = 2,0 · 10⁻²⁷ kg. Gib die Beschleunigung in Einheiten von 10¹¹ m/s² an." answer={3} unit="· 10¹¹ m/s²" hint="$a=\frac{F}{m}$." solution="$a=\frac{F}{m}=\frac{6{,}0\cdot10^{-16}\,\mathrm N}{2{,}0\cdot10^{-27}\,\mathrm{kg}}=3{,}0\cdot10^{11}\,\frac{\mathrm{m}}{\mathrm{s^2}}$, in Richtung der elektrischen Kraft." />
    <h3 id="gravitation">Elektrisches Feld und Gravitationsfeld im Vergleich</h3><div className="ef-table-wrap"><table><thead><tr><th>Aspekt</th><th>Elektrisches Feld</th><th>Gravitationsfeld</th></tr></thead><tbody><tr><th>Quelle</th><td>Ladung Q, positiv oder negativ</td><td>Masse M, klassisch positiv</td></tr><tr><th>Kraft</th><td><MathFormula tex="\vec F=q\cdot\vec E" />; Anziehung oder Abstoßung</td><td><MathFormula tex="\vec F_G=m\cdot\vec g" />; Anziehung</td></tr><tr><th>Radiales Feld</th><td><MathFormula tex="E=k\cdot\frac{|Q|}{r^2}" /></td><td><MathFormula tex="g=\frac{G\cdot M}{r^2}" /></td></tr><tr><th>Homogene Näherung</th><td>Zwischen großen parallelen Platten</td><td>Erdnah in einem kleinen Gebiet</td></tr><tr><th>Potential und Energie</th><td><MathFormula tex="E_{\mathrm{pot}}=q\cdot\varphi" /></td><td><MathFormula tex="E_{\mathrm{pot}}=m\cdot\varphi_G" /></td></tr><tr><th>Abschirmung</th><td>Elektrostatische Abschirmung durch geeignete Leiterhüllen</td><td>Keine vergleichbare Abschirmung bekannt</td></tr></tbody></table></div></Section>

  <Section id="uebungen" n="09" title="Begriffe sichern. Zusammenhänge anwenden." intro="Erkläre jeden Begriff zuerst ohne nachzuschlagen. Bearbeite anschließend die Heftaufgaben mit Skizze, Ansatz, Einheiten und Antwortsatz."><Glossary /><PlottingTasks /><aside className="ef-memory"><b>Einheiten vor dem Einsetzen umrechnen</b><p>1 nC = 10⁻⁹ C · 1 µN = 10⁻⁶ N · 1 cm = 10⁻² m · 1 cm² = 10⁻⁴ m² · 1 µF = 10⁻⁶ F · 1 pF = 10⁻¹² F</p></aside><div className="exercise-heading"><h3>Weiterführende Aufgaben für dein Heft</h3><button className="print-button" onClick={() => window.print()}>Übungen drucken</button></div><div className="exercise-list">{chapter.exercises.map((exercise, index) => <article key={exercise.id}><div><span>{index + 1}</span><b>{exercise.level}</b></div><h3>{exercise.title}</h3><p><MathText>{exercise.prompt}</MathText></p>{exercise.hint && <details className="hint"><summary>Denkanstoß</summary><p><MathText>{exercise.hint}</MathText></p></details>}<div className="paper-lines"><i /><i /><i /></div></article>)}</div><p className="ef-model">Die Kurzübungen in den einzelnen Teilen sind zum selbstständigen Lernen offen. Die Lösungen der weiterführenden Heftaufgaben werden wie bisher von der Lehrkraft freigeschaltet.</p></Section>
  <SolutionVault slug={chapter.slug} exercises={chapter.exercises} renderText={text => <MathText>{text}</MathText>} />
  <footer className="ef-footer"><p>Bildungsplanbezug: <a href={BP} target="_blank" rel="noreferrer">Baden-Württemberg · Physik Leistungsfach · 3.6.2.1 ↗</a> · geprüft am 1. Oktober 2026.</p><p>Die Simulationen liefern ideale, berechnete Modellwerte. Die gesondert gekennzeichneten Messreihen der Diagrammwerkstatt enthalten didaktisch simulierte Streuung. Vergleiche beides mit eigenen Messungen im Unterricht.</p><a href="#grundlagen">↑ Zurück zu Teil 00</a></footer>
  </article></main>;
}
