import ExperimentGuide from './ExperimentGuide';
import { useMemo, useState, type PointerEvent } from 'react';
import { Arrow, Choices, Formula, RealExperiment, Slider, Task, downloadCsv, fmt } from './LabUI';
import { MathFormula } from './Math';
import { NX, NY, contour, solveTank, tankPotential } from './physics';
export default function PotentialLab() {
  const [kind, setKind] = useState('plate'), [u, setU] = useState(10), [ax, setAx] = useState(30), [ay, setAy] = useState(50), [bx, setBx] = useState(100), [by, setBy] = useState(50), [probe, setProbe] = useState('A'), [equip, setEquip] = useState(false), [vectors, setVectors] = useState(false);
  const [points, setPoints] = useState<{ ax: number; ay: number; bx: number; by: number; va: number; vb: number; kind: string; u: number }[]>([]), [drag, setDrag] = useState(false);
  const tank = useMemo(solveTank, []);
  const grid = useMemo(() => kind === 'dipole' ? tank : Float64Array.from({ length: NX * NY }, (_, i) => 1 - (i % NX) / (NX - 1)), [kind, tank]);
  const contours = useMemo(() => Array.from({ length: 9 }, (_, i) => contour(grid, (i + 1) / 10)), [grid]);
  const potential = (x: number, y: number) => u * tankPotential(grid, x / 100, y / 100);
  const va = potential(ax, ay), vb = potential(bx, by);
  function change(v: string) { setKind(v); setAx(30); setAy(50); setBx(v === 'plate' ? 100 : 75); setBy(50); }
  function position(e: PointerEvent<SVGSVGElement>) {
    const p = new DOMPoint(e.clientX, e.clientY).matrixTransform(e.currentTarget.getScreenCTM()!.inverse());
    const x = Math.round(Math.max(0, Math.min(100, (p.x - 40) / 5.6))), y = Math.round(Math.max(0, Math.min(100, (p.y - 40) / 3.36)));
    if (probe === 'A') { setAx(x); setAy(y); } else { setBx(x); setBy(y); }
  }
  return <div className="ef-lab">
    <ExperimentGuide kind="potential" />
    <Task><ol><li>Lasse B an der negativen Elektrode. Finde mindestens vier Orte mit <MathFormula tex="U_{AB}" /> = {fmt(u / 2, 1)} V und speichere sie. Welche Linie entsteht?</li><li>Miss entlang der x-Richtung im Plattenfeld. Gleiche Wegstücke ergeben gleiche Spannungsunterschiede. Berechne <MathFormula tex="E=\frac{U}{d}" /> mit d = 0,20 m.</li><li>Wechsle zu runden Elektroden. Suche wieder Orte gleichen Potentials und blende erst dann die Hilfslinien ein.</li><li>Verschiebe beide Messspitzen auf dieselbe Äquipotentiallinie: Warum zeigt das Voltmeter null, obwohl dort ein Feld vorhanden sein kann?</li></ol></Task><Choices label="Potentialwanne" value={kind} set={change} options={[{ value: 'plate', label: 'Parallele Plattenelektroden' }, { value: 'dipole', label: 'Zwei runde Elektroden' }]} />
    <div className="ef-lab-grid"><div><Slider label="Spannung an der Wanne" value={u} set={setU} min={2} max={12} unit="V" /><Choices label="Messspitze zum Verschieben" value={probe} set={setProbe} options={[{ value: 'A', label: 'A · rot' }, { value: 'B', label: 'B · schwarz' }]} /><Slider label="Messspitze A: x" value={ax} set={setAx} min={0} max={100} unit="%" /><Slider label="Messspitze A: y" value={ay} set={setAy} min={0} max={100} unit="%" /><Slider label="Messspitze B: x" value={bx} set={setBx} min={0} max={100} unit="%" /><Slider label="Messspitze B: y" value={by} set={setBy} min={0} max={100} unit="%" /></div><div>
    <svg className="ef-scene ef-probe-scene" viewBox="0 0 640 435" role="img" aria-label="Wasserwanne mit zwei verschiebbaren Spannungsmessspitzen" onPointerDown={e => { e.currentTarget.setPointerCapture(e.pointerId); setDrag(true); position(e); }} onPointerMove={e => { if (drag) position(e); }} onPointerUp={() => setDrag(false)} onPointerCancel={() => setDrag(false)}>
      <rect x="30" y="30" width="580" height="356" rx="15" fill="#e7f4fa" stroke="#a6cedd" /><rect x="40" y="40" width="560" height="336" fill="#edf7fb" />
      <g stroke="#d4e5eb" strokeWidth=".8">{Array.from({ length: 21 }, (_, i) => <line key={`x${i}`} x1={40 + i * 28} x2={40 + i * 28} y1="40" y2="376" />)}{Array.from({ length: 13 }, (_, i) => <line key={`y${i}`} x1="40" x2="600" y1={40 + i * 28} y2={40 + i * 28} />)}</g>
      {equip && contours.map((d, i) => <path key={i} d={d} stroke="#6658b1" strokeWidth="1.5" strokeDasharray="5 4" fill="none" />)}
      {vectors && Array.from({ length: 72 }, (_, i) => { const x = (i % 12 + .5) / 12, y = (Math.floor(i / 12) + .5) / 6; const ex = tankPotential(grid, x - .004, y) - tankPotential(grid, x + .004, y), ey = (tankPotential(grid, x, y - .004) - tankPotential(grid, x, y + .004)) * 20 / 12; const n = Math.hypot(ex, ey); return n < 1e-7 ? null : <Arrow key={i} x={40 + 560 * x} y={40 + 336 * y} dx={15 * ex / n} dy={15 * ey / n} color="#2994a0" />; })}
      {kind === 'plate' ? <g><rect x="34" y="40" width="8" height="336" fill="#c7436c" /><rect x="598" y="40" width="8" height="336" fill="#4862d5" /></g> : <g><ellipse cx="180" cy="208" rx="21" ry="21" fill="#c7436c" /><ellipse cx="460" cy="208" rx="21" ry="21" fill="#4862d5" /></g>}
      <text x="42" y="23" fill="#a02c55">Elektrode +: {u} V</text><text x="435" y="23" fill="#364ead">Elektrode −: 0 V</text>
      {points.filter(p => p.kind === kind && p.u === u).map((p, i) => <g key={i}><circle cx={40 + p.ax * 5.6} cy={40 + p.ay * 3.36} r="4" fill="#b78016" /><text x={45 + p.ax * 5.6} y={35 + p.ay * 3.36} fontSize="12" fill="#7d5a16">{fmt(p.va, 1)}</text></g>)}
      {[{ x: ax, y: ay, color: '#c7436c', label: 'A' }, { x: bx, y: by, color: '#182743', label: 'B' }].map(p => <g key={p.label}><circle cx={40 + p.x * 5.6} cy={40 + p.y * 3.36} r="11" fill="white" stroke={p.color} strokeWidth="4" /><text x={40 + p.x * 5.6} y={44 + p.y * 3.36} fontSize="12" textAnchor="middle" fill={p.color}>{p.label}</text></g>)}
      <text x="320" y="416" textAnchor="middle">x → · y ↓ · Wanne 20 cm × 12 cm</text>
    </svg><div className="ef-readings"><div><small>Voltmeter <MathFormula tex="U_{AB}=\varphi_A-\varphi_B" /></small><strong>{fmt(va - vb)} V</strong></div><div><small>Modellpotentiale zum Bezug 0 V</small><strong><MathFormula tex="\varphi_A" /> = {fmt(va)} V</strong><span><MathFormula tex="\varphi_B" /> = {fmt(vb)} V</span></div></div></div></div>
    <div className="ef-toolbar"><button aria-pressed={equip} onClick={() => setEquip(!equip)}>Äquipotentiallinien {equip ? 'ausblenden' : 'einblenden'}</button><button aria-pressed={vectors} onClick={() => setVectors(!vectors)}>Feldrichtungen {vectors ? 'ausblenden' : 'einblenden'}</button><button disabled={points.length >= 25} onClick={() => setPoints(p => [...p, { ax, ay, bx, by, va, vb, kind, u }])}>Messpunkt speichern ({points.length}/25)</button><button onClick={() => setPoints([])}>Messpunkte löschen</button><button disabled={!points.length} onClick={() => downloadCsv('potential-messwerte.csv', [['Anordnung', 'U Wanne / V', 'x A / %', 'y A / %', 'x B / %', 'y B / %', 'phi A / V', 'phi B / V', 'U AB / V'], ...points.map(p => [p.kind === 'plate' ? 'Platten' : 'Rundelektroden', p.u, p.ax, p.ay, p.bx, p.by, p.va, p.vb, p.va - p.vb])])}>CSV herunterladen</button></div>
    {points.length > 0 && <div className="ef-table-wrap"><table><caption>Messprotokoll · orange Markierungen: gespeicherte Orte und Potentiale von A für die aktuelle Anordnung und Spannung</caption><thead><tr><th>Anordnung</th><th><MathFormula tex="\frac{U}{\mathrm V}" /></th><th>A (x; y) in %</th><th>B (x; y) in %</th><th><MathFormula tex="\frac{\varphi_A}{\mathrm V}" /></th><th><MathFormula tex="\frac{\varphi_B}{\mathrm V}" /></th><th><MathFormula tex="\frac{U_{AB}}{\mathrm V}" /></th></tr></thead><tbody>{points.map((p, i) => <tr key={i}><td>{p.kind === 'plate' ? 'Platten' : 'Rund'}</td><td>{p.u}</td><td>{p.ax}; {p.ay}</td><td>{p.bx}; {p.by}</td><td>{fmt(p.va)}</td><td>{fmt(p.vb)}</td><td>{fmt(p.va - p.vb)}</td></tr>)}</tbody></table></div>}
    <Formula tex={["\\varphi=\\frac{E_{\\mathrm{pot}}}{q}", "U_{AB}=\\varphi_A-\\varphi_B"]} note="Konvention: $U_{AB}=\varphi_A-\varphi_B$. Bewegung A → B: $\Delta E_{\mathrm{pot}}=-q\cdot U_{AB}$. Wirkt nur die elektrische Kraft, gilt $\Delta E_{\mathrm{kin}}=q\cdot U_{AB}$." />
    <p className="ef-model">Das Voltmeter misst immer zwischen zwei Punkten. Nur wenn B am gewählten Nullpotential bleibt, zeigt es direkt <MathFormula tex="\varphi_A" /> an. Die gestrichelten Linien liegen bei 10 %, 20 %, …, 90 % der Wannenspannung. Alle Feldpfeile sind zur Darstellung gleich lang. Das Modell löst die zweidimensionale Laplace-Gleichung für eine gleichmäßig leitende Wasserschicht mit isolierenden Wänden und festen Elektrodenpotentialen. Ein räumlicher Dipol aus Punktladungen besitzt andere quantitative Potentialwerte.</p>

    <RealExperiment title="Potential in der Wasserwanne kartieren"><p><b>Material:</b> flache nichtleitende Wanne mit gleichmäßig hoher, schwach leitender Wasserschicht, zwei Elektroden, schulgeeignete Kleinspannungsquelle (z. B. 6 V), hochohmiges Voltmeter, zwei Messspitzen und Rasterpapier unter der Wanne.</p><p><b>Ablauf:</b> Gerade Elektroden gegenüber aufstellen, Bezugsspitze an einer Elektrode festhalten und mit der zweiten Spitze Orte gleicher Spannung suchen. Je Linie mehrere Punkte aufnehmen. Danach beide Bezugspunkte variieren und mit runden Elektroden wiederholen. Nur sichere Kleinspannung verwenden, keine Netzspannung oder Hochspannung an der Wasserwanne.</p><p><b>Deutung:</b> In der Wanne fließt ein kleiner stationärer Strom. Ihr Potentialbild ist ein Analogiemodell für elektrische Felder, kein isolierender Kondensator. Elektrolyse, Elektrodenpolarisation und eine ungleichmäßige Wassertiefe können die Messung beeinflussen.</p></RealExperiment>
  </div>;
}
