import type { ReactNode } from 'react';
import { Chart, Check, Formula, RevealChart } from './LabUI';
import { MathFormula, MathText } from './Math';
function T({ text }: { text: string }) { return <MathText>{text}</MathText>; }
function Answer({ children }: { children: ReactNode }) { return <details className="rc-solution"><summary>Lösung mit Rechenweg und Erwartungshorizont</summary><div>{children}</div></details>; }
function Exercise({ number, title, level, children }: { number: number; title: string; level: string; children: ReactNode }) {
  return <article className="rc-assignment rc-exam-task"><span className="ef-eyebrow">AUFGABE {number} · {level}</span><h4>{title}</h4>{children}<div className="rc-writing-space" aria-hidden="true" /></article>;
}
export default function RCPractice() {
  const times = [0, 1, 2, 3, 4, 6], currents = [200, 121.3, 73.6, 44.6, 27.1, 9.96];
  const dots = times.map((t, i) => ({ x: t, y: currents[i] }));
  return <div className="rc-practice">
    <h4>6.3 · Pflichtaufgaben für die letzten 40 Minuten</h4>
    <p>Bearbeite Aufgaben 14 bis 19 im Heft. Aufgaben 14, 16 und 17 sind kurze Aufgaben; plane mehr Zeit für die Messwertauswertung und den Umschaltvorgang. Schreibe bei jeder Rechnung zuerst „gegeben“ und „gesucht“. Ergänze zu deinem Ansatz: „Ich benutze diese Gleichung, weil …“. Öffne die Lösungen erst nach einem eigenen Versuch. Brauchst du Hilfe beim Ansatz, gehe zur <a href="#rc-equation-choice">Tabelle für die Gleichungswahl</a>.</p>
    <Exercise number={14} title="Laden: alle Größen aus derselben Funktion bestimmen" level="AFB I · ca. 5 min">
      <p><T text="Ein zunächst leerer Kondensator mit $C=47\,\mathrm{\mu F}$ wird über $R=100\,\mathrm{k\Omega}$ an $U_0=12\,\mathrm V$ geladen." /></p>
      <ol><li><T text="Berechne $\tau$, $Q_{\max}$ und $I_0$." /></li><li><T text="Berechne $U_C$, $U_R$, Q und I nach genau einer Zeitkonstante." /></li><li>Prüfe, ob die beiden Bauteilspannungen die Quellenspannung ergeben. Überprüfe einen Wert mit der Übungsvoreinstellung im Experiment.</li></ol>
      <details className="rc-hint"><summary>Starthilfe zu Aufgabe 14</summary><div><p>Der Kondensator ist anfangs leer: Es handelt sich um den Standardfall des Aufladens. Rechne R und C in Ohm und Farad um. Bestimme erst R · C, dann die erreichbare Plattenladung und den Anfangsstrom. Bei t = τ ist der Exponent −1. Verwende für U_C die Ladefunktion mit Klammer; die Spannung am Widerstand ist der Rest von U₀.</p></div></details>
      <Answer><Formula tex={['\\tau=100\\cdot10^3\\,\\mathrm\\Omega\\cdot47\\cdot10^{-6}\\,\\mathrm F=4{,}7\\,\\mathrm s', 'Q_{\\max}=47\\,\\mathrm{\\mu F}\\cdot12\\,\\mathrm V=564\\,\\mathrm{\\mu C}', 'I_0=\\frac{12\\,\\mathrm V}{100\\cdot10^3\\,\\mathrm\\Omega}=0{,}12\\,\\mathrm{mA}', 'U_C(\\tau)=12\\,\\mathrm V\\cdot(1-\\mathrm e^{-1})\\approx7{,}59\\,\\mathrm V', 'U_R(\\tau)=12\\,\\mathrm V\\cdot\\mathrm e^{-1}\\approx4{,}41\\,\\mathrm V', 'Q(\\tau)=564\\,\\mathrm{\\mu C}\\cdot(1-\\mathrm e^{-1})\\approx356{,}52\\,\\mathrm{\\mu C}', 'I(\\tau)=0{,}12\\,\\mathrm{mA}\\cdot\\mathrm e^{-1}\\approx0{,}0441\\,\\mathrm{mA}']} /><p>Die Summe von 7,59 V und 4,41 V beträgt gerundet 12 V. Der Strom ist kleiner als am Anfang, während Spannung und Ladung noch steigen.</p></Answer>
    </Exercise>
    <Exercise number={15} title="Eine unbekannte Kapazität aus Messdaten bestimmen" level="AFB II · ca. 9 min">
      <p><T text="Ein geladener Kondensator entlädt sich über $R=100\,\mathrm\Omega$. Die Tabelle enthält gerundete ideale Stromstärkebeträge. Die Anfangsspannung und die Kapazität sind unbekannt." /></p>
      <div className="ef-table-wrap"><table><caption>Neue Auswertungsreihe · Zeit in Millisekunden · 1 ms = 0,001 s</caption><thead><tr><th>t in ms</th>{times.map(t => <th key={t}>{t}</th>)}</tr></thead><tbody><tr><th><MathFormula tex="|I|" /> in mA</th>{currents.map(value => <td key={value}>{value.toLocaleString('de-DE')}</td>)}</tr></tbody></table></div>
      <ol><li>Zeichne die Messkreuze in ein Strombetrag-Zeit-Diagramm. Gib an, auf welcher Seite der Zeitachse diese Werte bei unserer festen Stromrichtung liegen würden.</li><li><T text="Bestimme $U_0$ aus $I_0$ und R. Bestimme $\tau$ anhand des Werts bei ungefähr 36,8 % des Anfangsstroms. Berechne C." /></li><li><T text="Berechne $U_C(4\,\mathrm{ms})$ und die Anfangsladung. Erkläre, warum U und I-Betrag dieselbe zeitliche Form besitzen." /></li></ol>
      <details className="rc-hint"><summary>Starthilfe zu Aufgabe 15</summary><div><p>Du hast Stromwerte, aber noch keine Kapazität. Beim Entladen hängen der Anfangsstrombetrag und die Anfangsspannung durch das Ohm’sche Gesetz zusammen. Den Zeitpunkt für 36,8 % liest du aus der Tabelle ab. Diesen Zeitwert musst du vor der Berechnung der Kapazität von Millisekunden in Sekunden umrechnen.</p></div></details>
      <div className="rc-screen-chart"><RevealChart xMax={6} yMax={210} xLabel="t in ms" yLabel="|I| in mA" dots={dots} /></div>
      <div className="rc-print-chart"><Chart xMax={6} yMax={210} xLabel="t in ms" yLabel="|I| in mA" blank /></div>
      <Answer><p>Der positive Strombetrag fällt. Der vorzeichenbehaftete Strom wäre negativ und würde sich von unten der Null nähern.</p><Formula tex={['U_0=R\\cdot I_0=100\\,\\mathrm\\Omega\\cdot0{,}200\\,\\mathrm A=20\\,\\mathrm V', '\\frac{I_0}{\\mathrm e}\\approx73{,}58\\,\\mathrm{mA}\\quad\\Rightarrow\\quad\\tau\\approx2{,}0\\,\\mathrm{ms}', 'C=\\frac{\\tau}{R}=\\frac{2{,}0\\cdot10^{-3}\\,\\mathrm s}{100\\,\\mathrm\\Omega}=20\\,\\mathrm{\\mu F}', 'U_C(4\\,\\mathrm{ms})=20\\,\\mathrm V\\cdot\\mathrm e^{-\\frac{4\\,\\mathrm{ms}}{2\\,\\mathrm{ms}}}\\approx2{,}71\\,\\mathrm V', 'Q_0=C\\cdot U_0=20\\,\\mathrm{\\mu F}\\cdot20\\,\\mathrm V=400\\,\\mathrm{\\mu C}']} /><p><T text="Beim Entladen gilt $\lvert I\rvert=\frac{U_C}{R}$. Bei konstantem R unterscheiden sich Spannung und Strombetrag nur durch einen konstanten Maßstabsfaktor. Nutze zum Einsetzen in C = τ/R Sekunden, nicht die bloße Zahl 2 ohne Einheit." /></p></Answer>
    </Exercise>
    <Exercise number={16} title="Wie lange bis 90 %? Wie lange bis nur noch 10 %?" level="AFB II · ca. 6 min">
      <p><T text="Für einen RC-Kreis gilt $\tau=10\,\mathrm s$. Bestimme die Zeit, bis ein leerer Kondensator 90 % seiner Endspannung erreicht. Bestimme die Zeit, bis ein geladener Kondensator auf 10 % seiner Anfangsspannung entladen ist. Leite beide Zeitgleichungen her." /></p>
      <details className="rc-hint"><summary>Hilfe zum Logarithmus</summary><p><T text="Teile zuerst durch $U_0$ und isoliere den Exponentialterm. Wende dann auf beide Seiten $\ln$ an. Es gilt $\ln(\mathrm e^x)=x$. Beim Laden bleiben nach 90 % erreichter Spannung noch 10 % übrig. Erst wenn links der Exponentialterm allein steht, darfst du den Logarithmus anwenden. Du darfst den Logarithmus einer Differenz nicht in zwei Logarithmen zerlegen." /></p><p>Wenn du nicht weißt, weshalb ln hier hilft, lies die Rechenhilfe in Schritt 5.3 erneut.</p></details>
      <Answer><p>Beim Laden:</p><Formula tex={['0{,}90=1-\\mathrm e^{-\\frac{t}{\\tau}}', '\\mathrm e^{-\\frac{t}{\\tau}}=0{,}10', '-\\frac{t}{\\tau}=\\ln(0{,}10)', 't=-\\tau\\cdot\\ln(0{,}10)=10\\,\\mathrm s\\cdot\\ln(10)\\approx23{,}03\\,\\mathrm s']} /><p>Beim Entladen setzt man direkt den verbleibenden Anteil 0,10 ein und erhält dieselbe Zeit. Allgemein bei erreichtem Ladeanteil a und verbleibendem Entladeanteil b:</p><Formula tex={['t_{\\mathrm L}=-\\tau\\cdot\\ln(1-a),\\qquad0\\leq a<1', 't_{\\mathrm E}=-\\tau\\cdot\\ln(b),\\qquad0<b\\leq1']} /><p>Für a = 1 bzw. b = 0 ist kein endlicher Zeitpunkt möglich. Der Logarithmus von null ist nicht definiert.</p></Answer>
      <Check question="Wie lange dauert es bei τ = 10 s, bis beim Aufladen 99 % der Endspannung erreicht sind?" answer={-10 * Math.log(.01)} unit="s" hint="Nach 99 % fehlen 1 %. Verwende ln(0,01)." solution="$t=-10\,\mathrm s\cdot\ln(0{,}01)\approx46{,}05\,\mathrm s$. Das sind ungefähr 4,61 Zeitkonstanten." />
    </Exercise>
    <Exercise number={17} title="Vier Aussagen beurteilen und verbessern" level="AFB II · ca. 5 min">
      <ol><li>„Ein größerer Kondensator braucht länger, weil bei derselben Spannung mehr Ladung getrennt werden muss.“</li><li>„Wenn C doppelt so groß ist, ist der Ladestrom bei t = 0 doppelt so groß.“</li><li>„Nach einer Halbwertszeit ist ein Kondensator halb geladen; nach zwei ist er deshalb ganz geladen.“</li><li>„Die I-t-Fläche bis zu einer Zeit T ist beim Entladen immer die Restladung.“</li></ol><p>Schreibe zu jeder Aussage „richtig“ oder „falsch“ und begründe. Formuliere die falschen Aussagen fachlich richtig.</p>
      <Answer><ol><li><T text="Richtig bei gleichem R und $U_0$: $Q_{\max}=C\cdot U_0$ und $\tau=R\cdot C$ wachsen mit C." /></li><li><T text="Falsch: Für einen anfangs leeren Kondensator ist $I_0=\frac{U_0}{R}$ unabhängig von C." /></li><li>Falsch: Nach zwei Halbwertszeiten fehlen noch 25 %; erreicht sind 75 %. Die fehlende Spannung halbiert sich, der erreichte Anteil wächst um den jeweils halben Rest.</li><li><T text="Falsch: $\int_0^T I\,\mathrm dt=Q(T)-Q_0$ ist die vorzeichenbehaftete Ladungsänderung. Die Fläche mit $\lvert I\rvert$ ist die abgeflossene Ladung. Die Restladung ist $Q_0-\int_0^T\lvert I\rvert\,\mathrm dt$." /></li></ol></Answer>
    </Exercise>
    <Exercise number={18} title="Umschalten vor dem vollständigen Aufladen" level="AFB II · ca. 8 min">
      <p><T text="Im Grundversuch wird der leere Kondensator nur 5 s lang an 20 V geladen. Dann wird die Quelle abgetrennt und auf Entladen durch denselben Widerstand geschaltet. R = 1 MΩ, C = 10 µF." /></p>
      <ol><li>Bestimme die Kondensatorspannung unmittelbar vor und unmittelbar nach dem Umschalten.</li><li>Bestimme den Ladestrom unmittelbar davor und den Entladestrom unmittelbar danach.</li><li>Berechne die Spannung 10 s nach dem Umschalten. Prüfe im Experiment, indem du direkt von A nach E wechselst.</li></ol>
      <p><b>Vorgehen:</b> Teile die Aufgabe in zwei Phasen. Rechne zuerst die 5 s lange Ladephase. Das Ergebnis für die Spannung wird zum Anfangswert der Entladephase. Zeichne im Heft eine Zeitachse und markiere den Umschaltzeitpunkt.</p>
      <details className="rc-hint"><summary>Ein neuer Anfangswert – keine neue physikalische Regel</summary><p><T text="Nenne die erreichte Spannung beim Umschalten $U_i$. Für die neue Entladephase beginnt die Zeit s bei null; die frühere Quellenspannung ist nicht automatisch die neue Anfangsspannung. Wegen $Q(0)=C\cdot U_i$ hat die Lösung dieselbe Form mit $U_i$ statt $U_0$:" /></p><Formula tex="U_C(s)=U_i\cdot\mathrm e^{-\frac{s}{R\cdot C}}" /></details>
      <Answer><Formula tex={['U_i=20\\,\\mathrm V\\cdot(1-\\mathrm e^{-0{,}5})\\approx7{,}869\\,\\mathrm V', 'I_{\\mathrm{vor}}=\\frac{20\\,\\mathrm V-7{,}869\\,\\mathrm V}{1\\,\\mathrm{M\\Omega}}\\approx+0{,}01213\\,\\mathrm{mA}', 'I_{\\mathrm{nach}}=-\\frac{7{,}869\\,\\mathrm V}{1\\,\\mathrm{M\\Omega}}\\approx-0{,}007869\\,\\mathrm{mA}', 'U_C(s=10\\,\\mathrm s)=7{,}869\\,\\mathrm V\\cdot\\mathrm e^{-1}\\approx2{,}895\\,\\mathrm V']} /><p>Die Spannung beträgt unmittelbar auf beiden Seiten des Umschaltzeitpunkts 7,869 V. Sie bleibt stetig. Der Strom springt wegen der veränderten Schaltung. Für die zweite Rechnung ist die seit dem Umschalten vergangene Zeit maßgeblich; die gesamte Zeit seit Ladebeginn wäre bereits 15 s.</p></Answer>
    </Exercise>
    <Exercise number={19} title="Transportierte Ladung und Restladung unterscheiden" level="AFB II · ca. 7 min">
      <p>Beim Entladen im Grundversuch werden diese Beträge gemessen:</p><div className="ef-table-wrap"><table><thead><tr><th>t in s</th><th>0</th><th>5</th><th>10</th></tr></thead><tbody><tr><th><MathFormula tex="|I|" /> in mA</th><td>0,02000</td><td>0,01213</td><td>0,00736</td></tr></tbody></table></div>
      <ol><li>Bestimme die bis 10 s abgeflossene Ladung näherungsweise mit zwei Trapezen.</li><li>Bestimme daraus die Restladung. Vergleiche mit der exakten Restladung aus der Exponentialfunktion.</li><li>Bestimme das Vorzeichen der Stromfläche, wenn du statt des Betrags den vorzeichenbehafteten Entladestrom benutzt.</li></ol>
      <Answer><Formula tex={['Q_{\\mathrm{ab}}\\approx\\frac{0{,}02000+0{,}01213}{2}\\,\\mathrm{mA}\\cdot5\\,\\mathrm s+\\frac{0{,}01213+0{,}00736}{2}\\,\\mathrm{mA}\\cdot5\\,\\mathrm s', 'Q_{\\mathrm{ab}}\\approx0{,}12905\\,\\mathrm{mC}=129{,}05\\,\\mathrm{\\mu C}', 'Q_{\\mathrm{Rest}}\\approx200\\,\\mathrm{\\mu C}-129{,}05\\,\\mathrm{\\mu C}=70{,}95\\,\\mathrm{\\mu C}', 'Q(10\\,\\mathrm s)=200\\,\\mathrm{\\mu C}\\cdot\\mathrm e^{-1}\\approx73{,}58\\,\\mathrm{\\mu C}']} /><p>Die Trapeze überschätzen die abgeflossene Ladung leicht. Darum unterschätzt die so ermittelte Restladung den exakten Wert. Mit dem negativen I ist die angenäherte Stromfläche −129,05 µC; sie ist die Änderung der Plattenladung.</p></Answer>
    </Exercise>
    <details className="rc-extension"><summary>Weitere Übungsaufgaben · Vertiefung nach den sechs Zeitstunden</summary><div>
      <p>Diese Aufgaben sind Ergänzungen für schnelleres Arbeiten oder die Wiederholung vor einer Klausur. Ihre Lösungen bleiben einzeln aufklappbar.</p>
      <Exercise number={20} title="Was geschieht mit der Energie beim Entladen?" level="AFB II">
        <p><T text="Im Grundversuch sind anfangs 20 V am Kondensator. Verwende die bekannte Energiebeziehung $E_{\mathrm{Kond}}=\frac12\cdot C\cdot U_C^2$. Leite den Energieverlauf beim Entladen her. Wie viel Energie liegt anfangs vor? Nach welcher Zeit ist die Hälfte davon übrig? Vergleiche diese Zeit mit der Spannungs-Halbwertszeit." /></p>
        <Answer><Formula tex={['E_{\\mathrm{Kond}}(t)=\\frac12\\cdot C\\cdot\\left(U_0\\cdot\\mathrm e^{-\\frac{t}{\\tau}}\\right)^2=E_0\\cdot\\mathrm e^{-\\frac{2\\cdot t}{\\tau}}', 'E_0=\\frac12\\cdot10\\,\\mathrm{\\mu F}\\cdot(20\\,\\mathrm V)^2=2{,}0\\,\\mathrm{mJ}', '\\frac12=\\mathrm e^{-\\frac{2\\cdot T_E}{\\tau}}\\quad\\Rightarrow\\quad T_E=\\frac{\\tau\\cdot\\ln(2)}{2}\\approx3{,}47\\,\\mathrm s', '\\Delta E_{\\mathrm{th}}(t)=E_0-E_{\\mathrm{Kond}}(t)']} /><p>Die Energie-Halbwertszeit ist halb so groß wie die Spannungs-Halbwertszeit, weil die Energie vom Quadrat der Spannung abhängt. Im idealen Entladekreis nimmt die thermische Energie des Widerstands um die abgenommene Feldenergie zu. Es verschwindet keine Energie.</p></Answer>
      </Exercise>
      <Exercise number={21} title="Eine unbekannte Zeitkonstante aus zwei Spannungen" level="AFB II">
        <p><T text="Beim Entladen werden $U_C(2\,\mathrm s)=8{,}00\,\mathrm V$ und $U_C(8\,\mathrm s)=2{,}41\,\mathrm V$ gemessen. Leite eine Gleichung für τ her, in der die unbekannte Anfangsspannung nicht vorkommt. Bestimme τ und bei $R=100\,\mathrm{k\Omega}$ auch C." /></p>
        <Answer><p>Durch Division der beiden Spannungsfunktionen kürzt sich der Anfangswert.</p><Formula tex={['\\frac{U_C(t_2)}{U_C(t_1)}=\\mathrm e^{-\\frac{t_2-t_1}{\\tau}}', '\\tau=-\\frac{t_2-t_1}{\\ln\\left(\\frac{U_C(t_2)}{U_C(t_1)}\\right)}', '\\tau=-\\frac{6\\,\\mathrm s}{\\ln\\left(\\frac{2{,}41}{8{,}00}\\right)}\\approx5{,}00\\,\\mathrm s', 'C=\\frac{\\tau}{R}\\approx\\frac{5{,}00\\,\\mathrm s}{100\\cdot10^3\\,\\mathrm\\Omega}=50{,}0\\,\\mathrm{\\mu F}']} /><p>Die kleinen Rundungen der Messwerte begrenzen die Genauigkeit. Mit zeitlichem Abstand t₂ − t₁ funktioniert die Auswertung auch dann, wenn die Aufnahme nicht bei t = 0 beginnt.</p></Answer>
      </Exercise>
      <Exercise number={22} title="Ein Zeitgeber als Anwendung" level="AFB II">
        <p><T text="Ein idealisiertes Messgerät löst ein Signal aus, sobald ein anfangs leerer Kondensator beim Laden 10 V erreicht. Die Quelle liefert 12 V, $C=1000\,\mathrm{\mu F}$. Wähle R so, dass das Signal nach 2 s ausgelöst wird. Das Messgerät zieht bis zum Auslösen keinen Strom." /></p>
        <Answer><Formula tex={['\\frac{10}{12}=1-\\mathrm e^{-\\frac{2\\,\\mathrm s}{R\\cdot C}}', 'R=-\\frac{t}{C\\cdot\\ln\\left(1-\\frac{U_C}{U_0}\\right)}', 'R=-\\frac{2\\,\\mathrm s}{10^{-3}\\,\\mathrm F\\cdot\\ln\\left(1-\\frac{10}{12}\\right)}\\approx1116\\,\\mathrm\\Omega']} /><p>Ein Widerstand von ungefähr 1,12 kΩ ergibt im idealen Modell die gewünschte Zeit. Ein größerer R würde das Signal später auslösen. Die Annahme eines unbelasteten Kondensators ist hier entscheidend.</p></Answer>
      </Exercise>
      <Exercise number={23} title="Die Exponentialfunktion durch Logarithmieren prüfen" level="AFB III">
        <p><T text="Für eine Entladung wird $y=\ln\left(\frac{U_C(t)}{U_0}\right)$ gegen t aufgetragen. Leite her, warum idealerweise eine Gerade entsteht. Welche Bedeutung hat ihre Steigung? Was könnte eine deutliche Krümmung bei realen Messwerten anzeigen?" /></p>
        <Answer><Formula tex="y=\ln\left(\mathrm e^{-\frac{t}{\tau}}\right)=-\frac{1}{\tau}\cdot t" /><p><T text="Die Steigung ist $-\frac{1}{\tau}$ mit der Einheit $\mathrm{s}^{-1}$, der Anfangswert ist null. Eine deutliche Krümmung kann zeigen, dass die Annahme eines einzigen konstanten RC-Produkts nicht ausreicht. Mögliche Ursachen sind eine veränderliche Kapazität, zusätzliche Leckströme, Messgerätebelastung oder eine unzureichend berücksichtigte Messunsicherheit. Eine einzelne Abweichung beweist noch keine bestimmte Ursache." /></p></Answer>
      </Exercise>
      <Exercise number={24} title="Laden mit einer bereits vorhandenen Anfangsspannung" level="AFB III">
        <p><T text="Ein Kondensator hat bei Beginn des Ladens bereits die Spannung $U_i$. Überprüfe durch Ableiten und Einsetzen in die Spannungsbilanz die allgemeinere Funktion $U_C(t)=U_0+(U_i-U_0)\cdot\mathrm e^{-\frac{t}{R\cdot C}}$. Bestimme die Stromfunktion. Was geschieht für $U_i=U_0$ und für $U_i>U_0$?" /></p>
        <Answer><Formula tex={['I(t)=C\\cdot\\frac{\\mathrm dU_C}{\\mathrm dt}=\\frac{U_0-U_i}{R}\\cdot\\mathrm e^{-\\frac{t}{R\\cdot C}}', 'R\\cdot I(t)+U_C(t)=(U_0-U_i)\\cdot\\mathrm e^{-\\frac{t}{R\\cdot C}}+U_0+(U_i-U_0)\\cdot\\mathrm e^{-\\frac{t}{R\\cdot C}}=U_0']} /><p>Der Anfangswert ist Uᵢ, der Grenzwert ist U₀. Sind beide gleich, fließt kein Strom. Ist die Anfangsspannung größer als die Quellenspannung, fließt der Strom in Gegenrichtung und die Kondensatorspannung sinkt auf den Quellwert. Das setzt eine ideale Quelle voraus, die den rückfließenden Strom aufnehmen kann.</p></Answer>
      </Exercise>
    </div></details>
  </div>;
}
