import type { ReactNode } from 'react';
import { Check, Formula } from './LabUI';
import { MathFormula, MathText } from './Math';
import RCExperiment, { RCIntegrationLab } from './RCExperiment';
import RCPractice from './RCPractice';
import './rc-self-study.css';

function T({ text }: { text: string }) { return <MathText>{text}</MathText>; }
function Solution({ title = 'Musterlösung erst nach deinem Versuch öffnen', children }: { title?: string; children: ReactNode }) {
  return <details className="rc-solution"><summary>{title}</summary><div>{children}</div></details>;
}
function Notebook({ number, children }: { number: string; children: ReactNode }) {
  return <aside className="rc-notebook"><span className="ef-eyebrow">HEFTAUFSCHRIEB {number}</span><h4>Das kommt in dein Heft</h4>{children}<p className="rc-paper-note">Schreibe mit eigenen Worten. Jede Rechnung enthält Ansatz, Einsetzen mit Einheiten, Ergebnis und Antwortsatz. Zeichnungen bekommen Titel, beschriftete Achsen und Einheiten.</p></aside>;
}
function Assignment({ number, title, children }: { number: string; title: string; children: ReactNode }) {
  return <article className="rc-assignment"><span className="ef-eyebrow">AUFGABE {number}</span><h4>{title}</h4>{children}</article>;
}
const blocks = [
  { id: 'rc-block-1', title: 'Schaltung verstehen und messen', plan: '10 min Vorwissen · 15 min Aufbau · 25 min erste Messungen · 10 min Heft', evidence: 'Schaltskizze, Vorhersagen und zwei kurze Messreihen' },
  { id: 'rc-block-2', title: 'Das Entladen experimentell entdecken', plan: '20 min Messreihe · 15 min Diagramme · 15 min Quotienten · 10 min Heft', evidence: 'Eigene Diagramme und begründete Beschreibung der Abnahme' },
  { id: 'rc-block-3', title: 'Die Entladegleichungen herleiten', plan: '15 min Strom und Steigung · 15 min Grundgleichung · 20 min Herleitung · 10 min Übung', evidence: 'Vollständige Herleitung mit Anfangsbedingung und Vorzeichen' },
  { id: 'rc-block-4', title: 'Die Ladegleichungen herleiten', plan: '15 min Messung · 15 min Spannungsbilanz · 20 min Herleitung · 10 min Vergleich', evidence: 'Herleitung des Aufladens und Vergleichstabelle' },
  { id: 'rc-block-5', title: 'Zeitkonstante, Parameter und Ladungsfläche', plan: '20 min R/C-Vergleich · 15 min Zeitkonstante · 15 min Fläche · 10 min Heft', evidence: 'Vergleichsmessungen, Halbwertszeit und Flächenrechnung' },
  { id: 'rc-block-6', title: 'Grundgleichungen sicher anwenden', plan: '10 min Formeln erklären · 40 min Abschlussaufgaben · 10 min Selbstkontrolle', evidence: 'Sechs Pflichtaufgaben und vollständiger Heftaufschrieb' },
];
export default function RCSelfStudy() {
  function printUnit() {
    document.body.classList.add('rc-print-only');
    const clean = () => document.body.classList.remove('rc-print-only');
    window.addEventListener('afterprint', clean, { once: true });
    window.print();
  }
  return <div className="rc-self-study" id="rc">
    <header className="rc-unit-header"><span className="ef-eyebrow">TEIL 07 · AUFLADEN UND ENTLADEN · SELBSTSTÄNDIG LERNEN</span><h3>Wie verändert sich die Ladung eines Kondensators mit der Zeit?</h3><p>Hier erarbeitest du die Grundgleichungen selbst: vom Schaltbild über eigene Messwerte bis zu den Exponentialfunktionen. Die Kapazität kennst du bereits. Plane <b>sechs Zeitstunden, also 360 Minuten reine Lernzeit</b>. Pausen kommen dazu. Du brauchst dein Heft, Lineal, kariertes Papier und einen wissenschaftlichen Taschenrechner.</p><p>Arbeite in der Reihenfolge 1 bis 6. Lies einen kurzen Abschnitt, bearbeite den Auftrag im Heft und öffne danach den Erwartungshorizont. Wenn dein Ergebnis abweicht, verbessere nicht nur die Zahl, sondern die Begründung. Du kannst das virtuelle Experiment jederzeit erneut aufrufen.</p><div className="ef-toolbar"><a href="#rc-experiment">Zum Experiment ↓</a><a href="#rc-formula-map">Zur Formelsammlung ↓</a><button onClick={printUnit}>Selbstlernabschnitt drucken</button></div></header>
    <nav className="rc-block-nav" aria-label="Sechs Lernblöcke zum Aufladen und Entladen">{blocks.map((block, i) => <a key={block.id} href={'#' + block.id}><span>Lernblock {i + 1} · 60 min</span>{block.title}</a>)}</nav>
    <div className="ef-table-wrap rc-time-plan"><table><caption>Dein Arbeitsplan · 6 × 60 min = 360 min · Die Zeiten sind Richtwerte.</caption><thead><tr><th>Lernblock</th><th>Dein Ablauf</th><th>Am Ende liegt im Heft</th></tr></thead><tbody>{blocks.map((block, i) => <tr key={block.id}><th>{i + 1} · {block.title}</th><td>{block.plan}</td><td>{block.evidence}</td></tr>)}</tbody></table></div>
    <aside className="rc-start"><b>Was du am Ende erklären können sollst</b><ul><li>Warum die Stromstärke beim Aufladen und beim Entladen kleiner wird.</li><li>Wie aus Spannungsbilanz, Ohm’schem Gesetz und der bekannten Kapazität die Grundgleichungen entstehen.</li><li>Wie die Funktionen für Spannung, Ladung und Strom zusammenhängen und warum der Strom beim Entladen ein anderes Vorzeichen hat.</li><li>Was Zeitkonstante und Halbwertszeit bedeuten; wie R und C den Verlauf beeinflussen.</li><li>Wie du eine Ladung aus einem Strom-Zeit-Diagramm und unbekannte Bauteilwerte aus Messdaten bestimmst.</li></ul></aside>

    <section className="rc-block" id="rc-block-1"><header><span className="ef-eyebrow">LERNBLOCK 1 · 60 MINUTEN</span><h3>Schaltung verstehen und messen</h3></header>
      <h4>1.1 · Drei bekannte Beziehungen, die wir miteinander verbinden</h4>
      <p><T text="Ein Kondensator besteht aus zwei leitenden Flächen mit einem isolierenden Zwischenraum. Beim Laden entsteht auf einer Platte Elektronenmangel, auf der anderen Elektronenüberschuss. Wir nennen die positive Ladung der oberen Platte $Q$. Die untere Platte trägt $-Q$; die gesamte Anordnung bleibt bei idealer Ladungstrennung elektrisch neutral. $Q$ ist also nicht die Summe der beiden Plattenladungen." /></p>
      <Formula tex={['Q=C\\cdot U_C', 'U_R=R\\cdot I', '\\overline I=\\frac{\\Delta Q}{\\Delta t}']} />
      <p><T text="$C$ ist die bereits bekannte Kapazität und bleibt hier konstant. $U_C$ ist die Spannung zwischen den Kondensatorplatten; $U_R$ ist die Spannung am Widerstand. Die mittlere Stromstärke $\overline I$ beschreibt, wie viel Ladung sich in einem Zeitabschnitt ändert. Stromstärke wird in Ampere gemessen, Ladung in Coulomb. Kapazität und die Einheit der Ladung verwenden beide den Buchstaben C: In Formeln ist $C$ die Kapazität, hinter einer Zahl bezeichnet $\mathrm C$ die Einheit Coulomb." /></p>
      <p>Eine Gleichspannungsquelle liefert eine feste Spannung. Das bedeutet nicht, dass sie während des gesamten Ladeprozesses eine feste Stromstärke liefert: Der Strom hängt von der Spannung am Widerstand ab.</p>
      <Assignment number="1" title="Vorwissen prüfen"><ol><li><T text="Rechne $1\,\mathrm{M\Omega}$, $10\,\mathrm{\mu F}$ und $0{,}020\,\mathrm{mA}$ in Ohm, Farad und Ampere um." /></li><li><T text="Ein Kondensator mit $C=10\,\mathrm{\mu F}$ hat $U_C=8\,\mathrm V$. Berechne seine Plattenladung. Berechne anschließend die Stromstärke durch einen $1\,\mathrm{M\Omega}$-Widerstand bei $U_R=8\,\mathrm V$." /></li><li>Erkläre den Unterschied zwischen Ladung, Spannung, Stromstärke und Kapazität ohne eine Formel vorzulesen.</li></ol><Solution><Formula tex={['1\\,\\mathrm{M\\Omega}=10^6\\,\\mathrm\\Omega', '10\\,\\mathrm{\\mu F}=10^{-5}\\,\\mathrm F', '0{,}020\\,\\mathrm{mA}=2{,}0\\cdot10^{-5}\\,\\mathrm A', 'Q=10^{-5}\\,\\mathrm F\\cdot8\\,\\mathrm V=80\\,\\mathrm{\\mu C}', 'I=\\frac{8\\,\\mathrm V}{10^6\\,\\mathrm\\Omega}=8\\,\\mathrm{\\mu A}=0{,}008\\,\\mathrm{mA}']} /><p>Ladung beschreibt den elektrischen Ladungszustand. Spannung ist die Energieänderung pro Ladung beim Transport zwischen zwei Orten. Stromstärke beschreibt den Ladungstransport pro Zeit. Kapazität beschreibt, welche Plattenladung bei einer bestimmten Spannung gespeichert wird.</p></Solution></Assignment>
      <h4>1.2 · Messgeräte anschließen und die Richtung festlegen</h4>
      <p>Ein Amperemeter muss den Strom durch den Zweig erfassen und wird deshalb in Reihe eingefügt. Ein Voltmeter vergleicht die beiden Anschlusspotentiale eines Bauteils und wird parallel angeschlossen. In der Simulation sind beide ideal: Das Amperemeter fügt keinen Widerstand hinzu; das Voltmeter zieht keinen Strom.</p>
      <p><T text="Wir legen eine einzige positive Stromrichtung fest: hinein in die obere, positiv geladene Kondensatorplatte. Beim Aufladen gilt $I>0$, beim Entladen $I<0$. Die positive Kondensatorspannung ist das Potential oben minus das Potential unten. Die Widerstandsspannung $U_R$ wird von links nach rechts gezählt. Damit passt stets $U_R=R\cdot I$; beim Entladen sind $U_R$ und $I$ negativ." /></p>
      <Assignment number="2" title="Schaltskizze und Vorhersage"><ol><li>Zeichne die Schaltung aus dem Experiment mit Quelle, Umschalter, R, C, Amperemeter und Voltmeter ins Heft. Zeichne die feste positive Stromrichtung ein.</li><li>Markiere mit zwei Farben den geschlossenen Stromweg in Stellung A und in Stellung E. Ist die Quelle beim Entladen Teil des Stromwegs?</li><li>Sage voraus, wie Spannung und Strom direkt nach Beginn und lange danach aussehen. Begründe deine Vermutung.</li><li>Prüfe mit dem offenen Schalter: Was bleibt konstant, wenn der Kondensator von beiden Stromwegen getrennt ist?</li></ol><Solution><p>In A sind Quelle, Widerstand und Kondensator verbunden. In E sind nur Widerstand und Kondensator im geschlossenen Entladekreis; die Quelle ist abgetrennt. Beim Laden startet die Kondensatorspannung bei null, der Strom ist anfangs maximal. Beim Entladen startet die Spannung bei ihrem Anfangswert, der Strom fließt in Gegenrichtung. In beiden Fällen wird der Strombetrag mit der Zeit kleiner. Bei offenem Schalter bleiben Ladung und Kondensatorspannung im idealen Modell erhalten.</p></Solution></Assignment>
      <RCExperiment />
      <Assignment number="3" title="Deine ersten Messungen"><ol><li><T text="Wähle den Grundversuch: $U_0=20\,\mathrm V$, $R=1\,\mathrm{M\Omega}$ und $C=10\,\mathrm{\mu F}$. Klicke „Aufladen vorbereiten · leer“." /></li><li>Nimm bei t = 0 s, 5 s, 10 s und 20 s jeweils einen Messwert auf. Nutze dafür die direkte Zeiteingabe. Notiere die Werte im Heft. Merke die Messreihe.</li><li>Wähle „Entladen vorbereiten · geladen“ und wiederhole die Messungen. Merke auch diese Reihe. Nutze die Auswahl der gemerkten Reihen, um die Tabellen zu vergleichen.</li><li>Lade einen zunächst leeren Kondensator nur bis 5 s. Schalte direkt auf E um. Beobachte, welche Größe sich beim Umschalten sprunghaft ändern kann und welche nicht.</li></ol><Solution><p>Die Kondensatorspannung kann im idealen RC-Modell bei endlichem Widerstand nicht springen: Eine sprunghafte Änderung würde einen unbegrenzt großen Strom erfordern. Beim direkten Wechsel von A nach E beginnt die Entladung deshalb mit der erreichten Spannung. Die Stromstärke kann wegen des geänderten Stromkreises sofort ihr Vorzeichen und ihren Betrag ändern. „Entladen vorbereiten · geladen“ stellt dagegen einen neuen Standardversuch mit 20 V Anfangsspannung her.</p></Solution></Assignment>
      <Notebook number="1"><ol><li>Überschrift: „Aufladen und Entladen eines Kondensators im RC-Kreis“.</li><li>Schaltskizze mit zwei Stromwegen und Messgeräteanschlüssen.</li><li>Definition der Stromrichtung und Bedeutung der drei bekannten Beziehungen.</li><li>Vorhersagen sowie die beiden ersten Messwerttabellen; Beobachtung beim direkten Umschalten.</li></ol></Notebook>
    </section>

    <section className="rc-block" id="rc-block-2"><header><span className="ef-eyebrow">LERNBLOCK 2 · 60 MINUTEN</span><h3>Das Entladen experimentell entdecken</h3></header>
      <p>Bevor du eine Formel verwendest, untersuchst du den zeitlichen Verlauf. Ein vollständig vorbereiteter Kondensator besitzt anfangs eine Spannung. Nach dem Umschalten treibt diese Spannung den Strom durch den Widerstand. Es fließt Ladung von den Platten über den äußeren Stromweg ab. Dadurch sinkt die Kondensatorspannung, der Antrieb des Stroms wird schwächer und auch der Strombetrag sinkt.</p>
      <p>Der Kondensator wird deshalb nicht in jeder Sekunde um denselben Ladungsbetrag entladen. Bei kleinerer Spannung fließt in derselben Zeit weniger Ladung ab. Diese Rückwirkung ist der entscheidende Unterschied zu einer linearen Abnahme.</p>
      <Assignment number="4" title="Entladeprotokoll mit selbst gezeichneten Diagrammen"><ol><li><a href="#rc-experiment">Gehe zum Experiment ↑</a> und stelle den Grundversuch ein. Bereite das Entladen vor.</li><li>Nimm Messwerte bei t = 0, 5, 10, 15, 20, 25, 30, 40 und 50 s auf. Fertige eine Hefttabelle an. Notiere auch das negative Vorzeichen von I.</li><li>Zeichne ein U-t-Diagramm und ein I-t-Diagramm. Zeitachse jeweils 0 bis 50 s; U-Achse 0 bis 20 V, I-Achse beispielsweise −0,022 bis +0,002 mA. Verwende Raster, Pfeile und einzelne Messkreuze.</li><li>Erst danach: Wähle die entsprechende Diagrammgröße auf der Website und klicke „Diagramm zeichnen“. Vergleiche deine Punkte; ziehe auf der Website keine Linien.</li><li>Beschreibe, was ein negatives I bedeutet. Verwechsle es nicht mit einem negativen Stromstärkebetrag.</li></ol><Solution><p>Die Spannungswerte für 0, 10, 20, 30, 40 und 50 s betragen ungefähr 20,00; 7,36; 2,71; 1,00; 0,37; 0,13 V. Der Strom ist negativ und nähert sich von unten der Null. Sein Betrag ist zu den gleichen Zeitpunkten ungefähr 0,0200; 0,00736; 0,00271; 0,000996; 0,000366; 0,000135 mA. Beide Beträge nehmen anfangs stark und später langsamer ab.</p></Solution></Assignment>
      <Assignment number="5" title="Linear oder exponentiell?"><ol><li><T text="Berechne für gleich große Abschnitte von 10 s jeweils die Differenz der Spannungen. Berechne zusätzlich die Quotienten $\frac{U_C(10\,\mathrm s)}{U_C(0)}$, $\frac{U_C(20\,\mathrm s)}{U_C(10\,\mathrm s)}$ und $\frac{U_C(30\,\mathrm s)}{U_C(20\,\mathrm s)}$." /></li><li>Entscheide: Ist eher die Differenz oder der Quotient konstant? Welche Art von Funktion passt dazu?</li><li>Suche mit der Zeiteingabe die Zeitpunkte, an denen 10 V, 5 V und 2,5 V erreicht werden. Beginne jeweils vom selben Entladeversuch. Notiere die Zeitabstände.</li><li>Warum ist die Entladezeit bis exakt 0 V aus den Messwerten nicht ablesbar? Welcher Rest ist nach 50 s noch vorhanden?</li></ol><Solution><p>Die Differenzen werden kleiner, während die Quotienten ungefähr 0,368 betragen. In gleichen Zeitabschnitten bleibt also derselbe Anteil des vorherigen Werts übrig: Das kennzeichnet eine exponentielle Abnahme. Die Halbierungen erfolgen ungefähr bei 6,93 s, 13,86 s und 20,79 s. Der Abstand beträgt jeweils 6,93 s. Nach 50 s sind ungefähr 0,135 V bzw. 0,674 % der Anfangsspannung übrig. Mathematisch wird null in endlicher Zeit nicht erreicht.</p></Solution></Assignment>
      <h4>2.1 · Die physikalische Erklärung hinter der Kurvenform</h4>
      <p><T text="Zu Beginn gilt $U_C=U_0$. Der Betrag des Stroms beträgt daher $\frac{U_0}{R}$. Mit abnehmender Ladung sinkt wegen $U_C=\frac{Q}{C}$ auch die Spannung. Damit sinkt zugleich $\lvert I\rvert=\frac{U_C}{R}$. Weniger Strom bedeutet eine kleinere Ladungsänderung pro Zeit. Aus „viel Ladung → viel Strom → schnelle Abnahme“ wird allmählich „wenig Ladung → wenig Strom → langsame Abnahme“." /></p>
      <p>Für konstante R und C ist die momentane Abnahmerate proportional zur momentan noch vorhandenen Ladung. Es ist also kein von außen vorgeschriebener gleich großer Ladungsabfluss. Der Kondensator beeinflusst den Strom selbst über seine Spannung.</p>
      <Notebook number="2"><ol><li>Vollständige Entladetabelle und die beiden selbst gezeichneten Diagramme.</li><li>Die Quotientenrechnung und der Satz: „In gleichen Zeitintervallen bleibt bei der Entladung derselbe Anteil des vorherigen Werts übrig.“</li><li>Die Erklärung der Rückwirkung von Ladung, Kondensatorspannung und Stromstärke.</li><li>Ein Merksatz zur praktisch fast vollständigen und mathematisch niemals exakt vollständigen Entladung.</li></ol></Notebook>
    </section>

    <section className="rc-block" id="rc-block-3"><header><span className="ef-eyebrow">LERNBLOCK 3 · 60 MINUTEN</span><h3>Die Entladegleichungen Schritt für Schritt herleiten</h3></header>
      <h4>3.1 · Stromstärke ist die Steigung des Ladungs-Zeit-Diagramms</h4>
      <p><T text="In einem Zeitintervall von $t_1$ bis $t_2$ ändert sich die positive Plattenladung um $\Delta Q=Q(t_2)-Q(t_1)$. Beim Entladen ist diese Differenz negativ. Die mittlere Stromstärke gehört zur Sekante zwischen den beiden Punkten:" /></p>
      <Formula tex="\overline I=\frac{Q(t_2)-Q(t_1)}{t_2-t_1}=\frac{\Delta Q}{\Delta t}" />
      <p>Bei einem sich verändernden Strom ist das noch nicht die Stromstärke zu einem einzelnen Zeitpunkt. Dazu denken wir uns den Zeitabschnitt immer kleiner. Die Sekantensteigung geht in die Tangentensteigung über. Das ist die Ableitung:</p>
      <Formula tex="I(t)=\frac{\mathrm dQ}{\mathrm dt}=\dot Q(t)" />
      <p><T text="Der Punkt über Q bedeutet dieselbe Ableitung nach der Zeit; er ist kein Malpunkt. Das $\mathrm d$ bezeichnet hier eine infinitesimal kleine Änderung. Du musst keine neue elektrische Gesetzmäßigkeit lernen: Die Ableitung präzisiert „Ladungsänderung pro Zeit“. Bei steigender positiver Plattenladung ist I positiv, bei fallender negativ." /></p>
      <Assignment number="6" title="Mittlerer und momentaner Strom"><p><T text="Im Grundversuch sinkt die Ladung während der ersten 5 s von 200 µC auf ungefähr 121,31 µC. Berechne den mittleren Strom in mA. Vergleiche ihn mit dem Anfangsstrom und dem Strom bei 5 s. Erkläre, warum der Mittelwert zwischen beiden liegt." /></p><Solution><Formula tex="\overline I=\frac{(121{,}31-200)\,\mathrm{\mu C}}{5\,\mathrm s}\approx-15{,}74\,\mathrm{\mu A}=-0{,}01574\,\mathrm{mA}" /><p>Der Anfangsstrom ist −0,020 mA, der Strom bei 5 s ungefähr −0,01213 mA. Der Strom wird kontinuierlich weniger negativ; sein Mittelwert im Intervall liegt deshalb zwischen den beiden Randwerten.</p></Solution></Assignment>
      <h4>3.2 · Die Grundgleichung entsteht aus dem Stromkreis</h4>
      <div className="rc-derivation"><ol><li><b>Spannungsbilanz im Entladekreis.</b><p>Die Quelle ist nicht angeschlossen. Mit unseren festen Richtungen gilt:</p><Formula tex="0=U_R(t)+U_C(t)" /></li><li><b>Ohm’sches Gesetz und Kondensatorbeziehung einsetzen.</b><Formula tex="0=R\cdot I(t)+\frac{Q(t)}{C}" /><p>Ein positives Q führt zu einer positiven Kondensatorspannung und einem negativen I. Dieses Minuszeichen entsteht aus der Spannungsbilanz.</p></li><li><b>Nach I auflösen.</b><Formula tex="I(t)=-\frac{Q(t)}{R\cdot C}" /></li><li><b>Die Stromstärke durch die zeitliche Ladungsänderung ersetzen.</b><Formula tex="\frac{\mathrm dQ}{\mathrm dt}=-\frac{1}{R\cdot C}\cdot Q(t)" /></li></ol></div>
      <p>Dies ist eine <b>Differenzialgleichung</b>: Sie verbindet die gesuchte Funktion Q mit ihrer Ableitung. In Worten: „Die Änderungsrate ist negativ und proportional zur noch vorhandenen Ladung.“ Eine gewöhnliche Gleichung sucht oft eine Zahl; hier suchen wir einen ganzen zeitlichen Verlauf.</p>
      <h4>3.3 · Warum gerade eine Exponentialfunktion?</h4>
      <p><T text="Aus der Mathematik kennst du: Die Ableitung von $\mathrm e^{a\cdot t}$ ist $a\cdot\mathrm e^{a\cdot t}$. Die Ableitung ist also proportional zur Funktion selbst. Genau das verlangt unsere Grundgleichung. Der Faktor muss $a=-\frac{1}{R\cdot C}$ sein." /></p>
      <Formula tex="Q(t)=Q_0\cdot\mathrm e^{-\frac{t}{R\cdot C}}" />
      <p><T text="Die Konstante $Q_0$ wird durch den Anfangszustand festgelegt: Bei $t=0$ ist $\mathrm e^0=1$, also $Q(0)=Q_0=C\cdot U_0$. Die Zahl $\mathrm e\approx2{,}71828$ ist die Basis der natürlichen Exponentialfunktion. Der Exponent muss ohne Einheit sein; t und R · C besitzen beide die Einheit Sekunde." /></p>
      <div className="rc-derivation"><h4>Die Lösung überprüfen · Kettenregel sichtbar machen</h4><Formula tex={['\\frac{\\mathrm d}{\\mathrm dt}\\left(-\\frac{t}{R\\cdot C}\\right)=-\\frac{1}{R\\cdot C}', '\\frac{\\mathrm dQ}{\\mathrm dt}=Q_0\\cdot\\mathrm e^{-\\frac{t}{R\\cdot C}}\\cdot\\left(-\\frac{1}{R\\cdot C}\\right)', '\\frac{\\mathrm dQ}{\\mathrm dt}=-\\frac{1}{R\\cdot C}\\cdot Q(t)']} /><p>Die erste Zeile ist die Ableitung des Exponenten. Sie liefert den zusätzlichen Faktor in der zweiten Zeile. Die dritte Zeile ist genau die Grundgleichung. Zusätzlich stimmt der Anfangswert. Damit ist der vorgeschlagene Verlauf für unseren Anfangszustand die passende Lösung.</p></div>
      <Solution title="Mathematischer Zusatz: Lösung durch Trennung der Variablen"><p>Dieser Weg ist eine Ergänzung. Für das Verständnis der Grundgleichung genügt die Überprüfung mit der Ableitung.</p><Formula tex={['\\frac{\\mathrm dQ}{Q}=-\\frac{\\mathrm dt}{R\\cdot C}', '\\int_{Q_0}^{Q(t)}\\frac{\\mathrm d\\widetilde Q}{\\widetilde Q}=-\\frac{1}{R\\cdot C}\\cdot\\int_0^t\\mathrm ds', '\\ln\\left(\\frac{Q(t)}{Q_0}\\right)=-\\frac{t}{R\\cdot C}', '\\frac{Q(t)}{Q_0}=\\mathrm e^{-\\frac{t}{R\\cdot C}}']} /><p>Man trennt die Q-Änderung von der Zeitänderung und summiert beide über ihre Intervalle. Der natürliche Logarithmus ist die Umkehrfunktion zur Exponentialfunktion. Der Quotient im Logarithmus ist einheitenfrei. Dieser Schritt setzt eine positive Anfangsladung voraus.</p></Solution>
      <h4>3.4 · Aus Q(t) folgen Spannung und Stromstärke</h4>
      <p>Die Spannung erhältst du durch Division der Ladung durch die konstante Kapazität. Den Strom erhältst du durch Ableiten oder mit dem Ohm’schen Gesetz und der Spannungsbilanz.</p>
      <Formula tex={['U_C(t)=\\frac{Q(t)}{C}=U_0\\cdot\\mathrm e^{-\\frac{t}{R\\cdot C}}', 'I(t)=\\frac{\\mathrm dQ}{\\mathrm dt}=-\\frac{U_0}{R}\\cdot\\mathrm e^{-\\frac{t}{R\\cdot C}}', 'U_R(t)=-U_C(t)']} />
      <aside className="rc-notation"><b>Warum steht in manchen Schulbüchern kein Minus vor dem Entladestrom?</b><p><T text="Einige Bücher zählen in Entladerichtung positiv oder verwenden nur den Betrag $I_E=\lvert I\rvert$. Dann steht $I_E(t)=\frac{U_0}{R}\cdot\mathrm e^{-\frac{t}{R\cdot C}}$ und $I_E=-\frac{\mathrm dQ}{\mathrm dt}$. Wir behalten dagegen den einen Richtungspfeil für beide Vorgänge bei: $I=\frac{\mathrm dQ}{\mathrm dt}$, also ist der Entladestrom negativ. Beide Beschreibungen meinen denselben Vorgang. Mische die Konventionen innerhalb einer Rechnung nicht." /></p></aside>
      <Assignment number="7" title="Jede Zeile selbst begründen"><ol><li>Leite die vier Zeilen der Grundgleichung im Heft selbst her, ohne oben nachzusehen. Schreibe zu jedem Gleichheitszeichen, welches Gesetz du benutzt.</li><li>Leite die Exponentialfunktion mit der Kettenregel ab. Markiere den Faktor aus dem Exponenten.</li><li>Prüfe die Spannung und den Strom bei t = 0 und für sehr große Zeiten.</li><li>Prüfe deinen vorhergesagten Wert bei t = 15 s mit dem Experiment.</li></ol><Solution><p><T text="Die Gesetze sind der Reihe nach Spannungsbilanz, Ohm’sches Gesetz plus $U_C=\frac{Q}{C}$, algebraische Umformung und Definition der Stromstärke. Anfangs sind $Q=Q_0$, $U_C=U_0$, $I=-\frac{U_0}{R}$. Für sehr große Zeiten nähern sich alle drei Größen null. Bei 15 s im Grundversuch sind $U_C\approx4{,}46\,\mathrm V$ und $I\approx-0{,}00446\,\mathrm{mA}$." /></p></Solution></Assignment>
      <Check question="Grundversuch: Welche Kondensatorspannung liegt nach 15 s Entladung an? Gib das Ergebnis in V ein." answer={20 * Math.exp(-1.5)} unit="V" hint="Setze t = 15 s und R · C = 10 s in die Entladegleichung ein." solution="$U_C=20\,\mathrm V\cdot\mathrm e^{-\frac{15\,\mathrm s}{10\,\mathrm s}}\approx4{,}46\,\mathrm V$." />
      <Notebook number="3"><ol><li>Definition von mittlerer und momentaner Stromstärke mit einer Erklärung zur Steigung.</li><li>Alle vier Schritte der Entlade-Grundgleichung, jeweils mit dem verwendeten Gesetz.</li><li>Die Exponentiallösung samt Ableitung und Anfangswertprüfung.</li><li>Die Gleichungen für Q, U und I; Hinweis zum negativen Vorzeichen und zum positiven Betrag.</li></ol></Notebook>
    </section>

    <section className="rc-block" id="rc-block-4"><header><span className="ef-eyebrow">LERNBLOCK 4 · 60 MINUTEN</span><h3>Das Aufladen verstehen und herleiten</h3></header>
      <h4>4.1 · Erst die Messung, dann die Erklärung</h4>
      <Assignment number="8" title="Aufladeprotokoll"><ol><li><a href="#rc-experiment">Gehe zum Experiment ↑</a>. Stelle wieder 20 V, 1 MΩ und 10 µF ein und wähle „Aufladen vorbereiten · leer“.</li><li>Nimm Messwerte bei denselben Zeiten wie in Aufgabe 4 auf. Zeichne das U-t- und das I-t-Diagramm zunächst selbst.</li><li>Öffne erst danach die Diagramme. Beschreibe: Welche Größe steigt, welche fällt? Ist die Spannung selbst eine fallende Exponentialfunktion?</li><li><T text="Berechne für 0, 10 und 20 s jeweils die noch fehlende Spannung $U_0-U_C(t)$. Vergleiche sie mit der Entladespannung zu denselben Zeiten." /></li></ol><Solution><p>Die Kondensatorspannung steigt von null aus und nähert sich 20 V. Der positive Strom fällt von 0,020 mA gegen null. Bei 10 s sind ungefähr 12,64 V erreicht; es fehlen 7,36 V. Bei 20 s sind ungefähr 17,29 V erreicht; es fehlen 2,71 V. Die fehlende Spannung fällt exponentiell und besitzt bei diesen Anfangsbedingungen genau den Verlauf der Entladespannung.</p></Solution></Assignment>
      <h4>4.2 · Welche Spannung treibt den Ladestrom?</h4>
      <p><T text="Zu Beginn ist der Kondensator leer, also $U_C=0$. Die gesamte Quellenspannung liegt am Widerstand und der Strom ist maximal. Durch den Ladungstransport steigt $U_C$. Die beiden Bauteilspannungen müssen zusammen weiterhin $U_0$ ergeben. Deshalb bleibt am Widerstand immer weniger Spannung übrig und der Strom wird kleiner." /></p>
      <Formula tex={['U_0=U_R(t)+U_C(t)', 'U_R(t)=U_0-U_C(t)', 'I(t)=\\frac{U_0-U_C(t)}{R}']} />
      <p>Ein Kondensator beendet den Ladeprozess nicht, weil „kein Platz für Elektronen“ mehr vorhanden wäre. Der Strom nähert sich null, weil die Kondensatorspannung fast genauso groß wie die Quellenspannung geworden ist. Dann ist die antreibende Spannung am Widerstand fast null. Der isolierende Zwischenraum bleibt auch während des Ladens undurchlässig für einen Leitungselektronenstrom.</p>
      <Assignment number="9" title="Spannungsbilanz erklären"><p><T text="Der Kondensator hat im Grundversuch gerade 12 V. Bestimme $U_R$ und I. Erkläre, warum du für den Strom nicht einfach $\frac{20\,\mathrm V}{R}$ einsetzen darfst. Welcher Fehler entsteht, wenn du stattdessen $\frac{U_C}{R}$ benutzt?" /></p><Solution><Formula tex={['U_R=20\\,\\mathrm V-12\\,\\mathrm V=8\\,\\mathrm V', 'I=\\frac{8\\,\\mathrm V}{1\\,\\mathrm{M\\Omega}}=0{,}008\\,\\mathrm{mA}']} /><p>Am Widerstand liegt nur die Differenz der beiden Spannungen. Mit 20 V würde man den Anfangsstrom anstelle des momentanen Stroms berechnen. Mit der Kondensatorspannung allein würde man 0,012 mA erhalten und die Lade-Schaltung mit dem Entladen verwechseln.</p></Solution></Assignment>
      <h4>4.3 · Die Grundgleichung des Aufladens</h4>
      <div className="rc-derivation"><ol><li><b>Die Quellenspannung auf beide Bauteile verteilen.</b><Formula tex="U_0=R\cdot I(t)+\frac{Q(t)}{C}" /></li><li><b>Die Stromstärke als Ableitung einsetzen.</b><Formula tex="U_0=R\cdot\frac{\mathrm dQ}{\mathrm dt}+\frac{Q(t)}{C}" /></li><li><b>Nach der zeitlichen Änderung auflösen.</b><Formula tex="\frac{\mathrm dQ}{\mathrm dt}=\frac{U_0}{R}-\frac{Q(t)}{R\cdot C}" /></li><li><b>Die erreichbare Ladung einführen.</b><p><T text="Bei sehr langen Ladezeiten nähert sich die Kondensatorspannung $U_0$; damit ist $Q_{\max}=C\cdot U_0$." /></p><Formula tex="\frac{\mathrm dQ}{\mathrm dt}=\frac{Q_{\max}-Q(t)}{R\cdot C}" /></li></ol></div>
      <p>Die Ladegeschwindigkeit ist proportional zur <b>noch fehlenden</b> Ladung. Darin liegt der Unterschied zur Entladung: Dort ist die Abnahme proportional zur <b>noch vorhandenen</b> Ladung.</p>
      <h4>4.4 · Die fehlende Ladung nimmt exponentiell ab</h4>
      <p><T text="Wir definieren $D(t)=Q_{\max}-Q(t)$ als den noch fehlenden Ladungsbetrag. Weil $Q_{\max}$ konstant ist, gilt $\frac{\mathrm dD}{\mathrm dt}=-\frac{\mathrm dQ}{\mathrm dt}$. Die Grundgleichung wird dadurch zu:" /></p>
      <Formula tex="\frac{\mathrm dD}{\mathrm dt}=-\frac{D(t)}{R\cdot C}" />
      <p><T text="Das ist dieselbe Form wie beim Entladen. Für einen anfangs leeren Kondensator fehlt zunächst die ganze erreichbare Ladung: $D(0)=Q_{\max}$. Also gilt:" /></p>
      <Formula tex={['D(t)=Q_{\\max}\\cdot\\mathrm e^{-\\frac{t}{R\\cdot C}}', 'Q(t)=Q_{\\max}-D(t)=C\\cdot U_0\\cdot\\left(1-\\mathrm e^{-\\frac{t}{R\\cdot C}}\\right)']} />
      <p>Die Klammer ist entscheidend: Sie beschreibt den bereits erreichten Anteil und steigt von null gegen eins. Der Exponentialterm allein wäre der noch fehlende Anteil.</p>
      <h4>4.5 · Spannung und Strom daraus ableiten</h4>
      <Formula tex={['U_C(t)=\\frac{Q(t)}{C}=U_0\\cdot\\left(1-\\mathrm e^{-\\frac{t}{R\\cdot C}}\\right)', 'I(t)=\\frac{\\mathrm dQ}{\\mathrm dt}=C\\cdot U_0\\cdot\\frac{1}{R\\cdot C}\\cdot\\mathrm e^{-\\frac{t}{R\\cdot C}}', 'I(t)=\\frac{U_0}{R}\\cdot\\mathrm e^{-\\frac{t}{R\\cdot C}}', 'U_R(t)=U_0\\cdot\\mathrm e^{-\\frac{t}{R\\cdot C}}']} />
      <p><T text="Beim Ableiten heben sich die beiden Minuszeichen auf: eines vor dem Exponentialterm in der Klammer, eines aus der Ableitung des Exponenten. Anschließend kürzt sich C. Der Ladestrom ist deshalb positiv. Der Anfangsstrom $\frac{U_0}{R}$ hängt bei leerem Kondensator nicht von C ab." /></p>
      <Assignment number="10" title="Die Ladefunktion selbst überprüfen"><ol><li>Leite Q(t) selbst ab und zeige beide Minuszeichen. Prüfe, dass die Ladestromformel entsteht.</li><li><T text="Setze Q(t) und I(t) in $U_0=R\cdot I+\frac{Q}{C}$ ein. Zeige, dass die Exponentialterme sich wegheben." /></li><li>Prüfe die Anfangswerte bei t = 0 und die Grenzwerte für sehr lange Zeiten.</li><li>Begründe, weshalb Ladungs- und Spannungsdiagramm bei konstanter Kapazität dieselbe Form besitzen.</li></ol><Solution><Formula tex={['R\\cdot I(t)+\\frac{Q(t)}{C}=U_0\\cdot\\mathrm e^{-\\frac{t}{R\\cdot C}}+U_0\\cdot\\left(1-\\mathrm e^{-\\frac{t}{R\\cdot C}}\\right)=U_0', 'Q(0)=0,\\qquad U_C(0)=0,\\qquad I(0)=\\frac{U_0}{R}', 'Q(t)\\longrightarrow C\\cdot U_0,\\qquad U_C(t)\\longrightarrow U_0,\\qquad I(t)\\longrightarrow0']} /><p>Q und U unterscheiden sich nur durch den konstanten Faktor C. Ein vertikaler Maßstabswechsel verändert ihre zeitliche Kurvenform nicht.</p></Solution></Assignment>
      <Check question="Grundversuch: Welche Kondensatorspannung wird nach 20 s Aufladen erreicht?" answer={20 * (1 - Math.exp(-2))} unit="V" hint="Verwende die Ladefunktion mit 1 minus Exponentialterm." solution="$U_C=20\,\mathrm V\cdot\left(1-\mathrm e^{-\frac{20\,\mathrm s}{10\,\mathrm s}}\right)\approx17{,}29\,\mathrm V$." />
      <Notebook number="4"><ol><li>Aufladetabelle und eigene Diagramme; drei Vergleiche mit der Entladung.</li><li>Spannungsbilanz, vier Schritte der Lade-Grundgleichung und Herleitung über die fehlende Ladung D.</li><li>Ladefunktionen für Q, U und I mit einer Ableitung sowie Anfangs- und Grenzwerten.</li><li>Merksatz: „Beim Laden fällt die fehlende Spannung exponentiell; die Kondensatorspannung steigt um den ergänzenden Anteil.“</li></ol></Notebook>
    </section>

    <section className="rc-block" id="rc-block-5"><header><span className="ef-eyebrow">LERNBLOCK 5 · 60 MINUTEN</span><h3>Was bestimmt die Dauer? Und wie viel Ladung fließt?</h3></header>
      <h4>5.1 · Widerstand und Kapazität getrennt verändern</h4>
      <Assignment number="11" title="Ein fairer Parametervergleich"><ol><li><T text="Wähle die Vergleichsvoreinstellung: $U_0=10\,\mathrm V$, $R=10\,\mathrm{k\Omega}$, $C=4\,\mathrm{\mu F}$. Bereite Aufladen vor. Notiere den Anfangsstrom und miss bei 0; 0,02; 0,04; 0,08 und 0,12 s. Merke die Reihe." /></li><li><T text="Verändere nur C auf $8\,\mathrm{\mu F}$. Wiederhole genau dieselben Messzeiten und merke die Reihe." /></li><li><T text="Stelle C wieder auf $4\,\mathrm{\mu F}$ und verändere nur R auf $20\,\mathrm{k\Omega}$. Wiederhole und merke die dritte Reihe." /></li><li>Vergleiche zuerst die Kondensatorspannungen, dann die Anfangsströme. Zeichne die drei U-t-Messreihen mit derselben Zeitachse ins Heft. Beantworte: Welche beiden Reihen besitzen denselben Spannungsverlauf? Warum unterscheiden sich trotzdem ihre Ströme?</li></ol><Solution><p>Die erste Reihe hat die Zeitkonstante 0,04 s und den Anfangsstrom 1 mA. Die zweite hat 0,08 s bei ebenfalls 1 mA. Die dritte hat 0,08 s bei 0,5 mA. Die Reihen 2 und 3 besitzen dasselbe R·C und deshalb denselben Spannungsverlauf bei gleichem U₀. Ihr Anfangsstrom hängt jedoch nur von R und U₀ ab. Durch Verdoppeln von C muss doppelt so viel Ladung gespeichert werden; durch Verdoppeln von R wird der Strom bei gleicher Widerstandsspannung halbiert.</p></Solution></Assignment>
      <h4>5.2 · Die Zeitkonstante τ</h4>
      <p><T text="In jeder Exponentialfunktion steht die Kombination $R\cdot C$. Wir nennen sie Zeitkonstante $\tau$. Sie ist ein Maß für die Geschwindigkeit des Vorgangs und besitzt die Einheit Sekunde:" /></p>
      <Formula tex={['\\tau=R\\cdot C', '[\\tau]=\\mathrm\\Omega\\cdot\\mathrm F=\\frac{\\mathrm V}{\\mathrm A}\\cdot\\frac{\\mathrm A\\cdot\\mathrm s}{\\mathrm V}=\\mathrm s']} />
      <p><T text="Nach genau einer Zeitkonstante ist $\frac{t}{\tau}=1$ und der Exponentialterm gleich $\mathrm e^{-1}\approx0{,}3679$. Beim Entladen bleiben daher ungefähr 36,8 % der Anfangsspannung und Anfangsladung. Beim Aufladen sind ungefähr 63,2 % der Endspannung und Endladung erreicht; 36,8 % fehlen noch. Der Strombetrag ist bei beiden Standardversuchen auf 36,8 % des Anfangswerts gefallen." /></p>
      <Solution title="Auswertungstabelle zum Vergleichen · erst selbst berechnen"><div className="ef-table-wrap"><table><thead><tr><th>Zeit</th><th>Entladen: verbleibender Anteil</th><th>Aufladen: erreichter Anteil</th><th>Strombetrag: Anteil vom Anfang</th></tr></thead><tbody>{[[0, 100, 0], [1, 36.8, 63.2], [2, 13.5, 86.5], [3, 5, 95], [4, 1.8, 98.2], [5, .674, 99.326]].map(([t, left, reached]) => <tr key={t}><td>{t} τ</td><td>{left.toLocaleString('de-DE')} %</td><td>{reached.toLocaleString('de-DE')} %</td><td>{left.toLocaleString('de-DE')} %</td></tr>)}</tbody></table></div><p>Nach fünf Zeitkonstanten fehlen weniger als 0,7 %. „Voll geladen“ oder „entladen“ bezeichnet in der Praxis eine solche Näherung, nicht einen mathematisch exakt erreichten Grenzwert.</p></Solution>
      <Assignment number="12" title="Zeitkonstante aus einer Messreihe bestimmen"><ol><li>Bestimme τ aus dem Entladediagramm des Grundversuchs: Suche den Zeitpunkt für 36,8 % der Anfangsspannung. Prüfe die Bestimmung im Ladediagramm bei 63,2 %.</li><li>Berechne τ aus R und C und vergleiche. Begründe, warum 7 s Halbierung und 10 s Zeitkonstante nicht dasselbe sind.</li><li><T text="Berechne für den Grundversuch $Q(\tau)$, $U_C(\tau)$ und I(τ) beim Laden und beim Entladen." /></li></ol><Solution><p>τ = 10 s. Beim Entladen sind Q ≈ 73,58 µC, U ≈ 7,36 V und I ≈ −0,00736 mA. Beim Aufladen sind Q ≈ 126,42 µC, U ≈ 12,64 V und I ≈ +0,00736 mA. Eine Zeitkonstante beschreibt den Faktor 1/e, eine Halbwertszeit den Faktor 1/2.</p></Solution></Assignment>
      <h4>5.3 · Die Halbwertszeit herleiten</h4>
      <p><T text="Die Halbwertszeit $T_{\frac12}$ ist die Dauer, in der ein exponentiell fallender Wert halbiert wird. Setze in die Entladefunktion die Hälfte des Anfangswerts ein, dividiere durch $U_0$ und wende den natürlichen Logarithmus an:" /></p>
      <Formula tex={['\\frac{U_0}{2}=U_0\\cdot\\mathrm e^{-\\frac{T_{\\frac12}}{R\\cdot C}}', '\\frac12=\\mathrm e^{-\\frac{T_{\\frac12}}{R\\cdot C}}', '\\ln\\left(\\frac12\\right)=-\\frac{T_{\\frac12}}{R\\cdot C}', 'T_{\\frac12}=R\\cdot C\\cdot\\ln(2)\\approx0{,}693\\cdot R\\cdot C']} />
      <p><T text="Dabei nutzen wir $\ln(\mathrm e^x)=x$ und $\ln(\frac12)=-\ln(2)$. Die Halbwertszeit hängt weder vom Anfangswert noch von der bereits verstrichenen Zeit ab. Beim Aufladen halbiert sich in jeder Halbwertszeit die noch fehlende Spannung. Die erreichten Anteile sind nach einer, zwei und drei Halbwertszeiten 50 %, 75 % und 87,5 %; sie verdoppeln sich nicht." /></p>
      <p>Eine Buch-Messreihe mit etwa 7 s zwischen Halbierungen passt zum Grundversuch. Das ist ein gerundeter Wert. Wir rechnen mit 6,93 s und erzeugen durchgehend konsistente Modellwerte; gerundete Tabellen können kleine Abweichungen zeigen.</p>
      <Check question="R = 100 kΩ, C = 47 µF: Berechne die Halbwertszeit in Sekunden." answer={4.7 * Math.log(2)} unit="s" hint="Erst τ = R · C berechnen, dann mit ln(2) multiplizieren." solution="$\tau=10^5\,\mathrm\Omega\cdot47\cdot10^{-6}\,\mathrm F=4{,}7\,\mathrm s$ und $T_{\frac12}=4{,}7\,\mathrm s\cdot\ln(2)\approx3{,}26\,\mathrm s$." />
      <h4>5.4 · Ladung ist die Fläche unter dem Strom-Zeit-Verlauf</h4>
      <p><T text="Bei konstantem Strom ist $\Delta Q=I\cdot\Delta t$: Im I-t-Diagramm ist das die Fläche eines Rechtecks. Bei veränderlichem Strom zerlegen wir die Zeit in kurze Abschnitte. Je kürzer diese Abschnitte sind, desto besser lässt sich der Strom dort als ungefähr konstant behandeln." /></p>
      <Formula tex={['\\Delta Q\\approx\\sum_k I_k\\cdot\\Delta t', '\\Delta Q\\approx\\sum_k\\frac{I_k+I_{k+1}}{2}\\cdot\\Delta t', 'Q(T)-Q(0)=\\int_0^T I(t)\\,\\mathrm dt']} />
      <p><T text="Die erste Zeile addiert Rechtecke, die zweite Trapeze. Das Summenzeichen bedeutet „addiere die Beiträge aller Zeitabschnitte“. Das Integral in der dritten Zeile ist die exakte Summe im Grenzfall beliebig kleiner Abschnitte. Seine Einheit ist $\mathrm A\cdot\mathrm s=\mathrm C$; entsprechend gilt $\mathrm{mA}\cdot\mathrm s=\mathrm{mC}$ und $\mathrm{mA}\cdot\mathrm{ms}=\mathrm{\mu C}$." /></p>
      <p><T text="Mit unserem vorzeichenbehafteten I ist die Fläche beim Entladen negativ und beschreibt die negative Änderung der Plattenladung. Mit $\lvert I\rvert$ ist sie positiv und beschreibt die abgeflossene Ladung $Q_{\mathrm{ab}}$. Die Restladung bekommst du erst durch Subtraktion:" /></p>
      <Formula tex={['Q_{\\mathrm{ab}}(T)=\\int_0^T\\lvert I(t)\\rvert\\,\\mathrm dt=Q_0-Q(T)', 'Q(T)=Q_0-Q_{\\mathrm{ab}}(T)']} />
      <Assignment number="13" title="Flächen aus Messwerten rechnen"><ol><li>Nutze die Werkstatt unten mit vier Zeitabschnitten. Berechne aus der Tabelle zunächst die linke und die rechte Rechtecksumme.</li><li>Berechne die Trapezsumme. Achte darauf, dass der Strom in mA und die Zeit in s zu mC führen.</li><li>Blende den Flächenvergleich ein und prüfe. Verdopple die Anzahl der Abschnitte. Erkläre, warum die Näherungen sich annähern.</li><li>Bestimme aus der abgeflossenen Ladung die Restladung nach 20 s und vergleiche mit Q = C · U aus dem Experiment.</li></ol></Assignment>
      <RCIntegrationLab />
      <Solution title="Erwartungshorizont zu Aufgabe 13"><p>Bei vier Abschnitten von je 5 s liefern die linken Rechtecke ungefähr 219,75 µC, die rechten ungefähr 133,29 µC, die Trapeze ungefähr 176,52 µC. Die grobe linke Summe überschätzt sogar die anfangs vorhandenen 200 µC: Das zeigt, dass sie hier als Modell der tatsächlichen Ladung zu ungenau ist. Exakt fließen bis 20 s ungefähr 172,93 µC ab; es bleiben 27,07 µC. Mit mehr Abschnitten nähern sich die Werte dem exakten Ergebnis.</p></Solution>
      <Notebook number="5"><ol><li>Drei Vergleichsreihen mit Erklärung, was beim Verdoppeln von R bzw. C gleich bleibt und was sich ändert.</li><li>Definition, Einheit und Bedeutung der Zeitkonstante; die Halbwertszeit mit vollständiger Herleitung.</li><li>Die drei Flächenbeziehungen und eine Rechnung mit vier Trapezen.</li><li>Merksatz: „Die Fläche des Entladestrombetrags bis T ist die abgeflossene Ladung. Die Restladung ist Anfangsladung minus Fläche.“</li></ol></Notebook>
    </section>

    <section className="rc-block" id="rc-block-6"><header><span className="ef-eyebrow">LERNBLOCK 6 · 60 MINUTEN</span><h3>Ordnen, üben und den Heftaufschrieb abschließen</h3></header>
      <h4 id="rc-formula-map">6.1 · Deine Formelsammlung mit Bedeutung jeder Größe</h4>
      <p>Sprich zu jeder Zeile einen ganzen Satz: Was beschreibt sie, welche Anfangsbedingung benötigt sie und warum ist sie richtig? Erkläre dabei die Faktoren und die Klammer. Nutze die Tabelle als Kontrolle deines Hefts.</p>
      <div className="ef-table-wrap rc-formula-map"><table><caption>Standardfälle · R und C konstant · Laden von U_C(0) = 0 · Entladen von U_C(0) = U₀ · eine feste Stromrichtung</caption><thead><tr><th>Größe</th><th>Aufladen</th><th>Entladen</th></tr></thead><tbody>
        <tr><th>Grundgleichung</th><td><MathFormula tex="\frac{\mathrm dQ}{\mathrm dt}=\frac{U_0}{R}-\frac{Q}{R\cdot C}" /></td><td><MathFormula tex="\frac{\mathrm dQ}{\mathrm dt}=-\frac{Q}{R\cdot C}" /></td></tr>
        <tr><th>Plattenladung</th><td><MathFormula tex="Q(t)=C\cdot U_0\cdot\left(1-\mathrm e^{-\frac{t}{R\cdot C}}\right)" /></td><td><MathFormula tex="Q(t)=C\cdot U_0\cdot\mathrm e^{-\frac{t}{R\cdot C}}" /></td></tr>
        <tr><th>Kondensatorspannung</th><td><MathFormula tex="U_C(t)=U_0\cdot\left(1-\mathrm e^{-\frac{t}{R\cdot C}}\right)" /></td><td><MathFormula tex="U_C(t)=U_0\cdot\mathrm e^{-\frac{t}{R\cdot C}}" /></td></tr>
        <tr><th>Stromstärke mit Vorzeichen</th><td><MathFormula tex="I(t)=\frac{U_0}{R}\cdot\mathrm e^{-\frac{t}{R\cdot C}}" /></td><td><MathFormula tex="I(t)=-\frac{U_0}{R}\cdot\mathrm e^{-\frac{t}{R\cdot C}}" /></td></tr>
        <tr><th>Spannung am Widerstand</th><td><MathFormula tex="U_R(t)=U_0\cdot\mathrm e^{-\frac{t}{R\cdot C}}" /></td><td><MathFormula tex="U_R(t)=-U_0\cdot\mathrm e^{-\frac{t}{R\cdot C}}" /></td></tr>
        <tr><th>Zeitkonstante</th><td colSpan={2}><MathFormula tex="\tau=R\cdot C" /></td></tr><tr><th>Halbwertszeit</th><td colSpan={2}><MathFormula tex="T_{\frac12}=\tau\cdot\ln(2)\approx0{,}693\cdot\tau" /></td></tr>
      </tbody></table></div>
      <dl className="rc-symbols">{[
        ['t', 'Zeit seit Beginn der gerade betrachteten Lade- oder Entladephase; Einheit s. Nach einem Umschalten beginnt die Zeit der neuen Phase bei null.'],
        ['\\Delta t', 'Dauer eines Zeitintervalls; Einheit s.'],
        ['R', 'Ohm’scher Widerstand des Stromwegs; Einheit Ω.'],
        ['C', 'Konstante Kapazität des Kondensators; Einheit F. Das ist eine Bauteileigenschaft, keine Ladung.'],
        ['U_0', 'Konstante Quellenspannung beim Laden; im Standard-Entladeversuch zugleich die vorbereitete Anfangsspannung; Einheit V.'],
        ['U_i', 'Tatsächliche Kondensatorspannung am Anfang einer beliebigen neuen Phase; Einheit V. Sie kann nach einem vorzeitigen Umschalten von U₀ abweichen.'],
        ['U_C(t)', 'Spannung oben minus unten am Kondensator zum Zeitpunkt t; Einheit V. Der Index C benennt das Bauteil.'],
        ['U_R(t)', 'Spannung am Widerstand, von links nach rechts gezählt; Einheit V. Sie hat beim Entladen mit unserer Konvention ein negatives Vorzeichen.'],
        ['Q(t)', 'Positive Ladung der oberen Kondensatorplatte zum Zeitpunkt t; Einheit Coulomb. Die untere Platte trägt −Q.'],
        ['Q_0', 'Anfangsladung bei der Entladung: C · U₀; Einheit Coulomb.'],
        ['Q_{\\max}', 'Grenzwert der positiven Plattenladung beim Standardladen: C · U₀; Einheit Coulomb.'],
        ['D(t)', 'Noch fehlende Ladung beim Aufladen: Qmax minus Q(t); Einheit Coulomb. Hilfsgröße für die Herleitung.'],
        ['\\Delta Q', 'Vorzeichenbehaftete Änderung Q(t₂) − Q(t₁); Einheit Coulomb.'],
        ['Q_{\\mathrm{ab}}(T)', 'Positiver Betrag der bis zur Zeit T abgeflossenen Ladung beim Entladen; Einheit Coulomb.'],
        ['I(t)', 'Momentane technische Stromstärke in der festgelegten Richtung; Einheit A. Positiv beim Laden, negativ beim Entladen.'],
        ['\\overline I', 'Mittlere Stromstärke in einem Zeitintervall; Einheit A. Sie ist nicht automatisch der Wert am Intervallbeginn.'],
        ['I_0', 'Positiver Anfangsstrombetrag U₀/R in den Standardfällen; Einheit A. Beim Laden gilt I(0) = I₀, beim Entladen I(0) = −I₀.'],
        ['I_E=\\lvert I\\rvert', 'Positiver Betrag des Entladestroms, wie ihn einige Bücher verwenden; Einheit A.'],
        ['\\tau', 'Zeitkonstante R · C; Einheit s. Nach τ bleibt ein Anteil 1/e übrig bzw. es fehlt ein Anteil 1/e.'],
        ['T_{\\frac12}', 'Halbwertszeit τ · ln(2); Einheit s. In dieser Zeit halbiert sich der exponentiell fallende Anteil.'],
        ['\\mathrm e', 'Euler’sche Zahl, ungefähr 2,71828; keine Einheit. Basis der natürlichen Exponentialfunktion.'],
        ['\\ln(x)', 'Natürlicher Logarithmus, Umkehrfunktion von e hoch x. Das Argument x muss einheitenfrei und positiv sein.'],
        ['E_{\\mathrm{Kond}}', 'Im elektrischen Feld des Kondensators gespeicherte Energie; Einheit J.'],
        ['\\Delta E_{\\mathrm{th}}', 'Zunahme der thermischen Energie des Widerstands beim Entladen; Einheit J.'],
      ].map(([symbol, description]) => <div key={symbol}><dt><MathFormula tex={symbol} /></dt><dd>{description}</dd></div>)}</dl>
      <h4>6.2 · Ein Rechenverfahren, das du immer benutzen kannst</h4>
      <ol><li><b>Vorgang und Anfangszustand erkennen.</b> Wird geladen, entladen oder offengeschaltet? Ist der Kondensator anfangs leer, vollständig vorbereitet oder nur teilweise geladen?</li><li><b>Skizze und Vorzeichen festlegen.</b> Schreib auf, ob du den vorzeichenbehafteten Strom oder seinen Betrag berechnest.</li><li><b>Gegeben und gesucht mit Einheiten notieren.</b> Rechne Präfixe um. Berechne τ = R · C.</li><li><b>Grundgleichung oder passende Funktion hinschreiben.</b> Nicht direkt Zahlen eintippen: Formuliere zuerst den physikalischen Ansatz.</li><li><b>Mit Einheiten einsetzen und rechnen.</b> Der Exponent ist einheitenfrei. Runde erst am Ende.</li><li><b>Ergebnis prüfen und in einem Satz beantworten.</b> Liegt eine Ladespannung zwischen null und U₀? Ist der Entladestrom bei deiner Konvention negativ? Passen Größenordnung und Einheit?</li></ol>
      <RCPractice />
      <Notebook number="6"><ol><li>Vergleichstabelle der Lade- und Entladegleichungen mit Anfangsbedingungen.</li><li>Ein eigenes Größenverzeichnis: jedes Symbol, seine Bedeutung und Einheit.</li><li>Die sechs Pflichtaufgaben mit vollständigen Rechenwegen und sichtbaren Verbesserungen.</li><li>Drei Sätze: „Das habe ich verstanden …“, „Diesen Fehler habe ich verbessert …“, „Diese Frage möchte ich noch besprechen …“.</li></ol></Notebook>
      <aside className="rc-finish"><h4>Selbstkontrolle · Erkläre es ohne Nachschlagen</h4><ul><li>Warum ist der Strom zu Beginn groß und später klein?</li><li>Warum stehen beim Laden die fehlende und beim Entladen die vorhandene Ladung in der Grundgleichung?</li><li>Woher stammen das Minuszeichen und der Faktor aus der Kettenregel?</li><li>Warum verändern R und C beide die Dauer, aber nur R den Anfangsstrom bei gleicher U₀?</li><li>Warum ist die Halbwertszeit kleiner als die Zeitkonstante?</li><li>Was beschreibt eine Stromfläche – und wie erhältst du daraus die Restladung?</li></ul><p>Kannst du eine Frage noch nicht sicher beantworten, gehe zu dem entsprechenden Lernblock zurück und erkläre ihn einem Lernpartner oder laut in eigenen Worten. Dein Heft dient anschließend als Grundlage für die gemeinsame Besprechung.</p></aside>
    </section>
    <details className="rc-teacher"><summary>Für die Lehrkraft · Aufbau und Bezug zu den Buchseiten</summary><p>Die Lernstrecke verknüpft drei Zugänge aus den bereitgestellten Seiten: den qualitativen Spannungs- und Stromverlauf mit der Zeitkonstante (S. 124–125), die vorzeichenbehaftete Spannungsbilanz sowie Parametervergleiche (S. 50–53) und den Weg über Halbwertszeit, Differenzialgleichung und Stromflächen (S. 38–45). Die Kapazität wird vorausgesetzt; ihre geometrische Herleitung bleibt im vorherigen Abschnitt.</p><p>Der Grundversuch übernimmt 20 V, 1 MΩ und 10 µF, verwendet aber neu berechnete, konsistente Modellwerte. In der abgebildeten Tabelle auf S. 39 passen einige Zeit-/Spannungspaare nicht zum selben exponentiellen Verlauf; sie wurden deshalb nicht ungeprüft als Messreihe übernommen. Der Flächenauftrag unterscheidet ausdrücklich abgeflossene Ladung und Restladung. Das Stromvorzeichen bleibt für beide Schalterstellungen einheitlich; die in anderen Büchern verwendete Betragskonvention wird gegenübergestellt.</p><p>Alle Texte, Schaltskizzen, Messaufträge und Aufgaben sind für diese Website neu ausgearbeitet. Die Buchfotos werden nicht auf der öffentlichen Website eingebunden. Lösungen sind für die selbstständige Erarbeitung offen zugänglich, aber einzeln aufzuklappen. Die sechs Pflichtaufgaben schließen 360 Minuten Lernzeit ab; die weiteren Aufgaben sind als Vertiefung gekennzeichnet.</p><p>Bildungsplanbezug: <a href="https://www.bildungsplaene-bw.de/,Lde/BP2016BW_ALLG_GYM_PH.V2_IK_11-12-LF_02_01" target="_blank" rel="noreferrer">Physik Leistungsfach, 3.6.2.1, Kompetenz (8): Zeitverläufe und Einfluss von R und C</a>.</p></details>
  </div>;
}
