export type Exercise = { id: string; title: string; level: string; prompt: string; hint?: string };
export type Chapter = {
  slug: string; title: string; area: string; teaser: string; lead: string; symbol: string; hours: number; tags: string[];
  goals: string[];
  theorySections: { title: string; paragraphs: string[] }[];
  memory: string;
  formulas: { formula: string; meaning: string; condition?: string }[];
  example: { title: string; task: string; steps: string[]; result: string };
  flow: { label: string; detail: string }[];
  lab: { kind: string; title: string; intro: string };
  experiment: { title: string; question: string; materials: string; steps: string[]; evaluation: string[] };
  deepDive: { title: string; text: string };
  exercises: Exercise[];
};

export const chapters: Chapter[] = [
  {
    slug: "werkzeuge-experimentieren", title: "Werkzeuge & Experimentieren", area: "Denk- und Arbeitsweisen", symbol: "Δ", hours: 14,
    teaser: "Einheiten, Diagramme, Messunsicherheit und überzeugende physikalische Argumentationen.",
    lead: "Hier legst du das Fundament für jede spätere Rechnung und jede Abituraufgabe: sauber beobachten, sinnvoll messen, mathematisch modellieren und die Reichweite einer Aussage einschätzen.",
    tags: ["Messdaten", "Diagramme", "AFB III"], goals: ["Messgrößen und Einheiten sicher verwenden", "Diagramme erstellen und physikalisch deuten", "Aussagen evidenzbasiert beurteilen"],
    theorySections: [
      { title: "Vom Phänomen zum Modell", paragraphs: [
        "Physik beginnt nicht mit einer Formel, sondern mit einer präzisen Frage. Zunächst wird ein Phänomen beschrieben, ohne die Erklärung schon in die Beobachtung hineinzuschmuggeln. 'Der Zeiger bewegt sich nach rechts' ist eine Beobachtung; 'der Strom wird größer' ist bereits eine Deutung. Erst wenn Beobachtung, Fragestellung und relevante Größen geklärt sind, wird ein Modell ausgewählt.",
        "Ein Modell ist eine bewusst vereinfachte Darstellung. Beim freien Fall ohne Luftwiderstand wird ein Körper beispielsweise als Massepunkt behandelt und die Fallbeschleunigung als konstant angenommen. Das Modell ist nützlich, solange diese Annahmen zur Fragestellung passen. Eine gute physikalische Antwort nennt deshalb nicht nur das Ergebnis, sondern auch mindestens eine wichtige Voraussetzung oder Grenze.",
      ]},
      { title: "Messwerte, Streuung und Unsicherheit", paragraphs: [
        "Ein Messwert besteht immer aus Zahlenwert und Einheit. Die Einheit legt fest, wie die Größe mit einem vereinbarten Standard verglichen wird. Bei zusammengesetzten Größen hilft eine Einheitenkontrolle, Rechenfehler zu erkennen: Aus einer Strecke geteilt durch eine Zeit muss beispielsweise eine Geschwindigkeit entstehen. Viele scheinbar komplizierte Aufgaben werden übersichtlicher, wenn alle Größen vor dem Einsetzen in SI-Einheiten umgerechnet werden.",
        "Wiederholungsmessungen streuen. Zufällige Abweichungen verändern Betrag und Richtung unvorhersehbar; systematische Abweichungen verschieben eine ganze Messreihe in ähnlicher Weise. Ein Mittelwert vermindert zufällige Schwankungen, beseitigt aber keinen falsch kalibrierten Sensor. Ausreißer dürfen daher nicht nur deshalb gelöscht werden, weil sie unbequem sind. Man benötigt einen sachlichen Grund, etwa einen dokumentierten Fehlstart oder eine erkennbare Störung.",
      ]},
      { title: "Diagramme und Argumentationsketten", paragraphs: [
        "Ein Diagramm ist ein Teil der Auswertung. Auf die waagrechte Achse gehört meist die unabhängig veränderte Größe, auf die senkrechte die abhängige Größe. Achsen werden mit Größe und Einheit beschriftet. Die Steigung einer Geraden trägt ebenfalls eine Einheit. In einem Kraft-Ladungs-Diagramm hat sie zum Beispiel die Einheit N/C und kann als Feldstärke gedeutet werden.",
        "Auf Abiturniveau sollst du nicht nur rechnen, sondern erklären, beurteilen und bewerten. Eine tragfähige Argumentation folgt häufig der Kette: Behauptung – physikalisches Modell – Evidenz oder Rechnung – Einschränkung – Urteil. Das Urteil greift die Aufgabenfrage ausdrücklich auf. Wörter wie 'offensichtlich' oder 'logisch' ersetzen keinen fachlichen Grund.",
      ]},
    ],
    memory: "Eine vollständige physikalische Aussage verbindet Beobachtung, Modell, mathematische Beziehung, Einheit, Ergebnis und Gültigkeitsbereich.",
    formulas: [
      { formula: "Messwert = Zahlenwert · Einheit", meaning: "Grundform jedes Messergebnisses." },
      { formula: "m = Δy / Δx", meaning: "Steigung eines linearen Zusammenhangs." },
      { formula: "x̄ = (x₁ + … + xₙ) / n", meaning: "Arithmetischer Mittelwert einer Messreihe." },
      { formula: "δ = |x − x_ref| / |x_ref|", meaning: "Relative Abweichung von einem Referenzwert.", condition: "x_ref ≠ 0" },
    ],
    example: { title: "Reaktionszeit aus einer Fangstrecke", task: "Ein Lineal fällt 18,0 cm, bevor es gefangen wird. Bestimme die Reaktionszeit und prüfe das Ergebnis.", steps: ["Skizze und Modell: freier Fall aus der Ruhe, Luftwiderstand vernachlässigt.", "Gegeben: s = 0,180 m und g = 9,81 m/s². Gesucht: t.", "Aus s = ½gt² folgt t = √(2s/g). Einsetzen liefert √(0,360 m / 9,81 m/s²).", "Einheitencheck: Unter der Wurzel steht s²; das Ergebnis hat die Einheit s. Eine menschliche Reaktionszeit um 0,2 s ist plausibel."], result: "t = 0,192 s" },
    flow: [{ label: "Beobachten", detail: "Was geschieht tatsächlich?" }, { label: "Modellieren", detail: "Welche Idealisierung passt?" }, { label: "Auswerten", detail: "Daten, Diagramm, Rechnung" }, { label: "Urteilen", detail: "Aussage und Modellgrenze" }],
    lab: { kind: "reaction", title: "Reaktionszeit-Labor", intro: "Verändere die Fangstrecke und beobachte, warum die Reaktionszeit nicht proportional zur Strecke wächst." },
    experiment: { title: "Lineal-Falltest als faire Messung", question: "Wie zuverlässig lässt sich die Reaktionszeit einer Person bestimmen?", materials: "30-cm-Lineal, Tabelle, Taschenrechner", steps: ["Plant zwei Probe- und mindestens sechs Messdurchgänge.", "Legt Startpunkt, Handhaltung und Auslöseverfahren fest.", "Rechnet jede Fangstrecke in eine Reaktionszeit um.", "Bestimmt Mittelwert, Spannweite und einen auffälligen Wert."], evaluation: ["Trennt zufällige und systematische Fehlerquellen.", "Begründet, ob ein Wert ausgeschlossen werden darf.", "Formuliert das Ergebnis mit angemessener Stellenzahl."] },
    deepDive: { title: "Warum mehr Stellen nicht mehr Wahrheit bedeuten", text: "Ein Display kann 9,813742 anzeigen, obwohl der Sensor nur auf 0,1 genau misst. Die zusätzlichen Ziffern sind dann Rechengenauigkeit, keine Messgenauigkeit. Entscheidend sind Auflösung, Kalibrierung, Streuung, Messmodell und nachvollziehbare Dokumentation." },
    exercises: [
      { id: "w1", title: "Einheitenwerkstatt", level: "AFB I", prompt: "Rechne 4,7 ms, 620 nm, 0,035 kN und 2,5·10⁻³ km in SI-Einheiten um. Notiere die Präfixfaktoren." },
      { id: "w2", title: "Steigung mit Bedeutung", level: "AFB I/II", prompt: "In einem v-t-Diagramm steigt v in 2,5 s von 1,0 m/s auf 7,0 m/s. Berechne die Steigung mit Einheit und deute sie physikalisch." },
      { id: "w3", title: "Messreihe", level: "AFB II", prompt: "Fangstrecken: 145, 178, 162, 155, 289, 171, 160, 168 mm. Berechne Mittelwert und Spannweite zunächst mit, dann ohne 289 mm. Vergleiche." },
      { id: "w4", title: "Diagramm auf Papier", level: "AFB II · Heft", prompt: "Zeichne die acht Fangstrecken gegen die Messungsnummer. Markiere Mittelwert und auffälligen Wert. Beschreibe Streuung und Trend in vier Sätzen." },
      { id: "w5", title: "Versuchsqualität", level: "AFB II", prompt: "Nenne je drei zufällige und systematische Fehlerquellen beim Lineal-Falltest. Entwickle zwei konkrete Verbesserungen." },
      { id: "w6", title: "Genauer durch Nachkommastellen?", level: "AFB III · Argumentation", prompt: "Beurteile: 'Ein digitaler Sensor mit sechs Nachkommastellen misst genauer als ein analoges Gerät mit zwei.' Nutze Kriterien, Gegenbeispiel und begründetes Urteil.", hint: "Trenne Anzeigeauflösung, Kalibrierung und Streuung." },
    ],
  },
  {
    slug: "elektrisches-feld", title: "Elektrisches Feld", area: "Elektromagnetische Felder", symbol: "E", hours: 40,
    teaser: "Von Ladung und Coulomb-Kraft zum Feldbegriff, Feldlinien, Potential und Superposition.",
    lead: "Du entwickelst aus beobachtbaren Kraftwirkungen ein räumliches Feldmodell und lernst, dieses Modell zeichnerisch, energetisch und rechnerisch zu nutzen.",
    tags: ["Coulomb", "Feldlinien", "Potential"], goals: ["Coulomb-Kräfte berechnen und einordnen", "Feldkarten zeichnen und Vektoren überlagern", "Potential, Spannung und Energie verknüpfen"],
    theorySections: [
      { title: "Ladung und Coulomb-Kraft", paragraphs: [
        "Elektrische Ladung ist eine Eigenschaft von Materie. In einem abgeschlossenen System bleibt die Gesamtladung erhalten; Reibung erzeugt keine Ladung, sondern trennt bereits vorhandene positive und negative Ladungsanteile. Gleichnamige Ladungen stoßen sich ab, ungleichnamige ziehen sich an. Der Betrag der Kraft zwischen idealisierten Punktladungen wird durch das Coulomb-Gesetz beschrieben.",
        "Die Abhängigkeit F ∝ 1/r² ist ein inverses Quadratgesetz. Verdoppelt sich der Abstand, sinkt die Kraft auf ein Viertel. Dieses Verhalten lässt sich durch eine Linearisierung prüfen: Trägt man F gegen 1/r² auf, sollte im idealen Modell eine Gerade durch den Ursprung entstehen. Reale Ladungsverteilungen, Feuchtigkeit und endliche Körpergrößen begrenzen die Punktladungsnäherung.",
      ]},
      { title: "Feldstärke, Feldlinien und Superposition", paragraphs: [
        "Der Feldbegriff ersetzt die Vorstellung einer unmittelbaren Fernwirkung. Eine Quellladung verändert den Raum. Die elektrische Feldstärke E an einem Ort ist die Kraft pro positiver Probeladung. Das Feld gehört zum Ort und zur Quellenanordnung; die Kraft hängt zusätzlich von Betrag und Vorzeichen der eingebrachten Ladung ab. Für negative Ladungen zeigt die Kraft entgegengesetzt zur Feldrichtung.",
        "Feldlinien sind ein Darstellungsmodell. Die Tangente zeigt die Richtung des Feldvektors, die Liniendichte steht qualitativ für den Betrag. Feldlinien beginnen an positiven und enden an negativen Ladungen oder im Unendlichen; sie kreuzen sich nie. Mehrere Quellen werden durch vektorielle Addition überlagert. Ein Feldnullpunkt bedeutet, dass sich Beiträge aufheben – nicht, dass dort keine Einzelfelder existieren.",
      ]},
      { title: "Potential und Materie im Feld", paragraphs: [
        "Das elektrische Potential beschreibt die potentielle Energie pro Ladung. Eine Spannung ist eine Potentialdifferenz. Bewegt sich eine Ladung durch eine Spannung, ändert sich ihre potentielle Energie um qU. Äquipotentiallinien verbinden Orte gleichen Potentials und stehen im elektrostatischen Fall senkrecht auf den Feldlinien. Entlang einer Äquipotentiallinie verrichtet das Feld keine Arbeit.",
        "In einem Leiter können sich Ladungen verschieben. Im elektrostatischen Gleichgewicht ist das Feld im Inneren eines idealen Leiters null; überschüssige Ladung sitzt auf der Oberfläche. In Isolatoren können sich gebundene positive und negative Ladungsschwerpunkte geringfügig gegeneinander verschieben: Das Material wird polarisiert. Damit lassen sich Faraday-Käfig, angezogener Wasserstrahl und kapazitive Sensoren erklären.",
      ]},
    ],
    memory: "Das Feld gehört zum Ort, die Kraft zusätzlich zur Ladung: F⃗ = q·E⃗. Feldlinien sind keine Teilchenbahnen.",
    formulas: [
      { formula: "F = 1/(4πɛ₀) · |Q₁Q₂|/r²", meaning: "Coulomb-Kraft zwischen Punktladungen.", condition: "Punktladungsnäherung" },
      { formula: "E⃗ = F⃗/q", meaning: "Definition der elektrischen Feldstärke." },
      { formula: "E = 1/(4πɛ₀) · |Q|/r²", meaning: "Feld einer Punktladung." },
      { formula: "E⃗ges = ΣE⃗i", meaning: "Vektorielle Superposition." },
      { formula: "U = Δφ; ΔEpot = qU", meaning: "Potentialdifferenz und Energieänderung." },
    ],
    example: { title: "Feldstärke aus einer Kraftmessung", task: "Auf q = 3,0 nC wirkt F = 6,2 μN nach rechts. Bestimme Feldstärke und Kraft auf q₂ = −4,5 nC.", steps: ["Alle Größen in SI-Einheiten: q = 3,0·10⁻⁹ C, F = 6,2·10⁻⁶ N.", "E = F/q = 2,07·10³ N/C nach rechts.", "Für q₂ gilt F₂ = q₂E. Der Betrag ist 4,5·10⁻⁹ C · 2,07·10³ N/C.", "Wegen des negativen Vorzeichens zeigt die Kraft nach links."], result: "E = 2,1 kN/C nach rechts; F₂ = 9,3 μN nach links" },
    flow: [{ label: "Ladung", detail: "Quelle des Feldes" }, { label: "Feld", detail: "Eigenschaft des Raumes" }, { label: "Kraft", detail: "F⃗ = qE⃗" }, { label: "Energie", detail: "ΔEpot = qU" }],
    lab: { kind: "coulomb", title: "Coulomb-Labor", intro: "Variiere Ladung und Abstand. Prüfe besonders, was eine Verdopplung des Abstands bewirkt." },
    experiment: { title: "Feldstärke operational bestimmen", question: "Bleibt E = F/q bei verschiedenen Probeladungen konstant?", materials: "Kraftsensor oder vorbereiteter Datensatz, Tabellenkalkulation, Diagrammpapier", steps: ["Nimm F für mindestens fünf Werte von q am selben Ort auf.", "Berechne für jede Messung den Quotienten F/q.", "Zeichne F gegen q und bestimme die Steigung.", "Vergleiche Quotientenmittelwert und Geradensteigung."], evaluation: ["Diskutiere Nullpunktfehler und Streuung.", "Erkläre den Einfluss einer zu großen Probeladung.", "Unterscheide Feld- und Teilcheneigenschaft."] },
    deepDive: { title: "Warum ein Blitzableiter Blitze nicht einfach 'anzieht'", text: "An scharfen Spitzen ist die Oberflächenladungsdichte und damit die lokale Feldstärke groß. Das kann die Luft ionisieren. Ein Blitzableiter bietet vor allem einen kontrollierten, gut leitenden Weg zur Erde. Ob und wo ein Blitz entsteht, hängt jedoch von der gesamten Feldverteilung zwischen Gewitterwolke und Boden ab." },
    exercises: [
      { id: "e1", title: "Coulomb-Kraft", level: "AFB I/II", prompt: "Q₁ = 20 nC und Q₂ = −35 nC haben 6,0 cm Abstand. Berechne Betrag und Richtung der Kraft." },
      { id: "e2", title: "Linearisierung", level: "AFB II · Heft", prompt: "Für r = 4, 5, 6, 8, 10 cm werden F = 2,25; 1,44; 1,00; 0,562; 0,360 mN gemessen. Ergänze 1/r² und zeichne F gegen 1/r²." },
      { id: "e3", title: "Feldlinienkarte", level: "AFB II · Zeichnung", prompt: "Zeichne Punktladung, Plattenfeld und Dipol mit mindestens acht Feldlinien. Markiere Symmetrien, starke Bereiche und je eine Modellgrenze." },
      { id: "e4", title: "Vektoren überlagern", level: "AFB II", prompt: "Am Punkt P wirken 3,0 kN/C nach Osten und 4,0 kN/C nach Norden. Bestimme Gesamtfeld und Winkel zeichnerisch und rechnerisch." },
      { id: "e5", title: "Potential und Arbeit", level: "AFB II", prompt: "Ein Elektron durchläuft eine Potentialdifferenz von 850 V. Bestimme Betrag und Vorzeichen seiner potentiellen Energieänderung und erläutere die Änderung der kinetischen Energie." },
      { id: "e6", title: "Blitzableiter-Behauptung", level: "AFB III · Argumentation", prompt: "Beurteile: 'Ein Blitzableiter zieht Blitze an und macht ein Haus deshalb gefährlicher.' Verwende Feldstärke, Ionisation, Leitfähigkeit und Systemgrenze.", hint: "Trenne Entstehung des Blitzes und sicheren Strompfad." },
    ],
  },
  {
    slug: "teilchen-im-e-feld", title: "Teilchen im E-Feld & Gravitation", area: "Elektromagnetische Felder", symbol: "q", hours: 10,
    teaser: "Beschleunigung, Energie und Bahn geladener Teilchen – mit einem tragfähigen Feldvergleich.",
    lead: "Geladene Teilchen reagieren auf elektrische Felder. Aus Kraftgesetz, Energieansatz und Bewegungsüberlagerung entstehen geradlinige Beschleunigung oder eine Parabelbahn.",
    tags: ["Teilchenbahn", "Energie", "Feldvergleich"], goals: ["Teilchenbewegungen aus F = qE herleiten", "Energie- und Zeitansatz passend auswählen", "elektrisches und Gravitationsfeld vergleichen"],
    theorySections: [
      { title: "Bewegung parallel zum Feld", paragraphs: [
        "In einem homogenen elektrischen Feld wirkt auf eine Ladung die konstante Kraft F⃗ = qE⃗. Für ein Teilchen mit konstanter Masse folgt aus dem zweiten Newtonschen Gesetz eine konstante Beschleunigung a⃗ = qE⃗/m. Eine positive Ladung beschleunigt in Feldrichtung, eine negative entgegengesetzt. Die kinematischen Gleichungen der gleichmäßig beschleunigten Bewegung können daher direkt verwendet werden.",
        "Häufig ist der Energieansatz kürzer: Beim Durchlaufen einer Spannung U ändert sich die kinetische Energie um den Betrag |qU|. Aus qU = ½m(v²−v₀²) lässt sich die Geschwindigkeit bestimmen, ohne die Flugzeit zu kennen. Das Vorzeichen muss physikalisch gedeutet werden: Sinkt die potentielle Energie, steigt bei fehlenden Verlusten die kinetische Energie.",
      ]},
      { title: "Bewegung senkrecht zum Feld", paragraphs: [
        "Tritt ein Teilchen mit horizontaler Geschwindigkeit in ein senkrechtes homogenes Feld ein, werden zwei unabhängige Bewegungen überlagert. Horizontal bleibt die Geschwindigkeit konstant, vertikal wirkt eine konstante Beschleunigung. Aus x = v₀t und y = ½at² ergibt sich nach Eliminieren der Zeit eine Parabel y(x). Das ist mathematisch dieselbe Struktur wie beim waagrechten Wurf.",
        "Die Parabel gilt nur innerhalb der idealisierten Plattenregion. Randfelder, Luftwiderstand, relativistische Geschwindigkeiten und Wechselwirkungen mit Materie können das Modell begrenzen. In Elektronenstrahlröhren oder Ablenksystemen muss zudem geprüft werden, ob das Feld wirklich homogen und die Eintrittsgeschwindigkeit scharf festgelegt ist.",
      ]},
      { title: "Elektrisches Feld und Gravitation", paragraphs: [
        "Beide Felder können durch ein inverses Quadratgesetz beschrieben werden und besitzen Feldstärke, Potential und potentielle Energie. Die Quellen unterscheiden sich jedoch: elektrische Ladung kann positiv oder negativ sein, Masse im klassischen Modell nur positiv. Gravitation ist daher stets anziehend, elektrische Wechselwirkung kann anziehen oder abstoßen.",
        "Elektrische Felder lassen sich durch Ladungsverschiebung in Leitern abschirmen; eine vergleichbare Abschirmung der Gravitation ist nicht bekannt. Außerdem ist die elektrische Kraft zwischen Elementarteilchen sehr viel stärker als die Gravitation. Der Vergleich ist nützlich, solange Analogien nicht mit Identität verwechselt werden.",
      ]},
    ],
    memory: "Parallel zum homogenen Feld: konstante Beschleunigung. Senkrecht zum Feld: Überlagerung aus gleichförmiger und gleichmäßig beschleunigter Bewegung.",
    formulas: [
      { formula: "a⃗ = qE⃗/m", meaning: "Beschleunigung im homogenen E-Feld." },
      { formula: "qU = ½m(v²−v₀²)", meaning: "Energieansatz bei Beschleunigung durch eine Spannung." },
      { formula: "x = v₀t; y = ½(qE/m)t²", meaning: "Senkrechter Eintritt in ein homogenes Feld." },
      { formula: "F_G = Gm₁m₂/r²", meaning: "Gravitationskraft zum strukturellen Vergleich." },
    ],
    example: { title: "Elektron nach einer Beschleunigungsspannung", task: "Ein Elektron startet näherungsweise aus der Ruhe und durchläuft 2,0 kV. Bestimme seine Geschwindigkeit klassisch.", steps: ["Energieansatz: eU = ½mₑv².", "Nach v auflösen: v = √(2eU/mₑ).", "Mit e = 1,602·10⁻¹⁹ C, U = 2000 V und mₑ = 9,109·10⁻³¹ kg einsetzen.", "Das Ergebnis liegt deutlich unter c; der klassische Ansatz ist hier als Näherung brauchbar."], result: "v ≈ 2,65·10⁷ m/s" },
    flow: [{ label: "Feld", detail: "E⃗ vorgegeben" }, { label: "Kraft", detail: "F⃗ = qE⃗" }, { label: "Beschleunigung", detail: "a⃗ = F⃗/m" }, { label: "Bahn/Energie", detail: "Kinematik oder qU" }],
    lab: { kind: "particleE", title: "Teilchenbeschleuniger", intro: "Verändere Feldstärke, Ladung und Masse. Vergleiche die Beschleunigung verschiedener Teilchen." },
    experiment: { title: "Ablenkplatte in der Simulation", question: "Wie hängen Ablenkung, Eintrittsgeschwindigkeit und Plattenspannung zusammen?", materials: "Teilchenbahn-Simulation, Tabelle, Taschenrechner", steps: ["Halte zunächst v₀ konstant und variiere U.", "Halte danach U konstant und variiere v₀.", "Miss die Ablenkung am Plattenende.", "Prüfe die erwarteten Proportionalitäten."], evaluation: ["Leite y(L) aus den Bewegungsgleichungen her.", "Erkläre das Vorzeichen für Elektronen.", "Benenne mindestens zwei Modellgrenzen."] },
    deepDive: { title: "Wann wird der klassische Ansatz relativistisch?", text: "Wächst die berechnete Geschwindigkeit in die Nähe der Lichtgeschwindigkeit, ist ½mv² nicht mehr ausreichend. Eine Warnregel ist sinnvoll, sobald v einen merklichen Anteil von c erreicht. Dann muss relativistische Energie verwendet werden; die Geschwindigkeit kann c niemals überschreiten." },
    exercises: [
      { id: "p1", title: "Proton im Plattenfeld", level: "AFB I/II", prompt: "Ein Proton befindet sich in E = 4,0·10⁴ N/C. Bestimme Kraft und Beschleunigung." },
      { id: "p2", title: "Beschleunigungsspannung", level: "AFB II", prompt: "Berechne die klassische Endgeschwindigkeit eines Elektrons nach 750 V und eines Protons nach derselben Spannung. Vergleiche." },
      { id: "p3", title: "Parabelbahn", level: "AFB II · Heft", prompt: "Ein Elektron tritt mit 2,0·10⁷ m/s in ein 4,0 cm langes Feld E = 1,2·10⁴ N/C ein. Bestimme Flugzeit und Ablenkung am Ende." },
      { id: "p4", title: "Bahn skizzieren", level: "AFB II · Zeichnung", prompt: "Skizziere die Bahn einer positiven und einer negativen Ladung bei gleicher Anfangsgeschwindigkeit. Zeichne E⃗, F⃗ und v⃗ an drei Punkten." },
      { id: "p5", title: "Feldvergleich", level: "AFB II", prompt: "Erstelle eine Vergleichsmatrix zu Quelle, Vorzeichen, Kraftgesetz, Potential, Abschirmung und typischer Stärke von elektrischem Feld und Gravitationsfeld." },
      { id: "p6", title: "Abschirmung", level: "AFB III · Argumentation", prompt: "Erkläre, warum ein Faraday-Käfig elektrische Felder abschirmen kann, und beurteile, ob sich dieselbe Idee auf Gravitation übertragen lässt." },
    ],
  },
  {
    slug: "kondensator-rc", title: "Kondensator & RC-Kreis", area: "Elektromagnetische Felder", symbol: "C", hours: 22,
    teaser: "Kapazität, Energie, Dielektrika sowie exponentielles Auf- und Entladen.",
    lead: "Kondensatoren speichern getrennte Ladung und elektrische Feldenergie. Im RC-Kreis wird daraus ein zeitabhängiger Prozess mit einer charakteristischen Zeitkonstante.",
    tags: ["Kapazität", "Energie", "Exponentialfunktion"], goals: ["Kapazität als Bauteileigenschaft deuten", "Energie und Geometrie verknüpfen", "RC-Zeitverläufe lesen und berechnen"],
    theorySections: [
      { title: "Kapazität und Plattengeometrie", paragraphs: [
        "Ein Kondensator besteht aus zwei voneinander isolierten Leitern. Wird Ladung getrennt, entsteht zwischen ihnen eine Spannung. Die Kapazität C = Q/U beschreibt, wie viel Ladung pro Spannung gespeichert wird. Sie hängt im linearen Bereich von Geometrie und Material, nicht vom augenblicklichen Wert von Q oder U ab.",
        "Für den idealen Plattenkondensator gilt C = ε₀εᵣA/d. Größere Plattenfläche erhöht, größerer Abstand verringert die Kapazität. Ein Dielektrikum polarisiert sich im Feld und schwächt bei fester freier Ladung das innere Feld; dadurch wächst die Kapazität um den Faktor εᵣ. Randfelder und Durchschlag begrenzen das ideale Modell.",
      ]},
      { title: "Energie im elektrischen Feld", paragraphs: [
        "Beim Laden wird Arbeit gegen die zunehmende Spannung verrichtet. Im Q-U-Diagramm entspricht die gespeicherte Energie der Fläche unter der Geraden. Daraus folgen E = ½QU = ½CU² = Q²/(2C). Welche Formel den Einfluss einer Änderung richtig beschreibt, hängt davon ab, was konstant bleibt.",
        "Ist ein Kondensator an eine Spannungsquelle angeschlossen, bleibt U näherungsweise fest und Ladung kann nachfließen. Wird er vorher abgetrennt, bleibt Q fest. Beim Einführen eines Dielektrikums kann die Energie deshalb je nach Randbedingung steigen oder sinken. Gerade solche Randbedingungen sind typische Argumentationspunkte auf Abiturniveau.",
      ]},
      { title: "Auf- und Entladen im RC-Kreis", paragraphs: [
        "Beim Laden ist die Stromstärke anfangs groß, weil am ungeladenen Kondensator noch kaum Gegenspannung anliegt. Mit wachsender Kondensatorspannung sinkt der Strom exponentiell. Nach der Zeitkonstante τ = RC hat die Spannung beim Laden etwa 63 % ihres Endwerts erreicht; beim Entladen sind noch etwa 37 % des Anfangswerts vorhanden.",
        "Die Exponentialfunktion bedeutet, dass in gleichen Zeitabschnitten derselbe Anteil der noch fehlenden oder vorhandenen Größe verändert wird. R und C beeinflussen die Geschwindigkeit des Vorgangs, nicht den Endwert bei einer idealen Gleichspannungsquelle. Messdiagramme sollten Anfangswert, Endwert, τ und die Form der Tangente erkennen lassen.",
      ]},
    ],
    memory: "Kapazität ist eine Bauteileigenschaft. Im RC-Kreis bestimmt τ = RC die Zeitskala, nicht die Endspannung.",
    formulas: [
      { formula: "C = Q/U", meaning: "Definition der Kapazität im linearen Bereich." },
      { formula: "C = ε₀εᵣA/d", meaning: "Idealer Plattenkondensator." },
      { formula: "Eel = ½CU² = Q²/(2C)", meaning: "Gespeicherte elektrische Energie." },
      { formula: "τ = RC", meaning: "Zeitkonstante des RC-Kreises." },
      { formula: "UC(t)=U₀(1−e^(−t/RC))", meaning: "Ladespannung." },
      { formula: "UC(t)=U₀e^(−t/RC)", meaning: "Entladespannung." },
    ],
    example: { title: "Entladezeit bis 10 %", task: "Ein Kondensator C = 220 μF wird über R = 15 kΩ entladen. Nach welcher Zeit sind noch 10 % der Anfangsspannung vorhanden?", steps: ["Zeitkonstante: τ = RC = 15·10³ Ω · 220·10⁻⁶ F = 3,30 s.", "Ansatz: U/U₀ = e^(−t/τ) = 0,10.", "Logarithmieren: ln(0,10) = −t/τ, also t = −τ ln(0,10).", "Plausibilität: Nach 2,303 Zeitkonstanten bleiben 10 % übrig."], result: "t = 7,60 s" },
    flow: [{ label: "Geometrie", detail: "A, d, εᵣ" }, { label: "Kapazität", detail: "C = Q/U" }, { label: "Energie", detail: "½CU²" }, { label: "Zeitverlauf", detail: "τ = RC" }],
    lab: { kind: "capacitor", title: "Kondensator-Labor", intro: "Verändere R, C und U. Beobachte Zeitkonstante und gespeicherte Energie getrennt." },
    experiment: { title: "Entladekurve aufnehmen", question: "Folgt UC(t) einer Exponentialfunktion?", materials: "Kondensator, Widerstand, Spannungsmessgerät oder Sensor, Schalter", steps: ["Lade den Kondensator auf eine bekannte Spannung.", "Starte Zeitmessung und Entladung gleichzeitig.", "Nimm UC in gleichmäßigen Zeitabständen auf.", "Bestimme τ über die 37-%-Marke und vergleiche mit RC."], evaluation: ["Zeichne UC(t) mit Einheiten.", "Linearisiere optional ln(U/U₀) gegen t.", "Diskutiere Innenwiderstand und Messgerätebelastung."] },
    deepDive: { title: "Die entscheidende Frage: Q oder U konstant?", text: "Wird der Plattenabstand verändert, führt dieselbe geometrische Änderung je nach Anschlussbedingung zu unterschiedlichen Energieänderungen. An der Spannungsquelle kann Ladung fließen; beim isolierten Kondensator nicht. Ohne diese Randbedingung ist eine Aussage wie 'Die Energie steigt' unvollständig." },
    exercises: [
      { id: "c1", title: "Kapazität bestimmen", level: "AFB I/II", prompt: "Ein Kondensator speichert bei 12 V die Ladung 3,6 mC. Bestimme C." },
      { id: "c2", title: "Plattenkondensator", level: "AFB II", prompt: "A = 180 cm², d = 1,5 mm, εᵣ = 1. Berechne C. Untersuche rechnerisch die Verdopplung von A und d." },
      { id: "c3", title: "Energie und Blitzgerät", level: "AFB II", prompt: "Ein 120-μF-Kondensator wird auf 330 V geladen. Berechne Ladung und Energie. Vergleiche mit derselben Kapazität bei 165 V." },
      { id: "c4", title: "RC-Diagramm", level: "AFB II · Heft", prompt: "Skizziere Lade- und Entladekurve für τ = 2,0 s. Markiere Werte bei 0, τ, 2τ und 3τ sowie Anfangs- und Endwert." },
      { id: "c5", title: "Zeit bis 5 %", level: "AFB II", prompt: "C = 47 μF, R = 100 kΩ, U₀ = 9,0 V. Berechne die Zeit, bis U auf 5 % von U₀ gefallen ist." },
      { id: "c6", title: "Dielektrikum und Energie", level: "AFB III · Argumentation", prompt: "Ein Dielektrikum wird vollständig eingeführt. Vergleiche die Energieänderung für (a) angeschlossene Spannungsquelle und (b) zuvor abgetrennten Kondensator. Begründe mit konstanten Größen." },
    ],
  },
  {
    slug: "magnetisches-feld", title: "Magnetisches Feld & Lorentzkraft", area: "Elektromagnetische Felder", symbol: "B", hours: 26,
    teaser: "Kräfte auf Leiter und Ladungen, Spulenfeld, Hall-Effekt und Kreisbahnen.",
    lead: "Magnetfelder wirken auf bewegte Ladungen. Richtung, Betrag und Bewegungsform ergeben sich aus einer vektoriellen Kraft, die stets senkrecht zu Geschwindigkeit und Magnetfeld steht.",
    tags: ["Lorentzkraft", "Kreisbahn", "Spule"], goals: ["Magnetfelder darstellen und Richtungen bestimmen", "Lorentzkräfte berechnen", "Kreisbahnen und Sensoren erklären"],
    theorySections: [
      { title: "Magnetfelder und Leiterkraft", paragraphs: [
        "Magnetische Feldlinien sind geschlossen: Außerhalb eines Stabmagneten verlaufen sie vom Nord- zum Südpol, im Inneren zurück. Ein langer gerader Leiter erzeugt konzentrische Feldlinien; eine Spule besitzt ein Feld ähnlich einem Stabmagneten. Die Rechte-Hand-Regel verknüpft technische Stromrichtung und Umlaufrichtung des Magnetfelds.",
        "Auf einen stromdurchflossenen Leiter im Magnetfeld wirkt eine Kraft, weil sich im Leiter Ladungsträger bewegen. Für einen geraden Leiter gilt F = BIl·sin α. Die Kraft ist maximal bei senkrechter Anordnung und null bei parallelem Leiter. Richtung und Vorzeichen müssen mit einer vereinbarten Drei-Finger-Regel sauber bestimmt werden.",
      ]},
      { title: "Lorentzkraft und Kreisbahn", paragraphs: [
        "Für ein einzelnes Teilchen lautet der Betrag der magnetischen Lorentzkraft F_L = |q|vB·sin α. Da die Kraft senkrecht zur momentanen Geschwindigkeit steht, verrichtet ein statisches Magnetfeld keine Arbeit. Der Betrag der Geschwindigkeit und damit die kinetische Energie bleiben konstant; geändert wird nur die Richtung.",
        "Bei v senkrecht zu B wirkt die Lorentzkraft als Zentripetalkraft. Aus |q|vB = mv²/r folgt r = mv/(|q|B). Größere Masse oder Geschwindigkeit vergrößern, größere Ladung oder Feldstärke verkleinern den Radius. Besitzt v zusätzlich eine Komponente parallel zu B, entsteht eine Schraubenbahn.",
      ]},
      { title: "Spulenfeld und Hall-Effekt", paragraphs: [
        "Im Inneren einer langen, schlanken Spule ist das Feld näherungsweise homogen. Sein Betrag wächst mit Stromstärke, Windungsdichte N/l und relativer Permeabilität des Kerns. An den Enden treten Randfelder auf; kurze Spulen weichen deutlich von der Idealformel ab.",
        "Beim Hall-Effekt werden bewegte Ladungsträger quer zur Stromrichtung durch die Lorentzkraft verschoben. Die entstehende Hall-Spannung wächst bei festem Aufbau mit Stromstärke und Magnetfeld. Hall-Sensoren messen kontaktlos Magnetfelder, Positionen oder Drehzahlen. Das Vorzeichen kann zusätzlich Auskunft über die Art der dominierenden Ladungsträger geben.",
      ]},
    ],
    memory: "Ein statisches Magnetfeld ändert bei einem freien Teilchen die Bewegungsrichtung, aber nicht den Betrag der Geschwindigkeit.",
    formulas: [
      { formula: "F = BIl·sin α", meaning: "Kraft auf einen geraden stromdurchflossenen Leiter." },
      { formula: "F_L = |q|vB·sin α", meaning: "Magnetische Lorentzkraft." },
      { formula: "r = mv/(|q|B)", meaning: "Kreisbahnradius bei v ⟂ B." },
      { formula: "B = μ₀μᵣ(N/l)I", meaning: "Feld einer langen schlanken Spule." },
      { formula: "U_H ∝ I·B", meaning: "Hall-Spannung bei festem Sensoraufbau." },
    ],
    example: { title: "Elektron auf Kreisbahn", task: "Ein Elektron mit v = 3,0·10⁷ m/s fliegt senkrecht in B = 8,0 mT. Bestimme den Radius.", steps: ["Kräfteansatz: Lorentzkraft liefert Zentripetalkraft.", "|q|vB = mv²/r, daher r = mv/(|q|B).", "SI-Werte einsetzen: mₑ = 9,109·10⁻³¹ kg, e = 1,602·10⁻¹⁹ C, B = 8,0·10⁻³ T.", "Das Magnetfeld verrichtet keine Arbeit; v bleibt im Modell konstant."], result: "r = 2,13 cm" },
    flow: [{ label: "Bewegte Ladung", detail: "q und v⃗" }, { label: "Magnetfeld", detail: "B⃗" }, { label: "Lorentzkraft", detail: "senkrecht zu v⃗ und B⃗" }, { label: "Bahn", detail: "Kreis oder Helix" }],
    lab: { kind: "magnetic", title: "Lorentzkraft-Labor", intro: "Verändere Geschwindigkeit, Magnetfeld und Teilchenart. Beobachte Kraft und Kreisbahnradius." },
    experiment: { title: "Kraft auf die Leiterschaukel", question: "Wie hängt die Leiterkraft von I und Leiterlänge l ab?", materials: "Leiterschaukel oder Kraftsensor, Magnet, Stromversorgung, Maßstab", steps: ["Richte Leiter und Magnetfeld senkrecht aus.", "Miss F für mehrere Stromstärken bei konstantem l.", "Wiederhole mit zwei Leiterlängen.", "Zeichne F gegen I und bestimme die Steigung."], evaluation: ["Prüfe F ∝ I und F ∝ l.", "Bestimme B aus der Steigung.", "Diskutiere Feldinhomogenität und Erwärmung."] },
    deepDive: { title: "Warum ein Magnetfeld ein Teilchen nicht schneller macht", text: "Leistung ist P = F⃗·v⃗. Weil die magnetische Lorentzkraft senkrecht zur Geschwindigkeit steht, ist das Skalarprodukt null. Ein statisches Magnetfeld überträgt daher keine Energie auf das freie Teilchen, obwohl es dessen Impulsrichtung fortlaufend ändert." },
    exercises: [
      { id: "m1", title: "Leiterkraft", level: "AFB I/II", prompt: "Ein 8,0 cm langer Leiter führt 3,5 A senkrecht zu B = 0,42 T. Berechne Kraft und skizziere die Richtung für eine angegebene Feldrichtung." },
      { id: "m2", title: "Lorentzkraft", level: "AFB II", prompt: "Ein Proton bewegt sich mit 1,8·10⁶ m/s bei α = 30° in B = 0,15 T. Berechne den Kraftbetrag." },
      { id: "m3", title: "Kreisbahn", level: "AFB II", prompt: "Bestimme Radius und Umlaufdauer eines Protons bei v = 2,0·10⁶ m/s und B = 0,25 T." },
      { id: "m4", title: "Spulenfeld", level: "AFB II", prompt: "Eine Luftspule mit N = 1200, l = 0,40 m führt I = 0,80 A. Berechne B im Inneren und nenne zwei Modellgrenzen." },
      { id: "m5", title: "Hall-Sensor", level: "AFB II · Erklärung", prompt: "Erstelle eine beschriftete Skizze zur Ladungstrennung im Hall-Sensor und erkläre, wann das Kräftegleichgewicht erreicht ist." },
      { id: "m6", title: "Arbeit des Magnetfelds", level: "AFB III · Argumentation", prompt: "Beurteile: 'Weil ein Magnet ein Teilchen auf eine Kreisbahn zwingt, führt er ihm ständig Energie zu.' Nutze Kraft, Geschwindigkeit, Arbeit und Energie." },
    ],
  },
  {
    slug: "gekreuzte-felder", title: "Gekreuzte Felder", area: "Elektromagnetische Felder", symbol: "×", hours: 10,
    teaser: "Wien-Filter und Massenspektrometer als mehrstufige Modellanwendungen.",
    lead: "Elektrisches und magnetisches Feld können Kräfte auf geladene Teilchen verstärken oder aufheben. Daraus entstehen präzise Geschwindigkeitsfilter und Verfahren zur Massenbestimmung.",
    tags: ["Wien-Filter", "Massenspektrometer", "Modellkette"], goals: ["Kraftrichtungen in gekreuzten Feldern bestimmen", "v = E/B herleiten", "mehrstufige Teilchenexperimente auswerten"],
    theorySections: [
      { title: "Kräftegleichgewicht im Wien-Filter", paragraphs: [
        "In einem Geschwindigkeitsfilter stehen E⃗ und B⃗ senkrecht zueinander und zugleich senkrecht zur Bewegungsrichtung. Die elektrische Kraft qE und die magnetische Lorentzkraft qvB werden so ausgerichtet, dass sie entgegengesetzt wirken. Nur für qE = qvB ist die resultierende Kraft null und das Teilchen fliegt geradlinig hindurch.",
        "Nach Kürzen der Ladung folgt v = E/B. Die ausgewählte Geschwindigkeit ist unabhängig von Masse und Ladungsbetrag, solange das Teilchen geladen ist und die idealen Feldrichtungen erfüllt sind. Langsamere oder schnellere Teilchen werden in entgegengesetzte Richtungen abgelenkt.",
      ]},
      { title: "Massenspektrometer als Modellkette", paragraphs: [
        "Hinter dem Geschwindigkeitsfilter kann ein reines Magnetfeld die ausgewählten Teilchen auf Kreisbahnen lenken. Aus r = mv/(|q|B₂) folgt m/|q| = rB₂/v. Wird v durch E/B₁ ersetzt, lässt sich das Masse-zu-Ladung-Verhältnis allein aus Feldern und Radius bestimmen.",
        "Ein Massenspektrometer besteht deshalb aus aufeinander abgestimmten Teilmodellen: Ionisation erzeugt geladene Teilchen, Beschleunigung oder Filterung legt die Geschwindigkeit fest, Ablenkung trennt m/q, Detektion misst die Auftrefforte. Ein Fehler in einer Stufe beeinflusst die gesamte Auswertung.",
      ]},
      { title: "Isotope, Auflösung und Grenzen", paragraphs: [
        "Isotope eines Elements besitzen gleiche Protonenzahl, aber unterschiedliche Neutronenzahl und daher unterschiedliche Masse. Bei gleicher Ladung und Geschwindigkeit entstehen verschiedene Radien. Die Intensität der Detektorsignale kann Hinweise auf relative Häufigkeiten geben.",
        "Reale Strahlen besitzen eine endliche Geschwindigkeits- und Richtungsverteilung. Feldinhomogenität, Mehrfachladung und Detektorbreite begrenzen die Auflösung. Eine gemessene Radiusdifferenz ist erst dann aussagekräftig, wenn sie größer als die experimentelle Unschärfe ist.",
      ]},
    ],
    memory: "Der Wien-Filter wählt v = E/B; das anschließende Magnetfeld trennt nach m/|q|.",
    formulas: [
      { formula: "qE = |q|vB", meaning: "Kräftegleichgewicht im Wien-Filter." },
      { formula: "v = E/B", meaning: "Durchlassgeschwindigkeit." },
      { formula: "r = mv/(|q|B₂)", meaning: "Radius im Analysiermagnetfeld." },
      { formula: "m/|q| = rB₂/v", meaning: "Masse-zu-Ladung-Verhältnis." },
    ],
    example: { title: "Masse eines einfach geladenen Ions", task: "E = 3,0·10⁴ V/m, B₁ = 0,20 T. Im Analysierfeld B₂ = 0,35 T misst man r = 8,0 cm. Bestimme m für q = e.", steps: ["Wien-Filter: v = E/B₁ = 1,50·10⁵ m/s.", "Kreisbahn: m = |q|B₂r/v.", "Einsetzen mit e = 1,602·10⁻¹⁹ C und r = 0,080 m.", "Zur Einordnung in atomare Masseneinheiten durch u = 1,6605·10⁻²⁷ kg teilen."], result: "m = 2,99·10⁻²⁶ kg ≈ 18,0 u" },
    flow: [{ label: "Ionisieren", detail: "Teilchen erhält q" }, { label: "Filtern", detail: "v = E/B" }, { label: "Ablenken", detail: "r ∝ m/q" }, { label: "Detektieren", detail: "Radius und Häufigkeit" }],
    lab: { kind: "crossed", title: "Wien-Filter-Labor", intro: "Stelle E und B ein. Welche Geschwindigkeit passiert den Filter unabgelenkt?" },
    experiment: { title: "Massenspektrometer-Simulation", question: "Wie lassen sich zwei Isotope trennen?", materials: "Simulation, Tabellenblatt, bekannte Elementarladung", steps: ["Kalibriere den Filter mit bekannten E- und B-Werten.", "Miss Radien zweier Detektorsignale.", "Berechne m/q für beide Bahnen.", "Varriere die Spaltbreite und beobachte die Auflösung."], evaluation: ["Ordne mögliche Isotope zu.", "Unterscheide Masseänderung und Mehrfachladung.", "Beurteile, ob die Peaks experimentell getrennt sind."] },
    deepDive: { title: "Warum die Ladung im Wien-Filter herausfällt", text: "Beide Kräfte sind proportional zu q. Beim Kräftegleichgewicht wird der Ladungsbetrag gekürzt. Das bedeutet nicht, dass neutrale Teilchen den Filter genauso durchlaufen: Auf sie wirken beide Kräfte gar nicht, und sie werden deshalb auch nicht kontrolliert oder nachgewiesen wie Ionen." },
    exercises: [
      { id: "g1", title: "Durchlassgeschwindigkeit", level: "AFB I/II", prompt: "Berechne v für E = 4,5·10⁴ V/m und B = 0,18 T." },
      { id: "g2", title: "Richtungen", level: "AFB II · Zeichnung", prompt: "Ein positives Ion fliegt nach rechts, B zeigt in die Papierebene. Zeichne F_L und wähle die Richtung von E, damit das Ion geradlinig fliegt. Wiederhole für ein negatives Ion." },
      { id: "g3", title: "Masse bestimmen", level: "AFB II", prompt: "Nach einem Wien-Filter mit v = 2,2·10⁵ m/s bewegt sich ein einfach geladenes Ion bei B = 0,40 T auf r = 6,5 cm. Bestimme m in kg und u." },
      { id: "g4", title: "Isotopenabstand", level: "AFB II", prompt: "Zwei einfach geladene Isotope mit 20 u und 22 u haben gleiche Geschwindigkeit. Bestimme das Verhältnis ihrer Radien und den Radiusunterschied bei r₂₀ = 10,0 cm." },
      { id: "g5", title: "Mehrfachladung", level: "AFB II", prompt: "Erkläre, warum ein doppelt geladenes Ion denselben Radius wie ein anderes Ion mit halber Masse besitzen kann. Entwickle eine zusätzliche Prüfmöglichkeit." },
      { id: "g6", title: "Gerät beurteilen", level: "AFB III · Argumentation", prompt: "Ein Schüler behauptet: 'Ein größerer Radius bedeutet immer ein schwereres Isotop.' Beurteile unter Einbezug von v, q, B und Messunsicherheit." },
    ],
  },
  {
    slug: "induktion", title: "Induktion & Elektrodynamik", area: "Elektromagnetische Felder", symbol: "Φ", hours: 44,
    teaser: "Faraday, Lenz, Selbstinduktion, Energie der Spule und technische Anwendungen.",
    lead: "Zeitliche Änderungen magnetischer Flüsse erzeugen elektrische Spannungen. Das Induktionsgesetz verbindet Bewegung, Felder und Energieerhaltung zu einer zentralen Idee der Elektrodynamik.",
    tags: ["Faraday", "Lenz", "Selbstinduktion"], goals: ["magnetischen Fluss berechnen", "Induktionsspannung und Richtung bestimmen", "technische Anwendungen energetisch erklären"],
    theorySections: [
      { title: "Magnetischer Fluss und Faraday-Gesetz", paragraphs: [
        "Der magnetische Fluss Φ = BA·cos α beschreibt, wie stark ein Magnetfeld eine gedachte Fläche durchsetzt. Dabei ist α der Winkel zwischen B⃗ und dem Flächennormalenvektor. Der Fluss kann sich ändern, weil B, A oder der Winkel verändert wird. Entscheidend ist nicht ein großer Fluss an sich, sondern seine zeitliche Änderung.",
        "Das Faraday-Gesetz U_ind = −N·dΦ/dt beschreibt die induzierte Spannung einer Spule mit N Windungen. Eine schnelle Änderung, eine große Windungszahl oder eine größere wirksame Fläche erhöht den Betrag. Für gleichmäßige Änderungen kann die Ableitung näherungsweise durch ΔΦ/Δt ersetzt werden.",
      ]},
      { title: "Lenz-Regel und Energieerhaltung", paragraphs: [
        "Das Minuszeichen steht für die Lenz-Regel: Ein induzierter Strom ist so gerichtet, dass sein Magnetfeld der Ursache der Flussänderung entgegenwirkt. Beim Annähern eines Magneten entsteht beispielsweise ein Gegenfeld, das die Annäherung bremst. Beim Entfernen wirkt das induzierte Feld der Abnahme entgegen.",
        "Die Lenz-Regel ist eine Folge der Energieerhaltung. Würde der induzierte Strom die verursachende Änderung verstärken, könnte ohne äußere Arbeit immer mehr Energie entstehen. Tatsächlich muss beim Generator mechanische Arbeit gegen elektromagnetische Gegenkräfte verrichtet werden; diese Energie wird elektrisch übertragen und teilweise als Wärme abgegeben.",
      ]},
      { title: "Selbstinduktion, Spule und Anwendungen", paragraphs: [
        "Ändert sich der Strom einer Spule, ändert sich ihr eigenes Magnetfeld und damit ihr eigener Fluss. Es entsteht die Selbstinduktionsspannung U_ind = −L·dI/dt. Die Induktivität L hängt von Geometrie, Windungszahl und Kernmaterial ab. Beim Einschalten verzögert die Selbstinduktion den Stromanstieg, beim Ausschalten kann eine große Spannung auftreten.",
        "Im Magnetfeld einer Spule ist Energie E = ½LI² gespeichert. Transformator, Generator, Wirbelstrombremse, dynamisches Mikrofon und induktives Laden nutzen unterschiedliche Formen derselben Grundidee. Eine gute technische Erklärung benennt Eingangsenergie, Flussänderung, Induktionsspannung, Stromweg und Verluste.",
      ]},
    ],
    memory: "Induziert wird durch die Änderung des magnetischen Flusses. Die Wirkung bremst ihre Ursache – sonst wäre Energieerhaltung verletzt.",
    formulas: [
      { formula: "Φ = BA·cos α", meaning: "Magnetischer Fluss durch eine ebene Fläche." },
      { formula: "U_ind = −N·dΦ/dt", meaning: "Faraday-Gesetz für eine Spule." },
      { formula: "U_ind = −L·dI/dt", meaning: "Selbstinduktionsspannung." },
      { formula: "L ≈ μ₀μᵣN²A/l", meaning: "Induktivität einer langen Spule." },
      { formula: "Emag = ½LI²", meaning: "Energie im Magnetfeld der Spule." },
    ],
    example: { title: "Induktion durch Flussänderung", task: "Eine Spule mit 500 Windungen und A = 24 cm² wird in 0,080 s aus B = 0,35 T vollständig herausgezogen. Bestimme den mittleren Betrag der Spannung.", steps: ["Anfangsfluss pro Windung: Φ₁ = BA, Endfluss Φ₂ = 0.", "A = 24·10⁻⁴ m² = 2,4·10⁻³ m².", "|U| = N·|ΔΦ|/Δt = 500·0,35 T·2,4·10⁻³ m² / 0,080 s.", "Die Richtung hängt von Feldrichtung und Wicklungssinn ab und wird separat mit Lenz bestimmt."], result: "|U_ind| = 5,25 V" },
    flow: [{ label: "Änderung", detail: "B, A oder Winkel" }, { label: "Fluss", detail: "Φ(t)" }, { label: "Spannung", detail: "−N dΦ/dt" }, { label: "Gegenwirkung", detail: "Lenz & Energie" }],
    lab: { kind: "induction", title: "Induktions-Labor", intro: "Verändere Windungszahl und Änderungsdauer. Beobachte, wann die Spannung groß wird." },
    experiment: { title: "Magnet fällt durch Metallrohr", question: "Warum fällt ein Magnet in einem Kupferrohr langsamer?", materials: "Kupfer- oder Aluminiumrohr, starker Magnet, Vergleichskörper, Stoppuhr", steps: ["Vergleiche Fallzeiten von Magnet und nichtmagnetischem Körper.", "Prüfe, ob der Magnet am Rohr haften bleibt.", "Skizziere Flussänderung und mögliche Wirbelströme.", "Ordne die Richtung des induzierten Feldes beim Eintritt und Austritt zu."], evaluation: ["Erkläre die Bremskraft mit Lenz.", "Verfolge die Energieumwandlung.", "Nenne Grenzen und Sicherheitsaspekte des Versuchs."] },
    deepDive: { title: "Vier Maxwell-Ideen ohne Formelsalat", text: "Ladungen erzeugen elektrische Felder; magnetische Monopole werden nicht beobachtet; zeitlich veränderliche Magnetfelder erzeugen Wirbelfelder des elektrischen Felds; zeitlich veränderliche elektrische Felder und Ströme erzeugen magnetische Felder. Zusammen ermöglichen diese Aussagen elektromagnetische Wellen." },
    exercises: [
      { id: "i1", title: "Magnetischer Fluss", level: "AFB I/II", prompt: "Eine Fläche 35 cm² liegt in B = 0,28 T. Berechne Φ für α = 0°, 60° und 90° zwischen B und Flächennormale." },
      { id: "i2", title: "Induktionsspannung", level: "AFB II", prompt: "Bei N = 800 ändert sich der Fluss pro Windung in 25 ms um 1,8·10⁻⁴ Wb. Berechne den mittleren Spannungsbetrag." },
      { id: "i3", title: "Lenz-Richtung", level: "AFB II · Zeichnung", prompt: "Ein Nordpol nähert sich einer Spule. Zeichne Magnetfeld, induzierten Spulenpol und technische Stromrichtung. Wiederhole beim Entfernen." },
      { id: "i4", title: "Energie der Spule", level: "AFB II", prompt: "Eine Spule L = 0,75 H führt 2,4 A. Berechne die Energie. Wie ändert sie sich bei doppeltem Strom?" },
      { id: "i5", title: "Generator erklären", level: "AFB II", prompt: "Erstelle ein Fluss-Zeit- und ein Spannungs-Zeit-Diagramm für eine gleichförmig rotierende Leiterschleife. Begründe die Phasenlage." },
      { id: "i6", title: "Lenz und Energie", level: "AFB III · Argumentation", prompt: "Beurteile: 'Die Lenz-Regel verhindert Induktion, weil das induzierte Feld die Flussänderung aufhebt.' Unterscheide Gegenwirkung, vollständige Kompensation und Energiezufuhr." },
    ],
  },
  {
    slug: "schwingungen", title: "Mechanische & elektromagnetische Schwingungen", area: "Schwingungen", symbol: "T", hours: 40,
    teaser: "Harmonische Bewegung, Differentialgleichungen, Resonanz und LC-Kreis.",
    lead: "Schwingungen verbinden periodische Zeitverläufe mit Rückstellkräften und Energieaustausch. Mechanische und elektromagnetische Systeme folgen derselben mathematischen Struktur.",
    tags: ["Harmonisch", "DGL", "Resonanz"], goals: ["Schwingungsgrößen und Phasenlagen deuten", "Periodendauern herleiten und berechnen", "Resonanz und LC-Kreis vergleichen"],
    theorySections: [
      { title: "Kennzeichen einer Schwingung", paragraphs: [
        "Eine Schwingung ist eine zeitlich periodische Änderung um eine Gleichgewichtslage. Wichtige Größen sind Auslenkung s(t), Amplitude ŝ, Periodendauer T, Frequenz f und Kreisfrequenz ω. Harmonisch heißt eine Schwingung, wenn s(t) sinus- oder cosinusförmig verläuft. Nicht jede periodische Bewegung ist harmonisch.",
        "Bei s(t)=ŝ cos(ωt) sind Geschwindigkeit und Beschleunigung zeitlich phasenverschoben. In der Ruhelage ist der Geschwindigkeitsbetrag maximal, an den Umkehrpunkten null. Die Beschleunigung ist stets zur Ruhelage gerichtet und erfüllt a(t)=−ω²s(t). Diagramme von s, v und a sollten deshalb nicht unabhängig auswendig gelernt, sondern aus Ableitungen und Bewegungsvorstellung verstanden werden.",
      ]},
      { title: "Rückstellkraft, DGL und Energie", paragraphs: [
        "Beim idealen Federpendel gilt Hookes Gesetz F = −Ds. Mit F = ma folgt m·s¨ = −Ds. Die Differentialgleichung sagt: Die zweite zeitliche Änderung der Auslenkung ist proportional zur Auslenkung und entgegengesetzt gerichtet. Der Sinus- oder Cosinusansatz erfüllt diese Bedingung mit ω² = D/m.",
        "Während der Schwingung wechseln kinetische und potentielle Energie. Beim Federpendel gilt E = ½mv² + ½Ds². Ohne Reibung bleibt die Summe konstant. Dämpfung wandelt mechanische Energie in innere Energie um; bei erzwungenen Schwingungen führt der Erreger fortlaufend Energie zu.",
      ]},
      { title: "Resonanz und elektromagnetischer Schwingkreis", paragraphs: [
        "Wird ein System periodisch angeregt, hängt die stationäre Amplitude von Erregerfrequenz und Dämpfung ab. In der Nähe der Eigenfrequenz tritt Resonanz auf. Geringe Dämpfung führt zu einer hohen, schmalen Resonanzkurve; starke Dämpfung zu einer niedrigeren, breiteren. Resonanz kann erwünscht sein, etwa beim Musikinstrument, oder gefährlich, etwa bei Bauteilen.",
        "Im idealen LC-Kreis pendelt Energie zwischen elektrischem Feld des Kondensators und magnetischem Feld der Spule. Ladung Q entspricht der mechanischen Auslenkung, Strom I der Geschwindigkeit. Die Differentialgleichung Q¨ = −Q/(LC) führt zur Thomson-Formel T = 2π√(LC). Widerstände dämpfen die reale elektromagnetische Schwingung.",
      ]},
    ],
    memory: "Harmonisch ist eine Schwingung, wenn die Rückstellgröße proportional und entgegengesetzt zur Auslenkung ist: a = −ω²s.",
    formulas: [
      { formula: "f = 1/T; ω = 2πf", meaning: "Zusammenhang der Zeitgrößen." },
      { formula: "s(t)=ŝ cos(ωt+φ₀)", meaning: "Allgemeine harmonische Schwingung." },
      { formula: "T_Feder = 2π√(m/D)", meaning: "Periodendauer des idealen Federpendels." },
      { formula: "T_Faden ≈ 2π√(l/g)", meaning: "Kleine Auslenkungen beim Fadenpendel." },
      { formula: "T_LC = 2π√(LC)", meaning: "Thomson-Formel des idealen LC-Kreises." },
    ],
    example: { title: "Federpendel und Energie", task: "m = 0,40 kg, D = 25 N/m, Amplitude 8,0 cm. Bestimme T und maximale Geschwindigkeit.", steps: ["Periodendauer: T = 2π√(m/D).", "Kreisfrequenz: ω = √(D/m).", "In der Ruhelage ist E_kin maximal: ½mv_max² = ½Dŝ².", "Damit v_max = ŝ√(D/m) = ωŝ."], result: "T = 0,795 s; v_max = 0,632 m/s" },
    flow: [{ label: "Auslenkung", detail: "s(t)" }, { label: "Rückstellwirkung", detail: "F = −Ds" }, { label: "DGL", detail: "s¨ = −ω²s" }, { label: "Energieaustausch", detail: "potentiell ↔ kinetisch" }],
    lab: { kind: "oscillation", title: "Schwingungs-Labor", intro: "Variiere Masse und Federkonstante. Prüfe die Wurzelabhängigkeit der Periodendauer." },
    experiment: { title: "T²-m-Linearisierung", question: "Gilt T = 2π√(m/D) für das verwendete Federpendel?", materials: "Feder, Massestücke, Stativ, Waage, Stoppuhr oder Bewegungssensor", steps: ["Bestimme D statisch aus F-s-Messwerten.", "Miss T für mindestens fünf Massen über je zehn Perioden.", "Trage T² gegen m auf.", "Bestimme D aus der Steigung und vergleiche."], evaluation: ["Berücksichtige die effektive Federmasse als Modellgrenze.", "Diskutiere Reaktionszeit bei Handmessung.", "Prüfe, ob die Gerade den Ursprung trifft."] },
    deepDive: { title: "Kleinwinkelnäherung beim Fadenpendel", text: "Die rücktreibende Komponente enthält sin θ. Erst für kleine Winkel darf sin θ ≈ θ gesetzt werden; dann wird die DGL linear und die Periodendauer amplitudenunabhängig. Bei großen Auslenkungen wächst T – das einfache Schulmodell zeigt seine Grenze." },
    exercises: [
      { id: "s1", title: "Schwingungsgrößen", level: "AFB I", prompt: "Eine Schwingung hat T = 0,80 s und Amplitude 4,5 cm. Bestimme f und ω und skizziere zwei Perioden von s(t)=ŝ cos(ωt)." },
      { id: "s2", title: "Phasenlagen", level: "AFB II · Heft", prompt: "Ergänze zu einem gegebenen s-t-Diagramm qualitativ passende v-t- und a-t-Diagramme. Begründe Nullstellen und Extremwerte." },
      { id: "s3", title: "Federpendel", level: "AFB II", prompt: "m = 0,60 kg, D = 48 N/m. Berechne T. Wie ändern sich T bei vierfacher Masse und vierfacher Federkonstante?" },
      { id: "s4", title: "Energieorte", level: "AFB II", prompt: "Für D = 30 N/m und ŝ = 0,10 m: Bestimme Gesamtenergie sowie E_pot und E_kin bei s = 0,060 m." },
      { id: "s5", title: "LC-Kreis", level: "AFB II", prompt: "L = 85 mH und C = 2,2 μF. Berechne T und f. Beschreibe die Energieverteilung bei maximaler Ladung und maximalem Strom." },
      { id: "s6", title: "Resonanz bewerten", level: "AFB III · Argumentation", prompt: "Beurteile: 'Resonanz tritt exakt dann auf, wenn Erreger- und Eigenfrequenz gleich sind, und ist immer gefährlich.' Berücksichtige Dämpfung, Amplitude, Energie und Anwendung." },
    ],
  },
  {
    slug: "wellen", title: "Wellen", area: "Mechanische Wellen", symbol: "λ", hours: 30,
    teaser: "Ausbreitung, Reflexion, Interferenz, stehende Wellen und Akustik.",
    lead: "Eine Welle transportiert Energie und Information, ohne Materie dauerhaft mitzunehmen. Superposition erklärt Interferenz, Reflexion und stehende Wellen.",
    tags: ["c = λf", "Interferenz", "stehende Wellen"], goals: ["Orts- und Zeitbilder unterscheiden", "Interferenzbedingungen anwenden", "Eigenfrequenzen und Akustik erklären"],
    theorySections: [
      { title: "Vom Oszillator zur Welle", paragraphs: [
        "Eine Welle entsteht, wenn gekoppelte Schwinger eine Störung weitergeben. Bei Transversalwellen steht die Schwingungsrichtung senkrecht, bei Longitudinalwellen parallel zur Ausbreitungsrichtung. Die Teilchen des Mediums schwingen um ihre Ruhelagen; das Wellenmuster und die Energie breiten sich weiter aus.",
        "Wellenlänge λ, Frequenz f und Ausbreitungsgeschwindigkeit c sind durch c = λf verknüpft. Die Frequenz wird von der Quelle bestimmt, die Geschwindigkeit vom Medium. Beim Übergang in ein anderes Medium bleibt f gleich, während c und damit λ sich ändern können.",
      ]},
      { title: "Wellengleichung, Reflexion und Superposition", paragraphs: [
        "Eine laufende harmonische Welle kann durch s(x,t)=ŝ sin(ωt−kx+φ₀) beschrieben werden. Hält man x fest, erhält man das Zeitdiagramm eines Ortes; hält man t fest, eine Momentaufnahme im Raum. Das Vorzeichen vor kx verrät die Ausbreitungsrichtung.",
        "An einem festen Ende wird ein Puls mit Phasensprung reflektiert, an einem losen ohne. Treffen Wellen zusammen, addieren sich die momentanen Auslenkungen. Nach der Überlagerung laufen die Einzelwellen im linearen Modell weiter. Konstruktive Interferenz entsteht bei passender, destruktive bei gegenphasiger Überlagerung.",
      ]},
      { title: "Stehende Wellen und Akustik", paragraphs: [
        "Eine stehende Welle entsteht durch Überlagerung zweier gleichfrequenter, entgegengesetzt laufender Wellen. Knoten bleiben in Ruhe, Bäuche schwingen mit maximaler Amplitude. Bei einer beidseitig festen Saite muss die Länge ein ganzzahliges Vielfaches von λ/2 enthalten.",
        "Die erlaubten Eigenfrequenzen f_n = n·c/(2L) bilden harmonische Obertöne. Bei Luftsäulen hängen Randbedingungen davon ab, ob ein Ende offen oder geschlossen ist. Klangfarbe wird nicht allein vom Grundton, sondern von Amplituden und Phasen der Obertöne bestimmt.",
      ]},
    ],
    memory: "Die Quelle legt f fest, das Medium c; daraus folgt λ = c/f. Materie schwingt lokal, Energie breitet sich aus.",
    formulas: [
      { formula: "c = λf", meaning: "Grundgleichung der Welle." },
      { formula: "s(x,t)=ŝ sin(ωt−kx+φ₀)", meaning: "Laufende Welle in +x-Richtung." },
      { formula: "k = 2π/λ", meaning: "Wellenzahl." },
      { formula: "Δs = mλ / (m+½)λ", meaning: "Konstruktive / destruktive Interferenz." },
      { formula: "f_n = n·c/(2L)", meaning: "Beidseitig feste Saite." },
    ],
    example: { title: "Eigenfrequenzen einer Saite", task: "Eine 0,65 m lange Saite hat Wellengeschwindigkeit 156 m/s. Bestimme Grundton und dritte Eigenfrequenz.", steps: ["Randbedingung: beide Enden fest, daher λₙ = 2L/n.", "Grundfrequenz f₁ = c/(2L).", "Die dritte Eigenfrequenz ist f₃ = 3f₁.", "Skizze: Für n = 3 liegen drei Halbwellen auf der Saite."], result: "f₁ = 120 Hz; f₃ = 360 Hz" },
    flow: [{ label: "Schwinger", detail: "Quelle mit f" }, { label: "Kopplung", detail: "Störung wandert" }, { label: "Superposition", detail: "Auslenkungen addieren" }, { label: "Muster", detail: "Interferenz / stehende Welle" }],
    lab: { kind: "wave", title: "Wellen-Labor", intro: "Verändere Frequenz und Wellenlänge. Prüfe, wie die Ausbreitungsgeschwindigkeit entsteht." },
    experiment: { title: "Stehende Welle auf einer Saite", question: "Welche Frequenzen erzeugen stabile Eigenmoden?", materials: "Schnur oder Saitenmelder, Erreger, Frequenzgenerator, Maßstab", steps: ["Halte Länge und Spannung konstant.", "Suche Grundmode und mindestens zwei höhere Moden.", "Miss Knotenabstände und bestimme λ.", "Berechne c = λf für jede Mode."], evaluation: ["Vergleiche die c-Werte.", "Skizziere Knoten und Bäuche.", "Erkläre Abweichungen durch Randbedingungen und Dämpfung."] },
    deepDive: { title: "Noise Cancelling ist lokale Interferenz", text: "Ein Kopfhörer erzeugt ein Signal mit möglichst entgegengesetzter Phase zum Störschall. Gute Auslöschung gelingt nur am Ort des Ohres und vor allem bei langsam veränderlichen, tiefen Geräuschen. Bei hohen Frequenzen und wechselnden Schallfeldern begrenzen Laufzeit und räumliche Unterschiede die Wirkung." },
    exercises: [
      { id: "wa1", title: "Wellenlänge", level: "AFB I/II", prompt: "Schall mit f = 680 Hz breitet sich mit 340 m/s aus. Bestimme λ. Was ändert sich beim Übergang in ein Medium mit c = 510 m/s?" },
      { id: "wa2", title: "Wellengleichung lesen", level: "AFB II", prompt: "Gegeben s(x,t)=0,030 m·sin[2π(t/0,50 s−x/1,20 m)]. Bestimme Amplitude, T, f, λ, c und Richtung." },
      { id: "wa3", title: "Reflexion", level: "AFB II · Zeichnung", prompt: "Zeichne vier zeitlich aufeinanderfolgende Bilder eines positiven Pulses bei Reflexion am festen und am losen Ende." },
      { id: "wa4", title: "Interferenz", level: "AFB II", prompt: "Zwei kohärente Quellen haben λ = 0,80 m. Klassifiziere Gangunterschiede 0,40 m, 1,60 m, 2,00 m und 2,80 m." },
      { id: "wa5", title: "Offenes Rohr", level: "AFB II", prompt: "Ein beidseitig offenes Rohr ist 0,85 m lang. Bestimme die ersten drei Eigenfrequenzen bei c = 340 m/s und skizziere die Druckknoten qualitativ." },
      { id: "wa6", title: "Energie oder Materie?", level: "AFB III · Argumentation", prompt: "Beurteile: 'Wenn eine Stadionwelle nach rechts läuft, bewegen sich die Menschen ebenfalls nach rechts.' Übertrage die Erklärung auf Schall und nenne Modellgrenzen." },
    ],
  },
  {
    slug: "wellenoptik", title: "Wellenoptik", area: "Licht als Welle", symbol: "α", hours: 20,
    teaser: "Huygens-Prinzip, Beugung, Doppelspalt, Gitter und Interferometer.",
    lead: "Beugung und Interferenz zeigen, wann das Strahlenmodell des Lichts nicht ausreicht. Aus geometrischen Mustern werden Wellenlängen und kleinste Wegänderungen messbar.",
    tags: ["Doppelspalt", "Gitter", "Interferometer"], goals: ["Huygens-Konstruktionen erklären", "Interferenzmuster quantitativ auswerten", "Lichtmodelle nach Gültigkeitsbereich auswählen"],
    theorySections: [
      { title: "Huygens-Prinzip und Modellwahl", paragraphs: [
        "Nach dem Huygens-Prinzip kann jeder Punkt einer Wellenfront als Ausgangspunkt einer Elementarwelle betrachtet werden. Die Einhüllende bildet die neue Wellenfront. Damit lassen sich Reflexion, Brechung und Beugung qualitativ als Ausbreitung von Wellenfronten verstehen.",
        "Das Strahlenmodell ist leistungsfähig, wenn Blenden und Gegenstände groß gegenüber der Wellenlänge sind. An schmalen Spalten oder feinen Strukturen wird Beugung sichtbar und das Wellenmodell notwendig. Modelle sind daher Werkzeuge mit Gültigkeitsbereichen, keine konkurrierenden Meinungen über dieselbe Situation.",
      ]},
      { title: "Doppelspalt, Gitter und Einzelspalt", paragraphs: [
        "Beim Doppelspalt überlagern sich kohärente Teilwellen. Helle Maxima entstehen bei Gangunterschied d·sin α = kλ. Für kleine Winkel gilt näherungsweise sin α ≈ tan α ≈ y/L, sodass der Streifenabstand proportional zu λ und Schirmabstand L, aber umgekehrt proportional zum Spaltabstand d ist.",
        "Ein optisches Gitter besitzt viele Spalte. Die Hauptmaxima liegen ebenfalls bei d·sin α = kλ, sind aber schmaler und intensiver als beim Doppelspalt. Beim Einzelspalt entstehen Minima bei b·sin α = kλ für k ≠ 0. Je kleiner der Spalt, desto breiter das zentrale Maximum – eine wichtige Modellbrücke zur Unbestimmtheit.",
      ]},
      { title: "Interferometer und dünne Schichten", paragraphs: [
        "Im Michelson-Interferometer teilt ein Strahlteiler Licht in zwei Wege und führt sie wieder zusammen. Verschiebt sich ein Spiegel um Δs, ändert sich der Hin- und Rückweg um 2Δs. Wandern m Interferenzstreifen vorbei, gilt 2Δs = mλ. So werden sehr kleine Längenänderungen messbar.",
        "Bei dünnen Schichten interferieren Teilwellen, die an verschiedenen Grenzflächen reflektiert werden. Neben dem geometrischen Weg können Phasensprünge bei Reflexion am optisch dichteren Medium entscheidend sein. Farbige Seifenhäute entstehen, weil die Interferenzbedingung von Wellenlänge, Dicke und Blickwinkel abhängt.",
      ]},
    ],
    memory: "Interferenzbedingungen beruhen auf Gangunterschieden; beim Auswerten müssen Geometrie, Näherung und mögliche Phasensprünge genannt werden.",
    formulas: [
      { formula: "d·sin α = kλ", meaning: "Hauptmaxima bei Doppelspalt und Gitter." },
      { formula: "b·sin α = kλ", meaning: "Minima des Einzelspalts, k ≠ 0." },
      { formula: "y_k ≈ kλL/d", meaning: "Kleinwinkelnäherung am Doppelspalt." },
      { formula: "2Δs = mλ", meaning: "Spiegelverschiebung im Michelson-Interferometer." },
    ],
    example: { title: "Laserwellenlänge am Gitter", task: "Gitterkonstante d = 10,0 μm, Schirmabstand L = 1,50 m, erstes Maximum bei y = 9,5 cm. Bestimme λ ohne Kleinwinkelnäherung.", steps: ["Geometrie: tan α = y/L, also α = arctan(0,095/1,50).", "Für k = 1 gilt λ = d·sin α.", "d = 10,0·10⁻⁶ m einsetzen.", "Prüfe, ob die Kleinwinkelnäherung ein ähnliches Ergebnis geliefert hätte."], result: "λ ≈ 632 nm" },
    flow: [{ label: "Kohärente Wege", detail: "feste Phasenbeziehung" }, { label: "Gangunterschied", detail: "Δs" }, { label: "Phase", detail: "2πΔs/λ" }, { label: "Intensität", detail: "hell / dunkel" }],
    lab: { kind: "optics", title: "Doppelspalt-Labor", intro: "Verändere λ, Spaltabstand und Schirmabstand. Beobachte den Streifenabstand." },
    experiment: { title: "Wellenlänge eines Lasers", question: "Wie genau lässt sich λ mit einem Gitter bestimmen?", materials: "Schullaser, Gitter, Schirm, Maßband, Sicherheitsregeln", steps: ["Miss d aus der angegebenen Linienzahl.", "Bestimme L und y für mehrere Ordnungen auf beiden Seiten.", "Berechne α geometrisch und λ für jede Ordnung.", "Mittle die Werte und schätze Unsicherheit."], evaluation: ["Prüfe die Kleinwinkelnäherung.", "Diskutiere Nullpunkt und Breite der Maxima.", "Beachte konsequent Lasersicherheit."] },
    deepDive: { title: "Warum tiefe Töne um Ecken hörbar sind", text: "Beugung ist stark, wenn Öffnung oder Hindernis nicht groß gegenüber λ ist. Schallwellen tiefer Frequenz besitzen lange Wellenlängen und werden an Türen und Gebäudekanten deutlich gebeugt. Sichtbares Licht hat viel kleinere Wellenlängen; Alltagsöffnungen sind dafür riesig, weshalb Schatten meist scharf erscheinen." },
    exercises: [
      { id: "o1", title: "Doppelspalt", level: "AFB I/II", prompt: "λ = 532 nm, d = 0,25 mm, L = 2,0 m. Berechne den Abstand benachbarter Maxima in Kleinwinkelnäherung." },
      { id: "o2", title: "Gitterordnung", level: "AFB II", prompt: "Ein Gitter besitzt 600 Linien/mm. Bestimme für λ = 633 nm den Winkel der ersten und zweiten Ordnung und prüfe, ob eine dritte möglich ist." },
      { id: "o3", title: "Einzelspalt", level: "AFB II", prompt: "Bei b = 0,080 mm und λ = 520 nm: Bestimme den Winkel des ersten Minimums und die Breite des zentralen Maximums auf einem 1,8 m entfernten Schirm." },
      { id: "o4", title: "Michelson", level: "AFB II", prompt: "Beim Verschieben eines Spiegels wandern 240 Streifen vorbei. λ = 632,8 nm. Bestimme Δs." },
      { id: "o5", title: "Modelle vergleichen", level: "AFB II · Heft", prompt: "Erstelle eine Tabelle: Phänomen, geeignetes Lichtmodell, Begründung, Modellgrenze für Schatten, Linse, Doppelspalt und Gitter." },
      { id: "o6", title: "Strahl oder Welle?", level: "AFB III · Argumentation", prompt: "Beurteile: 'Weil Licht am Doppelspalt interferiert, ist das Strahlenmodell falsch.' Formuliere eine differenzierte Aussage zum Gültigkeitsbereich beider Modelle." },
    ],
  },
  {
    slug: "photonen", title: "Photonen & Fotoeffekt", area: "Quantenphysik und Materie", symbol: "h", hours: 10,
    teaser: "Einstein-Gleichung, Energie, Impuls und de-Broglie-Wellenlänge.",
    lead: "Beim Fotoeffekt zeigt Licht einen quantenhaften Energieaustausch. Photonen tragen Energie und Impuls; Materieteilchen wiederum besitzen eine de-Broglie-Wellenlänge.",
    tags: ["Fotoeffekt", "Photon", "de Broglie"], goals: ["Fotoeffekt mit der Einstein-Gleichung auswerten", "Photonenenergie und -impuls berechnen", "Materiewellen quantitativ vergleichen"],
    theorySections: [
      { title: "Lichtelektrischer Effekt", paragraphs: [
        "Beim äußeren Fotoeffekt lösen Photonen Elektronen aus einer Metalloberfläche. Unterhalb einer materialabhängigen Grenzfrequenz treten keine Elektronen aus, selbst bei hoher Intensität. Oberhalb der Grenze wächst die maximale kinetische Energie linear mit der Frequenz, während höhere Intensität vor allem die Zahl ausgelöster Elektronen erhöht.",
        "Einstein deutete den Energieaustausch als einzelne Quantenprozesse. Jedes Photon besitzt E = hf und überträgt seine Energie an ein Elektron. Ein Teil wird für die Austrittsarbeit W_A benötigt; der Rest erscheint maximal als kinetische Energie. Die Gegenspannungsmethode bestimmt E_kin,max über eU_g.",
      ]},
      { title: "Photonenenergie und Impuls", paragraphs: [
        "Für Licht gilt E = hf = hc/λ. Kurzwelliges Licht trägt pro Photon mehr Energie. Ein Photon besitzt trotz verschwindender Ruhemasse den Impuls p = h/λ = E/c. Strahlungsdruck und Compton-Effekt zeigen, dass dieser Impuls physikalisch wirksam ist.",
        "Intensität und Photonenenergie dürfen nicht verwechselt werden. Bei monochromatischem Licht bedeutet größere Intensität mehr Photonen pro Zeit und Fläche. Erst eine Frequenzänderung verändert die Energie jedes einzelnen Photons.",
      ]},
      { title: "de-Broglie-Wellenlänge", paragraphs: [
        "de Broglie ordnete auch Materieteilchen eine Wellenlänge λ = h/p zu. Elektronen können daher an Kristallen gebeugt werden. Für nichtrelativistische Elektronen nach einer Beschleunigungsspannung U gilt p = √(2mₑeU) und somit λ = h/√(2mₑeU).",
        "Für Alltagskörper ist der Impuls so groß, dass die de-Broglie-Wellenlänge extrem klein und Interferenz nicht beobachtbar ist. Der Wellencharakter verschwindet nicht grundsätzlich, wird aber durch winzige Wellenlängen und Dekohärenz praktisch unzugänglich.",
      ]},
    ],
    memory: "Frequenz bestimmt die Energie eines Photons; Intensität bestimmt bei gleicher Frequenz vor allem die Photonenzahl.",
    formulas: [
      { formula: "E_kin,max = hf − W_A", meaning: "Einstein-Gleichung des Fotoeffekts." },
      { formula: "E_kin,max = eU_g", meaning: "Gegenspannungsmethode." },
      { formula: "Eγ = hf = hc/λ", meaning: "Photonenenergie." },
      { formula: "pγ = h/λ", meaning: "Photonenimpuls." },
      { formula: "λ_dB = h/p", meaning: "de-Broglie-Wellenlänge." },
    ],
    example: { title: "Austrittsarbeit aus Messdaten", task: "Bei f = 8,0·10¹⁴ Hz wird U_g = 1,15 V gemessen. Bestimme W_A in eV.", steps: ["Photonenenergie in eV: Eγ = hf und anschließend durch e teilen.", "Maximale kinetische Energie in eV entspricht numerisch U_g in Volt: 1,15 eV.", "W_A = Eγ − E_kin,max.", "Prüfe: W_A muss positiv und materialtypisch im Bereich einiger eV sein."], result: "W_A ≈ 2,16 eV" },
    flow: [{ label: "Photon", detail: "E = hf" }, { label: "Material", detail: "Austrittsarbeit W_A" }, { label: "Elektron", detail: "E_kin,max" }, { label: "Messung", detail: "Gegenspannung U_g" }],
    lab: { kind: "photoelectric", title: "Fotoeffekt-Labor", intro: "Verändere Frequenz und Austrittsarbeit. Beobachte Grenzfrequenz und maximale Elektronenenergie." },
    experiment: { title: "Einstein-Gerade auswerten", question: "Wie lassen sich h und W_A aus U_g(f) bestimmen?", materials: "Vorbereiteter Datensatz oder Fotoeffekt-Simulation, Diagrammpapier", steps: ["Trage eU_g gegen f auf.", "Bestimme die Steigung der Ausgleichsgeraden.", "Bestimme Grenzfrequenz und Achsenabschnitt.", "Vergleiche h mit dem Literaturwert."], evaluation: ["Ordne Einheiten der Steigung zu.", "Diskutiere Kontaktpotentiale und Ableseunsicherheit.", "Erkläre, warum Intensität die Gerade nicht steiler macht."] },
    deepDive: { title: "Welle und Photon sind keine kleinen klassischen Bilder", text: "Das Wellenmodell beschreibt Ausbreitung und Interferenz; das Photonmodell quantisierte Wechselwirkungen. Ein Photon ist weder einfach ein winziges Kügelchen noch ein klassisches Wellenpaket mit eindeutigem Weg. Welche Beschreibung trägt, hängt von Versuch und Fragestellung ab." },
    exercises: [
      { id: "ph1", title: "Photonenenergie", level: "AFB I/II", prompt: "Berechne Energie in J und eV sowie Impuls eines Photons mit λ = 450 nm." },
      { id: "ph2", title: "Grenzfrequenz", level: "AFB II", prompt: "Ein Metall hat W_A = 2,30 eV. Bestimme Grenzfrequenz und Grenzwellenlänge." },
      { id: "ph3", title: "Gegenspannung", level: "AFB II", prompt: "λ = 365 nm, W_A = 2,10 eV. Berechne maximale kinetische Energie und Gegenspannung." },
      { id: "ph4", title: "Einstein-Gerade", level: "AFB II · Heft", prompt: "Skizziere U_g gegen f für zwei Metalle mit unterschiedlicher Austrittsarbeit. Markiere gemeinsame Steigung und unterschiedliche Grenzfrequenzen." },
      { id: "ph5", title: "Materiewelle", level: "AFB II", prompt: "Berechne λ_dB eines Elektrons nach 150 V klassisch und vergleiche mit einer Gitterkonstante von 0,20 nm." },
      { id: "ph6", title: "Intensitätsbehauptung", level: "AFB III · Argumentation", prompt: "Beurteile: 'Helleres Licht schlägt Elektronen mit größerer Energie aus dem Metall.' Trenne Photonenergie, Photonenzahl, Grenzfrequenz und Messgröße." },
    ],
  },
  {
    slug: "quantenobjekte", title: "Quantenobjekte", area: "Quantenphysik und Materie", symbol: "ψ", hours: 14,
    teaser: "Einzelquanten, Komplementarität, Unbestimmtheit und Verschränkung.",
    lead: "Quantenobjekte erzeugen einzelne Treffer und zugleich statistische Interferenzmuster. Die Quantentheorie sagt Wahrscheinlichkeiten voraus – nicht verborgene klassische Bahnen.",
    tags: ["Doppelspalt", "Unbestimmtheit", "Verschränkung"], goals: ["Einzelereignis und Verteilung unterscheiden", "Komplementarität argumentativ erklären", "Aussagen zu Unbestimmtheit und Verschränkung prüfen"],
    theorySections: [
      { title: "Einzelquanten am Doppelspalt", paragraphs: [
        "Werden Photonen oder Elektronen einzeln auf einen Doppelspalt geschickt, registriert der Schirm punktförmige Treffer. Nach vielen Ereignissen entsteht jedoch eine Interferenzverteilung. Das einzelne Ereignis ist nicht vorhersagbar; die Quantentheorie liefert mit |ψ|² eine Wahrscheinlichkeitsdichte für mögliche Ergebnisse.",
        "Es ist irreführend, jedem Teilchen ungeprüft eine klassische Bahn durch genau einen Spalt zuzuschreiben. Solange die Versuchsanordnung beide Wege kohärent zulässt, müssen die Wahrscheinlichkeitsamplituden beider Möglichkeiten überlagert werden. Das Interferenzmuster entsteht nicht durch Zusammenstöße verschiedener Teilchen.",
      ]},
      { title: "Komplementarität und Welcher-Weg-Information", paragraphs: [
        "Interferenz und eindeutige Welcher-Weg-Information sind komplementäre Versuchsaussagen. Wird die Anordnung so verändert, dass der Weg prinzipiell unterscheidbar wird, sinkt die Interferenzsichtbarkeit. Entscheidend ist nicht das menschliche Hinschauen, sondern die physikalische Verfügbarkeit der Information und die dadurch entstehende Korrelation mit einem Messsystem.",
        "Delayed-Choice- und Quantenradierer-Versuche bedeuten nicht, dass die Zukunft die Vergangenheit umschreibt. Sie zeigen, dass klassische Erzählungen eines schon vorher festgelegten Weges ungeeignet sind. Ausgewertet werden Korrelationen zwischen gemeinsam registrierten Ereignissen unter verschiedenen Messbedingungen.",
      ]},
      { title: "Unbestimmtheit und Verschränkung", paragraphs: [
        "Die Heisenbergsche Unbestimmtheitsrelation verbindet Streuungen komplementärer Größen, etwa Δx und Δp_x. Sie beschreibt keine bloße Ungeschicklichkeit des Messenden. Ein stark räumlich lokalisiertes Wellenpaket benötigt viele Impulskomponenten und besitzt daher eine große Impulsstreuung.",
        "Verschränkte Systeme besitzen gemeinsame Zustände, die nicht in unabhängige Einzelzustände zerlegt werden können. Messungen zeigen stärkere Korrelationen, als lokale klassische Modelle mit vorab festgelegten Eigenschaften erlauben. Dennoch können die einzelnen Ergebnisse nicht zur überlichtschnellen Nachrichtenübertragung gesteuert werden.",
      ]},
    ],
    memory: "Die Quantentheorie sagt Verteilungen vieler gleichartig präparierter Ereignisse voraus; das Einzelereignis bleibt grundsätzlich probabilistisch.",
    formulas: [
      { formula: "P(x) ∝ |ψ(x)|²", meaning: "Wahrscheinlichkeitsdichte einer Ortsmessung." },
      { formula: "ψ_ges = ψ₁ + ψ₂", meaning: "Überlagerung von Wahrscheinlichkeitsamplituden." },
      { formula: "Δx·Δp_x ≥ ħ/2", meaning: "Unbestimmtheitsrelation in Standardform." },
      { formula: "V² + D² ≤ 1", meaning: "Qualitativer Zusammenhang von Sichtbarkeit und Wegunterscheidbarkeit." },
    ],
    example: { title: "Minimale Impulsstreuung", task: "Ein Elektron wird auf Δx = 0,20 nm lokalisiert. Schätze die minimale Impuls- und Geschwindigkeitsstreuung.", steps: ["Unbestimmtheit: Δp_x ≥ ħ/(2Δx).", "Δx = 2,0·10⁻¹⁰ m einsetzen.", "Nichtrelativistisch Δv_x ≈ Δp_x/mₑ.", "Das Ergebnis ist eine Untergrenze der Streuung, kein gerichteter Impuls."], result: "Δp_x,min ≈ 2,64·10⁻²⁵ kg·m/s; Δv_x,min ≈ 2,90·10⁵ m/s" },
    flow: [{ label: "Präparation", detail: "gleiche Anfangsbedingungen" }, { label: "Amplituden", detail: "ψ₁ + ψ₂" }, { label: "Messung", detail: "ein einzelner Treffer" }, { label: "Statistik", detail: "|ψ|²-Verteilung" }],
    lab: { kind: "uncertainty", title: "Unbestimmtheits-Labor", intro: "Verkleinere die Ortsbreite. Beobachte die theoretische Untergrenze der Impulsstreuung." },
    experiment: { title: "Einzeltreffer simulieren", question: "Wie entsteht aus Zufallsereignissen eine stabile Interferenzverteilung?", materials: "Doppelspalt-Simulation mit Einzelteilchenmodus, Protokollbogen", steps: ["Erfasse zunächst 20 Treffer und beschreibe das Bild.", "Erhöhe auf 200 und 2000 Treffer.", "Vergleiche einen offenen Spalt, zwei offene Spalte und Wegmarkierung.", "Trenne Einzelvorhersage und Verteilungsvorhersage."], evaluation: ["Erkläre, warum keine Einzelbahn abgelesen wird.", "Beschreibe den Einfluss von Welcher-Weg-Information.", "Vermeide Aussagen über menschliches Bewusstsein als Ursache."] },
    deepDive: { title: "'Spukhafte Fernwirkung' sorgfältig einordnen", text: "Verschränkung erzeugt nichtlokale Korrelationen, aber kein steuerbares Signal schneller als Licht. Erst der spätere klassische Vergleich der Messlisten macht die Korrelation sichtbar. Populäre Formulierungen müssen diese beiden Aussagen auseinanderhalten." },
    exercises: [
      { id: "q1", title: "Einzelereignis und Muster", level: "AFB I/II", prompt: "Erkläre in je zwei Sätzen, was am Schirm bei einem einzelnen Elektron und nach sehr vielen Elektronen vorhergesagt werden kann." },
      { id: "q2", title: "Drei Modelle", level: "AFB II · Heft", prompt: "Vergleiche klassisches Teilchen, klassische Welle und Quantenobjekt am Doppelspalt hinsichtlich Einzelereignis, Interferenz und Bahnbegriff." },
      { id: "q3", title: "Welcher Weg", level: "AFB II", prompt: "Beschreibe, wie eine Wegmarkierung die Interferenz beeinflusst. Unterscheide Wechselwirkung, Information und Auswertung." },
      { id: "q4", title: "Unbestimmtheit", level: "AFB II", prompt: "Berechne Δp_min für Δx = 1,0 μm und 0,10 nm. Vergleiche und deute die Größenordnung." },
      { id: "q5", title: "Delayed Choice", level: "AFB II/III", prompt: "Formuliere eine fachlich korrekte Alternative zur Aussage: 'Das Photon entscheidet sich rückwirkend, welchen Weg es genommen hat.'" },
      { id: "q6", title: "Fernwirkung beurteilen", level: "AFB III · Argumentation", prompt: "Beurteile: 'Mit Verschränkung kann man sofort Nachrichten zu einem fernen Ort senden.' Trenne Korrelation, Steuerbarkeit, Einzelmessung und klassischen Vergleich." },
    ],
  },
  {
    slug: "atomphysik", title: "Atomphysik & Röntgenstrahlung", area: "Quantenphysik und Materie", symbol: "Eₙ", hours: 12,
    teaser: "Linienspektren, Potentialtopf, Atommodelle und Röntgenspektren.",
    lead: "Gebundene Quantensysteme besitzen diskrete Energien. Spektren werden dadurch zu Fingerabdrücken von Atomen, während Röntgenstrahlung Übergänge und Beschleunigungsprozesse sichtbar macht.",
    tags: ["Energieniveaus", "Spektren", "Potentialtopf"], goals: ["Spektrallinien Energiedifferenzen zuordnen", "Potentialtopf als Modell anwenden", "Röntgenspektren und Atommodelle deuten"],
    theorySections: [
      { title: "Linienspektren und Wasserstoff", paragraphs: [
        "Atome emittieren und absorbieren Licht nur bei bestimmten Frequenzen. Eine Spektrallinie entspricht einer Energiedifferenz ΔE = hf zwischen zwei erlaubten Zuständen. Beim Wasserstoffatom lassen sich die Energien im Coulombfeld näherungsweise durch E_n = −13,6 eV/n² beschreiben. Der Nullpunkt liegt beim freien Elektron im Unendlichen.",
        "Bei Emission fällt das Atom auf ein niedrigeres Niveau und gibt ein Photon ab; bei Absorption nimmt es ein Photon passender Energie auf. Ein Spektrum erlaubt daher Rückschlüsse auf das Element. Linienbreite, Doppler-Effekt und Wechselwirkungen können reale Linien verbreitern oder verschieben.",
      ]},
      { title: "Potentialtopf und Pauli-Prinzip", paragraphs: [
        "Der unendlich tiefe eindimensionale Potentialtopf ist ein stark vereinfachtes Modell für ein gebundenes Teilchen. Nur stehende Materiewellen, die zu den Randbedingungen passen, sind erlaubt. Daraus folgen diskrete Energien E_n = n²h²/(8mL²). Mit kleinerer Topfbreite wachsen die Energieabstände stark.",
        "Das Modell erklärt Quantisierung anschaulich, bildet ein reales Atom aber nicht vollständig ab. In Atomen sind dreidimensionale Orbitale, Coulombpotential, Spin und Elektronenwechselwirkung wichtig. Das Pauli-Prinzip besagt, dass zwei Elektronen eines Atoms nicht in allen Quantenzahlen übereinstimmen dürfen und strukturiert so die Elektronenhülle.",
      ]},
      { title: "Röntgenspektrum", paragraphs: [
        "In einer Röntgenröhre werden Elektronen durch eine Spannung U beschleunigt und am Anodenmaterial abgebremst. Die Bremsstrahlung bildet ein kontinuierliches Spektrum. Die maximale Photonenenergie eU führt zur Grenzwellenlänge λ_min = hc/(eU). Größere Spannung verschiebt diese Grenze zu kleineren Wellenlängen.",
        "Zusätzlich erscheinen charakteristische Linien, wenn innere Elektronen aus Atomen geschlagen werden und Elektronen aus höheren Schalen die Lücke füllen. Ihre Energien hängen vom Anodenmaterial ab. Spannung, Stromstärke und Material beeinflussen also verschiedene Merkmale des Spektrums.",
      ]},
    ],
    memory: "Spektrallinien zeigen Energiedifferenzen, nicht direkt die absoluten Energieniveaus. Jedes Atommodell hat einen begrenzten Erklärungsbereich.",
    formulas: [
      { formula: "ΔE = hf = hc/λ", meaning: "Energiedifferenz und Spektrallinie." },
      { formula: "E_n(H) = −13,6 eV/n²", meaning: "Wasserstoffniveaus." },
      { formula: "E_n(Topf)=n²h²/(8mL²)", meaning: "Unendlich tiefer Potentialtopf." },
      { formula: "eU = hc/λ_min", meaning: "Grenzwellenlänge der Bremsstrahlung." },
    ],
    example: { title: "Balmer-Übergang", task: "Bestimme die Wellenlänge beim Wasserstoffübergang n = 3 nach n = 2.", steps: ["E₂ = −13,6 eV/4, E₃ = −13,6 eV/9.", "Photonenenergie ist der positive Betrag ΔE = E₃ − E₂.", "λ = hc/ΔE; ΔE vorher in Joule umrechnen oder hc = 1240 eV·nm verwenden.", "Das Ergebnis liegt im sichtbaren roten Bereich."], result: "λ ≈ 656 nm" },
    flow: [{ label: "Gebundener Zustand", detail: "diskretes Eₙ" }, { label: "Übergang", detail: "ΔE" }, { label: "Photon", detail: "hf = ΔE" }, { label: "Spektrum", detail: "Element-Fingerabdruck" }],
    lab: { kind: "atom", title: "Energieniveau-Labor", intro: "Wähle Anfangs- und Endniveau des Wasserstoffatoms. Berechne Energie und Wellenlänge des Photons." },
    experiment: { title: "Spektrallampe untersuchen", question: "Lässt sich ein unbekanntes Gas anhand seiner Linien identifizieren?", materials: "Spektrallampe, Gitter oder Spektrometer, Vergleichsspektren", steps: ["Kalibriere die Winkelskala mit einer bekannten Linie.", "Miss mehrere Linien des unbekannten Gases.", "Berechne Wellenlängen und Photonenenergien.", "Vergleiche mit Referenzspektren."], evaluation: ["Berücksichtige Messunsicherheit und Linienbreite.", "Begründe die Stoffzuordnung mit mehreren Linien.", "Beachte Sicherheitsregeln für Spektrallampen."] },
    deepDive: { title: "Warum Orbitale keine Elektronenbahnen sind", text: "Ein Orbital beschreibt einen Quantenzustand und eine räumliche Wahrscheinlichkeitsverteilung. Es ist keine klassische Umlaufbahn wie bei einem Planeten. Das Bohrsche Bahnmodell kann Energien des Wasserstoffs teilweise ordnen, versagt aber für viele andere Eigenschaften und Mehrelektronenatome." },
    exercises: [
      { id: "a1", title: "Wasserstoffniveau", level: "AFB I/II", prompt: "Berechne E₁, E₂ und E₄ in eV. Bestimme die Ionisierungsenergie aus n = 2." },
      { id: "a2", title: "Spektrallinie", level: "AFB II", prompt: "Bestimme Energie, Frequenz und Wellenlänge des Übergangs n = 4 nach n = 2 im Wasserstoffatom." },
      { id: "a3", title: "Potentialtopf", level: "AFB II", prompt: "Ein Elektron befindet sich in einem unendlich tiefen Topf der Breite 0,50 nm. Berechne E₁ und das Verhältnis E₃/E₁." },
      { id: "a4", title: "Röntgengrenze", level: "AFB II", prompt: "Eine Röntgenröhre arbeitet bei 35 kV. Bestimme λ_min. Wie ändert sich λ_min bei 70 kV?" },
      { id: "a5", title: "Spektrum deuten", level: "AFB II · Heft", prompt: "Skizziere ein Röntgenspektrum mit Kontinuum, Grenzwellenlänge und zwei charakteristischen Linien. Beschreibe den Einfluss von Spannung und Anodenmaterial." },
      { id: "a6", title: "Atommodell bewerten", level: "AFB III · Argumentation", prompt: "Beurteile: 'Elektronen umkreisen den Kern wie Planeten die Sonne.' Nenne Erklärungsleistung, Widersprüche und eine fachlich bessere Modellvorstellung." },
    ],
  },
  {
    slug: "laserprojekt", title: "Vertiefung: Laserphysik", area: "Vertiefendes Themengebiet", symbol: "LASER", hours: 8,
    teaser: "Besetzungsinversion, Resonator, Anwendungen, Nutzen und Risiken.",
    lead: "Der Laser verknüpft Energieniveaus, stimulierte Emission, optischen Resonator und technische Systementwicklung. Dieses Kapitel eignet sich als selbstständige Projektphase.",
    tags: ["stimulierte Emission", "Resonator", "Projekt"], goals: ["Laserfunktion als Prozesskette erklären", "eine Anwendung fachlich recherchieren", "Nutzen, Risiko und Modellgrenzen bewerten"],
    theorySections: [
      { title: "Absorption, spontane und stimulierte Emission", paragraphs: [
        "Ein Atom kann ein Photon absorbieren, wenn dessen Energie zu einer Energiedifferenz passt. Ein angeregter Zustand kann spontan zerfallen; Zeitpunkt und Richtung des emittierten Photons sind dabei nicht festgelegt. Bei stimulierter Emission löst ein passendes Photon den Übergang aus. Das neue Photon stimmt in Frequenz, Phase, Ausbreitungsrichtung und Polarisation mit dem auslösenden überein.",
        "Damit Verstärkung statt überwiegender Absorption entsteht, müssen mehr Teilchen im geeigneten angeregten Zustand als im unteren Laserniveau sein. Dieser Nichtgleichgewichtszustand heißt Besetzungsinversion und wird durch Pumpen erzeugt, etwa optisch oder elektrisch. Ein einfaches Zweiniveausystem reicht dafür im stationären Betrieb meist nicht aus.",
      ]},
      { title: "Aktives Medium und Resonator", paragraphs: [
        "Das aktive Medium stellt die Energieniveaus bereit. Zwei Spiegel bilden einen optischen Resonator. Licht läuft vielfach durch das Medium und wird durch stimulierte Emission verstärkt. Nur Resonatormoden, die Randbedingungen und Verstärkungsbereich erfüllen, können anwachsen.",
        "Ein Spiegel ist teilweise durchlässig und koppelt einen Teil des Lichts als Laserstrahl aus. Verstärkung muss die Verluste übersteigen. Der Resonator sorgt für Richtungsauswahl und hohe Kohärenz; reale Laser sind dennoch nicht perfekt monochromatisch oder unendlich scharf gebündelt.",
      ]},
      { title: "Anwendungen und Sicherheit", paragraphs: [
        "Laser werden in Medizin, Kommunikation, Messtechnik, Materialbearbeitung, Datenspeicherung und Forschung eingesetzt. Die geeignete Wellenlänge, Leistung, Pulsdauer und Strahlqualität hängen von der Anwendung ab. Eine medizinische Wirkung kann durch Absorption in ausgewähltem Gewebe entstehen, eine Messanwendung durch Interferenz oder Laufzeit.",
        "Risiken hängen nicht nur von sichtbarer Helligkeit ab. Unsichtbare Laserstrahlung kann besonders gefährlich sein; das Auge kann Strahlung auf die Netzhaut fokussieren. Sicherheitsbewertung verlangt Laserklasse, Wellenlänge, Leistung, Expositionszeit, Strahlweg und Schutzmaßnahmen.",
      ]},
    ],
    memory: "Laserbetrieb braucht Pumpen, Besetzungsinversion, stimulierte Emission, Rückkopplung im Resonator und Verstärkung oberhalb der Verluste.",
    formulas: [
      { formula: "ΔE = hf", meaning: "Photonenenergie des Laserübergangs." },
      { formula: "λ = hc/ΔE", meaning: "Wellenlänge aus Energiedifferenz." },
      { formula: "2L = mλ", meaning: "Vereinfachte Resonanzbedingung im linearen Resonator." },
      { formula: "Verstärkung > Verluste", meaning: "Schwellenbedingung für Laserbetrieb." },
    ],
    example: { title: "Laserwellenlänge", task: "Der Laserübergang besitzt ΔE = 1,96 eV. Bestimme die Wellenlänge und ordne den Spektralbereich zu.", steps: ["Nutze λ = hc/ΔE.", "Mit hc = 1240 eV·nm kann direkt in eV gerechnet werden.", "λ = 1240 eV·nm / 1,96 eV.", "Die Wellenlänge liegt im sichtbaren roten Bereich."], result: "λ ≈ 633 nm" },
    flow: [{ label: "Pumpen", detail: "Energie zuführen" }, { label: "Inversion", detail: "angeregte Mehrheit" }, { label: "Stimulieren", detail: "kohärente Photonen" }, { label: "Resonator", detail: "verstärken & auskoppeln" }],
    lab: { kind: "laser", title: "Laserübergangs-Labor", intro: "Verändere die Energiedifferenz und ordne die entstehende Wellenlänge dem Spektrum zu." },
    experiment: { title: "Projektauftrag: Laseranwendung", question: "Wie wird eine ausgewählte Laseranwendung physikalisch möglich und verantwortungsvoll eingesetzt?", materials: "Mindestens drei belastbare Quellen, Demonstration oder Simulation, Poster/Präsentation", steps: ["Wähle Anwendung und präzise Leitfrage.", "Erstelle Funktionsschema vom Pumpen bis zur Wirkung.", "Recherchiere typische Wellenlänge, Leistung und Betriebsart.", "Entwickle eine Demonstration, Simulation oder Datenauswertung."], evaluation: ["Trenne gesicherte Quelle und Werbeaussage.", "Bewerte Nutzen, Risiko und Alternativen.", "Verteidige Modellgrenzen in einer Rückfrage."] },
    deepDive: { title: "Projektprodukt", text: "Erwartet werden ein physikalisches Funktionsschema, mindestens eine quantitative Rechnung, eine geprüfte Quelle, eine Risiko-Nutzen-Abwägung und ein sichtbarer Modellgrenzen-Abschnitt. Eine reine Sammlung schöner Laserbilder reicht nicht." },
    exercises: [
      { id: "l1", title: "Übergangsenergie", level: "AFB I/II", prompt: "Bestimme ΔE in eV für Laserlicht mit 532 nm und 1064 nm." },
      { id: "l2", title: "Resonatormoden", level: "AFB II", prompt: "Ein vereinfachter Resonator ist 30,0 cm lang. Schätze den Frequenzabstand benachbarter longitudinaler Moden mit Δf = c/(2L)." },
      { id: "l3", title: "Prozesskette", level: "AFB II · Heft", prompt: "Zeichne eine Prozesskette aus Pumpen, Besetzungsinversion, stimulierter Emission, Resonator und Auskopplung. Ergänze Energieflüsse." },
      { id: "l4", title: "Laser oder LED", level: "AFB II", prompt: "Vergleiche Laser und LED hinsichtlich Emission, Spektrum, Kohärenz, Richtung und typischer Anwendung." },
      { id: "l5", title: "Quellencheck", level: "AFB II/III", prompt: "Wähle zwei Internetquellen zu einer Laseranwendung. Prüfe Autorität, Belege, Aktualität, Zweck und Widersprüche. Dokumentiere dein Urteil." },
      { id: "l6", title: "Nutzen und Risiko", level: "AFB III · Argumentation", prompt: "Bewerte den Einsatz eines Lasers in Medizin oder Industrie. Nutze Physik, Nutzen, Risiken, Schutzmaßnahmen, Alternativen und ein abgewogenes Urteil." },
    ],
  },
  {
    slug: "abiturtraining", title: "Abiturtraining", area: "Vernetzung & Prüfung", symbol: "A", hours: 34,
    teaser: "Operatoren, vernetzte Aufgaben, Experimentinterpretation und Fehlerstrategien.",
    lead: "Im Abitur werden bekannte Ideen in neuen Zusammenhängen geprüft. Entscheidend sind strukturierte Lösungswege, präzise Operatorenbearbeitung und begründete Modellentscheidungen.",
    tags: ["Operatoren", "Materialaufgaben", "Fehleranalyse"], goals: ["mehrteilige Aufgaben planvoll bearbeiten", "Experimente und Diagramme auswerten", "AFB-III-Urteile strukturiert formulieren"],
    theorySections: [
      { title: "Operatoren als Arbeitsaufträge", paragraphs: [
        "'Nennen' verlangt eine knappe Angabe, 'beschreiben' eine geordnete Darstellung, 'erklären' eine kausale Verknüpfung mit Modell oder Gesetz. 'Begründen' fordert tragende Gründe; 'beurteilen' ein Sachurteil anhand fachlicher Kriterien; 'bewerten' bezieht zusätzlich offengelegte Werte oder Interessen ein. Eine gute Antwort passt Tiefe und Form an den Operator an.",
        "Bei Materialaufgaben werden Informationen nicht ungeprüft abgeschrieben. Zuerst wird markiert, welche Daten, Diagramme oder Aussagen zur Teilaufgabe gehören. Danach wird das passende Modell gewählt. Jede Rechnung endet mit Einheit und Deutung im Kontext; jedes Urteil greift die konkrete Behauptung oder Entscheidung auf.",
      ]},
      { title: "Lösestrategie für mehrteilige Aufgaben", paragraphs: [
        "Ein belastbarer Ablauf lautet: Situation und Systemgrenze skizzieren; Gegebenes und Gesuchtes notieren; physikalischen Ansatz begründen; symbolisch umstellen; SI-Einheiten einsetzen; Ergebnis prüfen; Antwortsatz und Modellgrenze formulieren. Frühere Teilergebnisse dürfen genutzt werden, müssen aber plausibel kontrolliert werden.",
        "Diagramme werden aktiv gelesen: Achsen, Einheit, Skalierung, charakteristische Punkte, Steigung, Fläche und Unsicherheit. Ein Versuchsaufbau wird über Funktion der Bauteile, unabhängige und abhängige Größe, Konstanten, Messprinzip und Fehlerquellen analysiert. Die Erklärung soll nicht nur den Aufbau nacherzählen.",
      ]},
      { title: "Fehleranalyse und Prüfungskommunikation", paragraphs: [
        "Fehler lassen sich in Kategorien ordnen: Modellfehler, falscher Ansatz, Algebrafehler, Einheit, Vorzeichen/Richtung, Rundung und unvollständige Kommunikation. Wer nur die richtige Zahl vergleicht, lernt weniger als jemand, der die Fehlerursache identifiziert und eine Gegenstrategie festlegt.",
        "Unter Zeitdruck hilft eine Punkte- und Zeitplanung. Zunächst werden sichere Teilaufgaben bearbeitet, anspruchsvolle Stellen markiert und später zurückgeholt. Auch bei Unsicherheit lohnt ein sauberer Ansatz: Skizze, Gesetz, Größenbeziehung und qualitative Folgerung können Teilpunkte sichern. Lesbare Fachsprache ist Teil der Leistung.",
      ]},
    ],
    memory: "Ein starkes Abiturergebnis entsteht aus fachlichem Modell, sichtbarem Lösungsweg, Einheitenkontrolle, Kontextdeutung und passender Operatorenantwort.",
    formulas: [
      { formula: "Skizze → Ansatz → Rechnung → Deutung", meaning: "Grundstruktur quantitativer Aufgaben." },
      { formula: "Behauptung → Kriterium → Evidenz → Grenze → Urteil", meaning: "Grundstruktur einer AFB-III-Argumentation." },
      { formula: "Steigung = Δy/Δx", meaning: "Immer mit physikalischer Einheit deuten." },
      { formula: "Fläche ≈ Σ Größe·Δx", meaning: "Diagrammflächen als akkumulierte Größe." },
    ],
    example: { title: "Unbekannten Aufbau erschließen", task: "Ein Diagramm zeigt eine lineare Abhängigkeit F(q) mit Steigung 2,4·10³ N/C. Deute Aufbau, Ergebnis und Grenze.", steps: ["Achsenanalyse: F gegen q; die Steigung hat N/C.", "Mit E = F/q ist die Steigung die elektrische Feldstärke.", "Ein möglicher Aufbau hält den Messort im Feld konstant und variiert die Probeladung.", "Grenzen: Probeladung darf das Feld nicht merklich verändern; Nullpunkt und Streuung beachten."], result: "E = 2,4 kN/C; lineares Feldmodell am festen Messort" },
    flow: [{ label: "Lesen", detail: "Operator & Material" }, { label: "Planen", detail: "Modell & Teilziele" }, { label: "Lösen", detail: "sichtbarer Fachweg" }, { label: "Prüfen", detail: "Einheit, Plausibilität, Urteil" }],
    lab: { kind: "exam", title: "Punkte-Zeit-Labor", intro: "Plane eine 300-Minuten-Klausur. Verteile Arbeits- und Kontrollzeit auf Aufgaben mit unterschiedlichen Punkten." },
    experiment: { title: "Mündliche Experimentinterpretation", question: "Wie lässt sich ein unbekannter Aufbau in fünf Minuten fachlich erschließen?", materials: "Foto oder realer Aufbau, Messdiagramm, Timer, Feedbackbogen", steps: ["Beschreibe den sichtbaren Aufbau ohne Deutung.", "Formuliere Messfrage und Hypothese.", "Ordne Diagramm und passende Formel zu.", "Nenne Ergebnis, Fehlerquelle und Modellgrenze."], evaluation: ["Nutze Fachbegriffe präzise.", "Trenne Beobachtung und Erklärung.", "Überarbeite die Antwort nach Peer-Feedback."] },
    deepDive: { title: "Fehlerkonferenz statt Punktesammeln", text: "Nach einer Probeklausur ordnest du jeden verlorenen Punkt einer Fehlerkategorie zu und formulierst eine konkrete Gegenstrategie. Beispiel: 'Einheit vergessen' wird nicht mit 'besser aufpassen', sondern mit 'vor dem Einsetzen alle Größen in einer Gegeben/Gesucht-Zeile in SI umrechnen' beantwortet." },
    exercises: [
      { id: "ab1", title: "Operatoren unterscheiden", level: "AFB I/II", prompt: "Formuliere zum Thema Induktion je eine passende Antwortstruktur für beschreiben, erklären, begründen, beurteilen und bewerten." },
      { id: "ab2", title: "Einheitencheck", level: "AFB II", prompt: "Prüfe durch Dimensionsanalyse: r = mv/(qB), T = 2π√(LC), E = ½CU² und λ = h/p." },
      { id: "ab3", title: "Diagrammdeutung", level: "AFB II · Heft", prompt: "Entwirf einen vollständigen Auswertetext zu einem exponentiellen U-t-Diagramm: Anfangswert, Endwert, τ, Steigung, Modell und Abweichungen." },
      { id: "ab4", title: "Fehlerlösung verbessern", level: "AFB II", prompt: "Eine Lösung endet mit v = 4,2·10⁹ m/s. Erkläre mindestens drei Prüfungen, die den Fehler sichtbar machen, und entwickle den nächsten Modellschritt." },
      { id: "ab5", title: "Experiment mündlich", level: "AFB II/III", prompt: "Wähle einen Kursversuch. Erstelle einen fünfminütigen Sprechplan: Beobachtung, Modell, Formel, Auswertung, Fehler, Grenze." },
      { id: "ab6", title: "Materialbehauptung", level: "AFB III · Argumentation", prompt: "Beurteile eine technische Werbeaussage deiner Wahl aus dem Themenfeld Energie, Sensorik oder Laser. Lege Kriterien offen und trenne physikalischen Befund von Werturteil." },
    ],
  },
];
